- pkg/cluster/preinstall/tmpl/init_os.go
fix typo in initOs.sh.
systemctl stop firewald, lost a 'l'.
> fix firewalld typo

- pkg/bootstrap/os.go
- pkg/config/parse.go
Signed-off-by: zgldh <zgldh@hotmail.com>
Please check golang source:
`go/src/os/user/user.go`
``` golang
// Username is the login name.
Username string
// Name is the user's real or display name.
// It might be blank.
// On POSIX systems, this is the first (or only) entry in the GECOS field
// list.
// On Windows, this is the user's display name.
// On Plan 9, this is the contents of /dev/user.
Name string
```
The user.Name **might be blank**. And it is happening on my laptop `Linux version 5.8.6-1-MANJARO (builder@db927223e331)`
It's better to user user.Username instead.
> Change to user.Username

- Makefile
- README.md
- cmd/kk/main.go
- main.go
As we can see below, current PR could reduce about 3M of the binary file. But I don't know if it leads to new issues due to I haven't go through all the related code lines. So please don't hesitate to tell me if I missed anything.
```
-rwxr-xr-x  1 rick  staff    53M Nov  6 15:50 bin/darwin/amd64/kk
-rwxr-xr-x  1 rick  staff    56M Nov  6 15:50 bin/manager
```
> Using a separate entry-point can reduce the size of the binary file

- .github/workflows/release.yaml
- .goreleaser.yml
- Makefile
- README.md
[goreleaser](https://github.com/goreleaser/goreleaser) is a very popular tool in the Golang CLI area. I provide the following things:
* goreleaser config file
* GitHub action for publishing rpm and deb package to bintray
* documentation about this feature
> Notice: As you can see, there're two secrets that are needed. They are `GH_TOKEN` and `BINTRAY_TOKEN`.
I already have finished the test work. You can find [the release binary files](https://github.com/LinuxSuRen/kubekey/releases) which for test purposes.
Here is the [Kubesphere home page](https://bintray.com/kubesphere) in bintray.com.
This PR can close #376
> Using goreleaser to publish deb and rpm package

- .github/workflows/release.yaml
GitHub automatically creates a `GITHUB_TOKEN` secret.
> update secret name

- .goreleaser.yml
Please see also a brother pull request which is similar to this.
https://github.com/kubesphere/kubesphere/pull/3160
Below is the comparision result:
Before using upx:
```
-rwxr-xr-x  1 rick  staff    54M Nov 28 22:51 kubekey/bin/kk_darwin_amd64/kk
```
After using upx:
```
-rwxr-xr-x  1 rick  staff    22M Nov 28 22:53 kubekey/bin/kk_darwin_amd64/kk
```
> Reduce the binary file size by upx

- .github/workflows/release.yaml
- .goreleaser.yml
Align the binary name to the previous one.
I test this via `goreleaser release --skip-publish --rm-dist`
Below is the partial log output:
```
• archives
• creating                  archive=bin/kubekey-v1.1.4-linux-arm64.tar.gz
• creating                  archive=bin/kubekey-v1.1.4-linux-amd64.tar.gz
• creating source archive
• pipe skipped              error=source pipe is disabled
• linux packages
• creating                  file=bin/kubekey-v1.1.4-linux-64bit.rpm
• creating                  file=bin/kubekey-v1.1.4-linux-arm64.deb
• creating                  file=bin/kubekey-v1.1.4-linux-arm64.rpm
• creating                  file=bin/kubekey-v1.1.4-linux-64bit.deb
```
**Open Question**
* Do we need Linux Packages for kk?
I find there is no Linux package for kk on [the last release …
> Use kubekey as the offical binary name instead of kk

- cmd/cluster.go
- cmd/kk/main.go
- cmd/version.go
- pkg/config/parse.go
- pkg/deploy/kubesphere.go
- version/k8s.go
Nightly build is different from the latest version. For example, if the latest or the version from yesterday has some bugs, then users can have another choice instead of don't know how to deal with it.
There's two completion support in this PR. With this feature, users don't need to remember the exact version anymore.
```
[root@i-vhxkszk5 kubekey]# kk create cluster --with-kubernetes [tab][tab]
v1.15.12  v1.16.10  v1.16.12  v1.16.13  v1.16.8   v1.17.0   v1.17.4   v1.17.5   v1.17.6   v1.17.7   v1.17.8   v1.17.9   v1.18.3   v1.18.5   v1.18.6   v1.18.8   v1.19.0
[root@i-vhxkszk5 kubekey]# kk create cluster --with-kubernetes v1.19.0 [tab][tab]
nightly-20201227  v2.1.1            v3.0.0
```
> Add nightly build support

- pkg/plugins/network/calico/tmpl-v1.16+.go
- pkg/plugins/network/calico/tmpl-v1.16-.go
1. Specify `can-reach=$(NODEIP)` as the `IP_AUTODETECTION_METHOD`.
2. Add `typha` for old calico manifests.
> update calico manifests

- .github/dependabot.yml
- .github/release-drafter.yml
- .github/settings.yml
There're three parts in the PR.
We don't need to do anything. It works once it is part of this project.
This bot can generate the release draft automatically base on the PR title and labels.
For the administrators for the project, you probably need to install the [release-drafter](https://github.com/apps/release-drafter) so it can work.
The benefits are obvious, anyone can help to improve the project settings. For example, improve the possible labels, project description, and so on. Only the admin can do that before having this.
We don't need to do anything. It works once it is part of this project.
> Automatic the go depend, release draft, project settings

- cmd/cluster.go
- cmd/root.go
- pkg/cluster/preinstall/preinstall.go
- pkg/install/install.go
- pkg/util/executor/executor.go
- pkg/util/manager/manager.go
This PR provider an extension point for downloading tools, for example, users can set the timeout, proxy, or retry under some poor network environment. Or users even can choose another cli, it might be wget. Perhaps we should have a build-in download function instead of totally rely on the external one.
> Add user defined tools download command option

- .github/workflows/release.yaml
- .goreleaser.yml
- README.md
The target binary filename was changed from `kubekey` to `kk`. You can download it from [here](https://github.com/LinuxSuRen/kubekey/releases/tag/v1.0.13).
```
[root@i-credeh69 test]# wget https://github.com/LinuxSuRen/kubekey/releases/tag/v1.0.13
[root@i-credeh69 test]# tar xzvf kubekey-v1.0.13-linux-amd64.tar.gz
README.md
README_zh-CN.md
kk
```
> Rename binary filename from kubekey to kk

- pkg/kubernetes/preinstall/prepull_images.go
- pkg/plugins/storage/local-volume/openebs.go
- update openebs image version to 2.9.0
- use latest operator yaml
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>
> chore(openebs): update openebs version to 2.9.0

- pkg/kubernetes/preinstall/prepull_images.go
- pkg/plugins/storage/local-volume/openebs.go
Signed-off-by: Roland.Ma <rolandma@yunify.com>
Upgrade openebs to 2.10.1 to fix vulnerabilities.
> Upgrade openebs to 2.10.1

- pkg/kubernetes/config/v1beta2/kubeadm.go
This pr fixes the problem that  APIEndpoints are missing when there are multiple master nodes.
> fix: missing APIEndpoints when multiple masters

- apis/kubekey/v1alpha1/cluster_types.go
- apis/kubekey/v1alpha1/default.go
- config/crd/bases/kubekey.kubesphere.io_clusters.yaml
- pkg/cluster/add/add.go
- pkg/cluster/install/install.go
- pkg/cluster/install/tasks.go
- pkg/cluster/upgrade/upgrade.go
- pkg/config/from_cluster.go
- pkg/config/generate.go
- pkg/k3s/config/service.go
- pkg/k3s/nodes.go
- pkg/kubernetes/config/v1beta2/kubeadm.go
- pkg/kubernetes/master.go
- pkg/kubernetes/nodes.go
- pkg/kubernetes/preinstall/prepull_images.go
- pkg/loadbalancer/haproxy.go
This PR is to add a HA plan for creating cluster. This plan is the same as this repo [kubespray](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ha-mode.md). 
In short, the kubelet of each master nodes connects the local apiserver and the kubelet of each worker nodes connects the local haproxy server that proxy the traffic to every apiserver.
Now it's only support kubernetes, i will support the k3s as soon as possible.
> Feature: Add internal LB haproxy for kubernetes.

- apis/kubekey/v1alpha1/cluster_types.go
- pkg/cluster/add/add.go
- pkg/cluster/install/install.go
- pkg/etcd/etcd.go
- pkg/etcd/tmpl/etcd.go
- pkg/kubernetes/master.go
There is a bug in adding nodes when the hosts order is different from the original order.
The original config file:
```
hosts:
- {name: node1, address: 192.168.0.3, internalAddress: 192.168.0.3, user: root, password: password}
- {name: node2, address: 192.168.0.4, internalAddress: 192.168.0.4, user: root, password: password}
- {name: node3, address: 192.168.0.5, internalAddress: 192.168.0.5, user: root, password: password}
roleGroups:
etcd:
- node1
- node2
- node3
master:
- node1
- node2
- node3
worker:
- node1
```
When adding nodes, the config:
```
hosts:
- {name: node4, address: 192.168.0.10, internalAddress: 192.168.0.10, user: root, password: password}
- {name: node5, address: 192.168.0.11 internalAddress: 192.168.0.11, user: root, password: password}
- {name: node1, address: …
```
> fix: the bug that the config file is different from the original order

- pkg/cluster/upgrade/precheck.go
> Fix "Println arg list ends with redundant newline" when exec go vet

- apis/kubekey/v1alpha1/default.go
1. Remove the lb configuration limit for allinone. 
2. When the number of nodes in the ControlPlane is above 1, lb should be set up. 
> Refine the verification of the lb configuration

- pkg/plugins/network/calico/tmpl-v1.16+.go
Remove the asNumber and peerIP dependencies to keep in line with official calico, calicoctl will detect the dependencies
> Remove the asNumber and peerIP dependencies

- README.md
- README_zh-CN.md
Using the lower version of the Linux Kernel, the cluster can experience problems during the operation.
https://garyhuang123.github.io/kubernetes/2019/03/21/the-analysis-of-kernel-and-os-for-running-kubernetes.html
https://github.com/kubernetes/kubernetes/issues/61937
> Add the requirement for Linux Kernel Version

- pkg/kubernetes/config/v1beta2/kubeadm.go
The localAPIEndpoint of each master should be its own IP address.
> fix: localAPIEndpoint of each master is set to master1's address

- pkg/kubernetes/preinstall/prepull_images.go
The PullImages() function will invoked by install, add, and upgrade tasks. The ExistNode() condition will make node which is ready to upgrade the version doesn't pull images.
> fix: if the node is exist in cluster that will not pull images

- cmd/add_nodes.go
- cmd/cluster.go
- cmd/root.go
- config/manager/manager.yaml
- controllers/kubekey/cluster_controller.go
- pkg/common/kube_action.go
- pkg/common/kube_module.go
- pkg/common/kube_prepare.go
- pkg/common/kube_runtime.go
- pkg/core/connector/host.go
- pkg/core/connector/interface.go
- pkg/core/connector/runtime.go
- pkg/core/module/task_module.go
- pkg/core/pipeline/pipeline.go
- pkg/core/task/remote_task.go
- pkg/pipelines/add_nodes.go
* Add ignore-err option
Sometimes we need to ignore the error host and make the pipeline force run. This PR i add a ignore-err option, can do this. When some hosts report error, kk will remove the host from runtime hosts array. After that, all of tasks will not execute actions on that host. And finally, the pipeline will still report an error `there are some error in your spec hosts` to display this pipeline run result is not fully successful.
> dev-v2.0.0: add ignore-err option

- pkg/kubesphere/manifests.go
Fix a bug that private registry can't be set when os env `KKZONE` is `cn`
> [release-1.2]: fix a bug that private registry can't be set when os env KKZONE is cn

- config/manager/manager.yaml
- controllers/kubekey/cluster_controller.go
- controllers/kubekey/cluster_controller_test.go
Fix kk controller-manager can't get correct etcd nodes info
If the cr `cluster` defines a existed cluster, controller will find the `kubeadm-config` configmap to get the etcd endpoints at first, and if the `kubeadm-config` is not found, controller will add etcd info by `.spec.roleGroups` field of  the cr `cluster`.
> fix kk controller-manager can't get correct etcd nodes info

- pkg/common/loader.go
Modify the all-in-one cluster name.
The cluster name will be used to create a configmap, and configmap's name needs to consist of lower case alphanumeric characters.
> modify all-in-one cluster name

- pkg/core/common/common.go
- pkg/core/connector/runner.go
Fix cp command report text busy error.
If using a cp command to copy a file to a target path that the file existed, the Linux may report a `text file busy` error. That caused by the file is been used. I modify the `mv` command to replace the `cp` command, which will not change the old file and the old file still be used by the process. Linux will change the process to use the new file and delete the old file when the process restarts.
> fix cp file text busy error

- pkg/bootstrap/os/templates/init_script.go
What does this PR do?
Fix sed command is not working in init script.
> fix: sed is not working in init script

- cmd/ctl/create/cluster.go
If the flag `--with-kubernetes` has a default value, the loader will think that the user set the `--with-kubernetes`, and the loader will override the `runtime.cluster.kubernetes.version` by the default k8s version.
> fix the default flag value makes kk can't create k3s cluster

- pkg/bootstrap/precheck/tasks.go
- pkg/certs/tasks.go
- pkg/filesystem/module.go
- pkg/filesystem/task.go
- pkg/k3s/tasks.go
- pkg/kubernetes/tasks.go
- pkg/pipelines/add_nodes.go
- pkg/pipelines/create_cluster.go
- pkg/pipelines/upgrade_cluster.go
Add a `ChownModule` to make sure the owner of `$HOME/.kube` is the user that is defined on `.spec.hosts`. Besides, I modify the code related to managing `$HOME/.kube`.
Before, the owner of `$HOME/.kube` is `root`, it will make a normal user get a response too long and get a throttling warning when the user uses the `kubectl` tools.
> fix error file mode on $HOME/.kube

- controllers/kubekey/cluster_controller.go
Signed-off-by: sunhaizhou [孙海洲] <sunhaizhou@kingsoft.cn>
> use raw string for regexp to avoid escape twice.

- .github/workflows/ci.yml
- .github/workflows/release.yaml
Modify the GitHub workflow and build using go 1.17
When I upgrade the `k8s.io` package dependencies, I can build kk on my desktop (go version 1.17), but it can't build on GitHub CI action (go version 1.16).
> modify the github workflow and build using go 1.17

- pkg/container/module.go
- pkg/container/prepares.go
Fix install container runtime failed.
If the field `.spec.registry.auths` is an empty string, this module will still run, and report a `no such file` error. So we need a `prepare` to make sure to skip.
> fix install container runtime failed

- apis/kubekey/v1alpha2/manifest_types.go
- apis/kubekey/v1alpha2/zz_generated.deepcopy.go
- config/crd/bases/kubekey.kubesphere.io_manifests.yaml
- pkg/artifact/manifest.go
- pkg/artifact/templates/manifest.go
- pkg/binaries/kubernetes.go
- pkg/files/file.go
Modify manifest's `containerRuntime` to a list. And it will make kk can detect and show multi-container runtimes from the cluster.
> modify manifest's containerRuntime to a list

- cmd/ctl/create/cluster.go
- pkg/kubesphere/kubesphere_test.go
- pkg/kubesphere/modules.go
- pkg/version/kubesphere/version_enum.go
- pkg/version/kubesphere/version_enum_test.go
What does this PR do?
Fix: generate kubesphere repo error. Before, if the flag `--with-kubesphere v3.2.1`, kk will generate a yaml file with `image: kubespheredev/kubesphere:v3.2.1`
> fix: generate kubesphere repo error

- cmd/ctl/delete/delete.go
- cmd/ctl/delete/delete_node.go
- pkg/pipelines/delete_node.go
fix cmd delete `nodes` to `node`, now only support delete one node.
> fix cmd delete node.

- pkg/kubesphere/modules.go
- pkg/kubesphere/tasks.go
- pkg/pipelines/upgrade_cluster.go
Fix: upgrade cluster apply a wrong and default cc. Ensure there is no cc config, and prevent resetting cc config when upgrading the cluster.
> fix: upgrade cluster apply a wrong and default cc

- pkg/artifact/module.go
- pkg/artifact/prepares.go
- pkg/artifact/tasks.go
Add an md5 check function in the UnArchiveModule. This can make kk do not always unarchive the artifact.
> Add an md5 check function in UnArchiveModule

- pkg/binaries/k3s.go
- pkg/binaries/kubernetes.go
- pkg/binaries/tasks.go
- pkg/container/containerd.go
- pkg/container/docker.go
- pkg/k3s/tasks.go
- pkg/kubernetes/tasks.go
fix: kk will use the wrong binary's path in the multi-arch environment. Before, the map key is a binary's name, so that will be overridden when in the multi-arch environment.
> fix: kk will use the wrong binary's path in the multi-arch environment

- pkg/artifact/containerd.go
- pkg/artifact/tasks.go
Artifact supports pulling images with skipping SSL certificate validation.
> artifact supports pulling images with skipping SSL certificate validation

- pkg/binaries/registry.go
- pkg/binaries/tasks.go
- pkg/bootstrap/registry/tasks.go
- pkg/common/common.go
- pkg/files/file.go
- pkg/images/images.go
1. Adjust the paths of registries‘ packages.
2. Push images to registry with auth is supported. 
> Fix: wrong paths of registries' packages

- pkg/bootstrap/os/templates/init_script.go
- pkg/kubernetes/templates/v1beta2/kubeadm_config.go
add pid limit and pid available for pod.
Kubernetes allows you to limit the number of processes running in a Pod. You specify this limit at the node level, rather than configuring it as a resource limit for a particular Pod. Each Node can have a different PID limit.
To configure the limit, you can specify the command line parameter set PodPidsLimit in the kubelet configuration file.
https://kubernetes.io/docs/concepts/policy/pid-limiting/#pod-pid-limits
https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#eviction-signals
> add pod pid limit and pid available

- apis/kubekey/v1alpha2/cluster_types.go
- apis/kubekey/v1alpha2/default.go
- apis/kubekey/v1alpha2/kubernetes_types.go
- config/crd/bases/kubekey.kubesphere.io_clusters.yaml
- pkg/common/kube_runtime.go
- pkg/kubernetes/tasks.go
- pkg/kubernetes/templates/v1beta2/kubeadm_config.go
- pkg/plugins/dns/tasks.go
- pkg/plugins/dns/templates/nodelocaldns_configmap.go
Support custom `dnsDomain` for cluster.
> Support custom dnsDomain for cluster

- pkg/artifact/manifest.go
Before, the manifest module detected the cluster images by `.node.Status.Images`, and these fields may contain some host local image that the k8s cluster doesn't use. So, this PR makes this module detect cluster images by pods' `containers` and `initContainers`.
> manifest module detects cluster images way by pods

- pkg/artifact/manifest.go
- pkg/bootstrap/os/module.go
- pkg/bootstrap/os/repository/repository_deb.go
- pkg/bootstrap/os/repository/repository_rpm.go
- pkg/bootstrap/os/rollback.go
- pkg/bootstrap/os/tasks.go
- pkg/common/kube_rollback.go
- pkg/core/module/task_module.go
- pkg/core/rollback/base.go
- pkg/core/rollback/interface.go
- pkg/core/task/local_task.go
- pkg/core/task/remote_task.go
- pkg/images/images.go
* Add a rollback feature to support restoring something when a task failed
* Revert #1012 
Sometimes, a task will do something on the os, like mounting an ISO file. But when the task failed, the ISO file is still mounted on the os. So, the `rollback` function makes us can do some custom things after the task failed.
> Add a rollback feature to support restoring something when a task failed

- apis/kubekey/v1alpha2/cluster_types.go
- docs/config-example.md
- pkg/config/templates/cluster.go
- pkg/images/tasks.go
> add namespaceOverride support for privateRegistry

- .github/PULL_REQUEST_TEMPLATE.md
Add a Github PR template that is the same as the one for KubeSphere.
> add a GitHub PR template

- pkg/artifact/tasks.go
- pkg/images/images.go
- pkg/images/images_test.go
/kind bug
Fix image name parse error.
Before, using the `-` to split the image name can not parse the following example:
```
registry.cn-beijing.aliyuncs.com-kubesphere-kube-apiserver:v1.21.5.tar
```
This PR, I change the image name policy to fix this bug, we use the `#` to split the image name
```
registry.cn-beijing.aliyuncs.com#kubesphere#kube-apiserver:v1.21.5.tar
```
Fixes #
```
```
```release-note
```
```docs
```
> fix image name parse err

- apis/kubekey/v1alpha2/default.go
- pkg/kubernetes/tasks.go
- pkg/kubernetes/templates/v1beta2/kubeadm_config.go
- pkg/loadbalancer/module.go
- pkg/loadbalancer/templates/haproxyConfig.go
/kind bug
LocalApiEndpoint and controlPlane should not share the same port in cluster. So this pr removes dependence of LocalApiEndpoint bindPort on the controlPlane's port.
Fixes 
https://github.com/kubesphere/kubekey/issues/1061
```
```
```release-note
```
```docs
```
> Fix: LocalApiEndpoint's bindPort uses controlPlane's port

- pkg/binaries/k3s.go
- pkg/binaries/module.go
- pkg/binaries/tasks.go
- pkg/images/images.go
- pkg/pipelines/artifact_export.go
- pkg/pipelines/create_cluster.go
/kind feature
Support export a k3s artifact and create a k3s cluster using the artifact.
```
After creating a k3s cluster using a private registry, need to configure the k3s `Registries Configuration File` and restart the k3s manually.
```
```release-note
```
- [Usage]: [K3s Registries Configuration File](https://rancher.com/docs/k3s/latest/en/installation/private-registry/)
> support k3s artifact

- pkg/kubesphere/modules.go
- pkg/kubesphere/tasks.go
- pkg/version/kubesphere/templates/cc_v321.go
/kind bug
KubeKey supports `NamespaceOverride` and is only used for deploying kubenretes cluster. However, when deploying KubeSphere at the same time, this parameter has no effect on the images of KubeSphere. When all images use the same namespace, it will lead to the failure of installation.
Therefore, this pr adds the support of `NamespaceOverride` for KubeSphere‘s images.
```release-note
None
```
> Add the support of NamespaceOverride for KubeSphere‘s images

- pkg/kubernetes/templates/v1beta2/kubeadm_config.go
/kind bug
When the kubernetes version is less than 1.21, setting `CSIStorageCapacity` in feature gates will cause the cluster to fail to start normally.
Fixes https://github.com/kubesphere/kubekey/issues/1073
> Fix: CSIStorageCapacity cause the cluster to fail to start normally

- pkg/bootstrap/registry/module.go
/kind cleanup
When installing harbor, if the registry's authentication information is filled in the configuration file in advance, the login to the  registry will fail because the harbor has not been started.
Therefore, the task of logging into the registry is useless in the module of installing harbor.
Fixes #
```
```
```release-note
Remove the login registry task in the installation harbor module
```
```docs
```
> Remove the login registry task in the installation harbor module

- apis/kubekey/v1alpha2/default.go
- cmd/ctl/upgrade/upgrade.go
- pkg/common/common.go
/kind bug
Fix the command missing default Kubernetes type.
Fixes #
```
```
```release-note
```
```docs
```
> fix the command missing default kubernetes type

- README.md
- docs/features.md
- docs/manifest_and_artifact.md
- docs/zh/manifest_and_artifact.md
Update features doc and README.
Fixes #
```
```
```release-note
```
```docs
```
> Update features doc

- pkg/core/util/util.go
/kind bug
Fixes #1151
Signed-off-by: cumirror <jacksontong@yunify.com>
> Fix #1151: Probabilistic panic when create clusters with multiple nodes

- .github/workflows/ci.yml
- .goreleaser.yml
- Makefile
- build.sh
/kind dependencies
> containers_image_openpgp: Use a Golang-only OpenPGP implementation for signature verification instead of the default cgo/gpgme-based implementation; the primary downside is that creating new signatures with the Golang-only implementation is not supported.
Add a build flag "containers_image_openpgp" to prevent dependency on gpgme.
This PR is used to support importing the [github.com/containers/image/v5](https://github.com/containers/image) package in KubeKey later.
Fixes #
```
```
```release-note
```
```docs
```
> add a build flag "containers_image_openpgp" 

- pkg/kubesphere/tasks.go
/kind bug
fix etcd client certs not found
Fixes #
```
```
```release-note
```
```docs
```
> fix etcd client certs not found

- pkg/bootstrap/os/templates/init_script.go
/kind bug
Remove zombie process crontab, in some situation, this cron will kill dockershim and make pod recreated
Fixes #
```
```
```release-note
NONE
```
```docs
```
> Remove zombie process crontab

- pkg/bootstrap/confirm/tasks.go
- pkg/bootstrap/precheck/tasks.go
While sudo package not installed, precheck not work expected.
/kind bug
Fixes #1196
prepare test env:
```bash
apt remove sudo
```
```release-note
None
```
> fix sudo not work expected

- .github/workflows/gen-repository-iso.yaml
- Makefile
- hack/gen-repository-iso/dockerfile.centos7
- hack/gen-repository-iso/dockerfile.debian10
- hack/gen-repository-iso/dockerfile.debian9
- hack/gen-repository-iso/dockerfile.ubuntu1604
- hack/gen-repository-iso/dockerfile.ubuntu1804
- hack/gen-repository-iso/dockerfile.ubuntu2004
- hack/gen-repository-iso/packages.yaml
Signed-off-by: muzi502 <muzi502.li@gmail.com>
1. Use a configuration file to manage the required packages instead of in Dockerfile, this way is more flexible and easier to maintain.
2. Build repository iso support debian9/debian10 and arm64 architecture.
3. Add github action workflow of auto build repository iso artifact.
Fixes #
```
```
```release-note
```
Usage: run `make build-iso-${OS}` command in kubekey repo
example: `make build-iso-centos7` will build centos7 system repository iso artifact
```shell
$ make build-iso-centos7
docker build  \
--platform linux/amd64 \
-o type=local,dest=./output \
-f hack/gen-repository-iso/dockerfile.centos7 \
hack/gen-repository-iso
[+] Building 7.8s (14/14) FINISHED
=> [internal] load build definition from dockerfile.centos7 …
```
> Optimize the process of build repository iso

- pkg/kubernetes/templates/v1beta2/kubeadm_config.go
if use docker as container  runtime,  the cgroup driver between `docker` and `kubelet` must be same.
> fix:  when use docker runtime , the `kk` check cgroup driver  wrong at the docker already deployed node

- pkg/bootstrap/os/templates/init_script.go
/kind bug
The kernel module `br_netfilter` will be overwritten, when the init os script is executed.
Fixes #
```
```
```release-note
```
```docs
```
> Fix kernel module br_netfilter missing

- pkg/core/connector/runner.go
/kind feature
Add a debug log print in the ssh runner. That will allow kk to print every command executed in debug mode.
Fixes #
```
```
```release-note
```
```docs
```
> add a debug log print in the ssh runner

- pkg/common/loader.go
- pkg/common/local_runtime.go
/kind bug
As the issue says, we need to specify the signature algorithm to avoid generating the RSA SHA-1 signature key.
Fixes #1290
```
```
```release-note
```
```docs
```
> fix: all-in-one mode generate rsa-sha2-512 signature key

- pkg/bootstrap/registry/module.go
- pkg/bootstrap/registry/tasks.go
- pkg/bootstrap/registry/templates/harbor.go
/kind feature
Fixes #
```
```
```release-note
```
```docs
if use kubekey install harbor, the package should be include "install.sh" sciprts,
the scripts can let harbor auto start, the command  `docker-compose up -d`
but it is not start, the reason is Compose does not wait until a container is “ready”.
the document  https://docs.docker.com/compose/startup-order/
```
> feature: support harbor automatically start

- pkg/artifact/tasks.go
/kind bug
If we do not remove the kubekey/artifact directory each time, then the exported artifact may contain previously downloaded binaries or images, which are different from what is specified in the manifest file.
Fixes #1316 
```
```
```release-note
```
```docs
```
> Fix: remove kubekey/artifact dir after exporting an artifact

- pkg/common/loader.go
/kind feature
AutoRenewCerts is enabled by default for creating an all-in-one cluster
Fixes #1318 
```
```
```release-note
```
```docs
```
> feature: AutoRenewCerts is enabled by default for creating an all-in-one cluster

- pkg/core/logger/logger.go
- pkg/core/logger/logger_test.go
/kind feature
show "WARN" and "ERRO" log level
Fixes #
```
```
```release-note
```
```docs
```
> feat: show "WARN" and "ERRO" log level

- pkg/bootstrap/confirm/tasks.go
/kind feature
Users can use "y" or "n" when confirming
Fixes #
```
```
```release-note
```
```docs
```
> feat: users can use "y" or "n" when confirming

- pkg/artifact/tasks.go
/kind bug
fix: print combined output when the cp command is executed with an error
Fixes #
```
```
```release-note
```
```docs
```
> fix: print combined output when the cp command is executed with an error

- README.md
- pkg/config/generate.go
- pkg/config/templates/cluster.go
- pkg/kubernetes/tasks.go
/kind bug
fix: the generated kk config file contains the "containerManager" by default
Fixes #
```
```
```release-note
```
```docs
```
> fix: the generated kk config file contains the "containerManager" by default

- pkg/pipelines/upgrade_cluster.go
/kind cleanup
Do not need to exec init_os script when upgrading the k8s cluster.
Fixes #
```
```
```release-note
```
```docs
```
> cleanup: do not need to exec init_os script when upgrading the k8s cluster

- pkg/kubernetes/tasks.go
- pkg/pipelines/create_cluster.go
/kind cleanup
As the title. We de not need to generate a kubeadm config when upgrading the cluster.
See:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
Fixes #
```
```
```release-note
```
```docs
```
> cleanup: do not need to generate kubeadm config and kubelet service file when upgrading the k8s cluster

- apis/kubekey/v1alpha2/default.go
- docs/config-example.md
- pkg/plugins/network/templates/calico_v1.16+.go
/kind feature
1. update calico to v3.23.2
2. Set the default value of veth_mtu to 0. By default, MTU is auto-detected, and explicitly setting this field should not be required.
Fixes  https://github.com/kubesphere/kubekey/issues/1364
```
```
```release-note
```
```docs
```
> Upgrade calico and set the default veth_mtu to 0

- apis/kubekey/v1alpha2/default.go
- pkg/bootstrap/precheck/module.go
- pkg/core/task/local_task.go
- pkg/core/task/remote_task.go
- pkg/core/util/time.go
- pkg/core/util/time_test.go
/kind bug
* Fix: GreetingModule sometimes occurs a timeout error. 
For now, the `timeout` value of the `GreetingModule` will be calculated by adding up the `timeout` values of all hosts
* Print human-readable task timeout error message.
Fixes #1288 
```
```
```release-note
```
```docs
```
> fix: GreetingModule sometimes occurs a timeout error

- pkg/common/loader.go
/kind feature
This makes kubekey more convenient to use and improves the user experience
Fixes https://github.com/kubesphere/kubekey/issues/1365
```
```
```release-note
Now, we can use both "1.23.6" and "v1.23.6" to create clusters.
```
```docs
```
> feat: support k8s and kubesphere version without "v"

- apis/kubekey/v1alpha2/cluster_types.go
- pkg/container/module.go
- pkg/container/templates/docker_config.go
- pkg/kubernetes/module.go
- pkg/kubernetes/tasks.go
- pkg/kubernetes/templates/v1beta2/kubeadm_config.go
/kind feature
This pr is to provide  data-root config when cni is docker and delete node add timeout for drain node
feature[#997](https://github.com/kubesphere/kubekey/issues/997)
```
```
```
```
Additional documentation, usage docs, etc.:
```
```
> support docker's data-root config

- pkg/etcd/module.go
- pkg/etcd/tasks.go
- pkg/etcd/templates/backup_script.go
- pkg/etcd/templates/backup_service.go
- pkg/etcd/templates/backup_service_test.go
/kind bug
Fix: the old etcd backup service does not work.
This PR uses the `timer` that is a unit of `systemd` to run a backup script regularly.
Fixes #
```
```
```release-note
```
```docs
```
> fix: etcd backup service does not work

- hack/fetch-kubernetes-hash.sh
/kind feature
Fixes #1408
This script is used to help adding new k8s version support. 
This script require [jq](https://stedolan.github.io/jq/) had been installed.
Hash file kubernetes-hashes.json would be created and can be diffed to pkg/files/file.go.
Reference:  #1306.
Related to: #1407.
> [#1408] add fetch-kubernetes-hash script

- cmd/ctl/alpha/artifact.go
- cmd/ctl/artifact/artifact.go
- cmd/ctl/root.go
- cmd/ctl/upgrade/phase.go
- cmd/ctl/upgrade/upgrade.go
- pkg/alpha/artifact.go
/kind feature
This pr is to divide the artifact import from origin pipelines, which can be an independent phase cmd for phase run functions to use.
Fixes #1389
```
1. I think artifact import should independent from those pipelines which will have phase run functions, so I put it in the artifact cmds which just use a more cmd "import" to achieve it.
2. Now the "phase.go" has no more cmd, but it can make the next work easily add other phase run cmds. So I decide to add it in this pr. 
```
```release-note
It provide user to use  " artifact import -g gzip_name " to import the artifact if needed as one step of the phase run. 
```
```docs
Usage:
kk artifact import [flags]
Flags:
--debug              Print detailed information
-g, --gzip string        Path to a artifact gzip
-h, --help …
```
> feat: add artifact import for phase run

- cmd/ctl/alpha/artifact.go
- cmd/ctl/alpha/binary.go
- cmd/ctl/upgrade/phase.go
- pkg/alpha/artifact/artifact.go
- pkg/alpha/binary/binary.go
- pkg/alpha/binary/modules.go
- pkg/alpha/precheck/modules.go
- pkg/alpha/precheck/task.go
- pkg/common/common.go
/kind feature
This pr is to divide the binary download and synchronization from origin pipelines, which can be an independent phase cmd for phase run functions to use.
Fixes #1417
```
I add "MaxK8sVersion" in the common to make sure the desired version should be higher than the max k8s version in nodes.
```
```release-note
It provide user to use  "upgrade phase binary " to download and synchroniz binary as one step of the upgrade phase run. 
```
```docs
Usage:
kk upgrade phase binary [flags]
Flags:
--debug                    Print detailed information
--download-cmd string      The user defined command to download the necessary binary files. The first param '%s' is output path, the second param '%s', is the URL (default "curl -L -o %s %s")
-f, --filename string          Path to a …
```
> feat: add upgrade binary cmd for cluster

- cmd/ctl/alpha/images.go
- cmd/ctl/upgrade/phase.go
- pkg/alpha/images/images.go
- pkg/alpha/images/modules.go
- pkg/alpha/precheck/modules.go
/kind feature
Fixes #1423 
```
This should be approval after the pr #1418 has been approval. 
```
```release-note
It provide user to use  "upgrade phase images " to pull the images as one step of the upgrade phase run. 
```
```docs
Usage:
kk upgrade phase images [flags]
Flags:
--debug                    Print detailed information
--download-cmd string      The user defined command to download the necessary binary files. The first param '%s' is output path, the second param '%s', is the URL (default "curl -L -o %s %s")
-f, --filename string          Path to a configuration file
-h, --help                     help for images
--ignore-err               Ignore the error message, remove the host which reported error and force to continue
--in-cluster               Running inside the cluster …
```
> feat: add images pull cmd for upgrade phase

- cmd/ctl/delete/delete_cluster.go
fix issue: https://github.com/kubesphere/kubekey/issues/1148
let below cmd works
```
./kk delete cluster --with-kubenetes v1.21.6-k3s
```
Signed-off-by: Deshi Xiao <xiaods@gmail.com>
Fixes #
```
```
```release-note
```
```docs
```
> fix: delete k3s cluster with kubenetes version

- pkg/bootstrap/os/module.go
- pkg/bootstrap/os/tasks.go
/kind bug
fix: chrony service name and config path in ubuntu and debian is diffrent to centos
Fixes # [1414](https://github.com/kubesphere/kubekey/issues/1414)
```
```
```release-note
```
```docs
```
> fix: fix ubuntu debian chrony bug

- cmd/ctl/alpha/nodes.go
- cmd/ctl/upgrade/phase.go
- pkg/alpha/nodes/modules.go
- pkg/alpha/nodes/nodes.go
- pkg/alpha/precheck/modules.go
- pkg/alpha/precheck/task.go
/kind feature
Fixes #1429
```
I change the getAllnodesK8sVersion of precheck modules, which just use in upgrade phase run. I can't confirm it have no problem.
```
```release-note
It provide user to use  "upgrade phase master " to upgrade master node as one step of the upgrade phase run. 
It provide user to use  "upgrade phase workers " to upgrade worker nodes  as one step of the upgrade phase run. 
```
```docs
Usage:
kk upgrade phase master [flags]
Flags:
--debug                    Print detailed information
--download-cmd string      The user defined command to download the necessary binary files. The first param '%s' is output path, the second param '%s', is the URL (default "curl -L -o %s %s")
-f, --filename string          Path to a configuration file
-h, --help …
```
> feat: add master and worker nodes upgrade cmd

- clients/clientset/versioned/fake/register.go
- clients/clientset/versioned/scheme/register.go
- cmd/ctl/delete/delete_cluster.go
- docs/commands/kk-delete-cluster.md
- pkg/common/kube_runtime.go
- pkg/container/containerd.go
- pkg/container/docker.go
- pkg/container/module.go
- pkg/core/util/file.go
- pkg/images/utils.go
- pkg/pipelines/delete_cluster.go
/kind feature
Sometimes, I need to delete all cri(docker/containerd) related configuration and data direcoties when delete the total cluster.
Fixes #1415 
```
```
```release-note
```
```docs
./kk delete cluster -f config.yaml --all
./kk delete cluster -f config.yaml -a
```
> [feature] Support clean CRI 

- README.md
- docs/k3s-versions.md
- docs/kubernetes-versions.md
show the k3s versions supported by kubekey
Fixes https://github.com/kubesphere/kubekey/issues/1432
Fixes #
```
```
```release-note
None
```
```docs
```
> docs: add k3s versions support

- pkg/container/module.go
- pkg/container/templates/containerd_config.go
/kind bug
DataRoot configuration in registry works for docker but not containerd.
Fixes #1449 
```
```
@24sama 
```release-note
```
```docs
```
> [bug] add dataRoot configuration support for containerd

- pkg/binaries/k8e.go
- pkg/binaries/module.go
- pkg/binaries/tasks.go
- pkg/common/common.go
- pkg/files/file.go
- pkg/k8e/k8e_status.go
- pkg/k8e/module.go
- pkg/k8e/prepares.go
- pkg/k8e/tasks.go
- pkg/k8e/templates/k8eService.go
- pkg/k8e/templates/k8eServiceEnv.go
- pkg/k8e/templates/killall_script.go
- pkg/k8e/templates/uninstall_script.go
- pkg/pipelines/add_nodes.go
- pkg/pipelines/artifact_export.go
- pkg/pipelines/create_cluster.go
- pkg/pipelines/delete_cluster.go
Support for deploying k8e #1359
Signed-off-by: Xiao Deshi <xiaods@gmail.com>
/kind feature
k8e - Simple Enterprise Kubernetes. I would like to adopt more enterprise features in a lightweight distribution, a binary component, k8e to provide all the k8s components.
it solid on enterprise LTS version
create cluster:
```
./bin/linux/amd64/kk create cluster --with-kubernetes v1.21.14-k8e
```
delete cluster:
```
./bin/linux/amd64/kk delete cluster --with-kubernetes v1.21.14-k8e
```
cc @24sama 
Feat Request https://github.com/kubesphere/kubekey/issues/1359
Fixes #
```
```
```release-note
```
```docs
```
> feat: add k8e install pipeline

- cmd/ctl/alpha/kubesphere.go
- cmd/ctl/upgrade/phase.go
- pkg/alpha/confirm/confirm.go
- pkg/alpha/confirm/task.go
- pkg/alpha/kubesphere/kubesphere.go
- pkg/alpha/precheck/modules.go
- pkg/alpha/precheck/task.go
/kind feature
Fixes #1440 
```
```
```release-note
It provide user to use  "upgrade phase kubesphere " to upgrade worker nodes  as one step of the upgrade phase run.
```
```docs
Usage:
kk upgrade phase kubesphere [flags]
Flags:
--debug                    Print detailed information
--download-cmd string      The user defined command to download the necessary binary files. The first param '%s' is output path, the second param '%s', is the URL (default "curl -L -o %s %s")
-f, --filename string          Path to a configuration file
-h, --help                     help for kubesphere
--ignore-err               Ignore the error message, remove the host which reported error and force to continue
--in-cluster               Running inside the cluster
--namespace string         KubeKey namespace to …
```
> feat: add upgrade kubesphere cmd

- pkg/bootstrap/os/templates/init_script.go
/kind bug
Fixed invalid syntax of /etc/sysctl.conf after executing init os script. 
log output:
`sysctl: /etc/sysctl.conf(103): invalid syntax, continuing...`
When using "awk print" to write to a file and read the same file at the same time, and the file size exceeds 4Kbytes, it will cause the file content to be truncated.
`awk ' !x[$0]++{print > "/etc/sysctl.conf"}' /etc/sysctl.conf`
Fixes #1453
```
```
```release-note
```
```docs
```
> fixed #1453 : invalid syntax of /etc/sysctl.conf after executing init os script

- exp/cluster-api-provider-kubekey/Makefile
- exp/cluster-api-provider-kubekey/main.go
- exp/cluster-api-provider-kubekey/pkg/clients/ssh/client.go
- exp/cluster-api-provider-kubekey/pkg/service/bootstrap/bootstrap.go
- exp/cluster-api-provider-kubekey/pkg/service/operation/file/binary.go
- exp/cluster-api-provider-kubekey/pkg/service/provisioning/cloudinit/action.go
- exp/cluster-api-provider-kubekey/pkg/util/filesystem/common.go
/kind bug
Fix the permission problem of SFTP for non-root users. 
The CAPKK uses the SFTP to `scp` files to the remote instance `/tmp/kubekey` directory and then uses `cp` command to copy them to their original remote path.
Fixes #
```
```
```release-note
```
```docs
```
> Fix the permission problem of sftp for non-root users.

- README.md
- README_zh-CN.md
fix: README format issue
Fixes #
```
```
```release-note
```
```docs
```
> fix: README format issue

- pkg/kubernetes/module.go
- pkg/kubernetes/tasks.go
/kind bug
Add retry for adding nodes labels.
When the `internalLoadBalancer: haproxy` is used, before the `haproxy` is started, the labeling fails because kubectl cannot connect to the kube-apiserver.
Fixes #
```
```
```release-note
```
```docs
```
> fix: failed to add labels to nodes

- pkg/certs/templates/certs_renew_service.go
fix: registry node missing certs file
/kind bug
this PR update k8s-certs-renew.timer to run each monday of every week.
Fixes #1506
```
```
```release-note
```
```docs
```
>  fix #1506: update k8s-certs-renew.timer to run each monday of every week

- apis/kubekey/v1alpha1/default.go
- apis/kubekey/v1alpha2/default.go
- pkg/plugins/network/modules.go
- pkg/plugins/network/tasks.go
- pkg/plugins/network/templates/kubectl_ko.go
- pkg/plugins/network/templates/kubeovn.go
/kind feature
- Update Kube-ovn to 1.10.6
-  Adjusting the structure of the Kube-ovn configuration file:split a simple file `network-plugin.yaml`  into three files `kube-ovn-crd.yaml`,`ovn.yaml` and `kube-ovn.yaml`.
Fixes #
```
```
```release-note
```
```docs
```
> Update Kube-ovn to 1.10.6

- apis/kubekey/v1alpha2/default.go
- apis/kubekey/v1alpha2/kubernetes_types.go
- docs/config-example.md
- pkg/kubernetes/templates/v1beta2/kubeadm_config.go
/kind feature
add kubelet pod pid limit
Fixes #
```
```
```release-note
```
```docs
```
> Add kubelet pod pid limit

- cmd/ctl/cri/cri.go
- cmd/ctl/cri/migrate_cri.go
- cmd/ctl/root.go
- docs/commands/kk-cri-migrate.md
- pkg/binaries/kubernetes.go
- pkg/binaries/module.go
- pkg/binaries/tasks.go
- pkg/bootstrap/confirm/module.go
- pkg/bootstrap/confirm/tasks.go
- pkg/common/kube_runtime.go
- pkg/container/containerd.go
- pkg/container/module.go
- pkg/pipelines/migrate_container.go
migrate
we add  migrate_cri
Fixes #
```
```
```release-note
```
```docs
```
> add  migrate_cri

- cmd/kk/pkg/images/tasks.go
- cmd/kk/pkg/images/utils.go
/kind bug
fix the image name parsing panic
#1581
```
```
```release-note
```
```docs
```
> fix the image name parsing panic

- cmd/kk/cmd/alpha/alpha.go
- cmd/kk/cmd/alpha/create.go
- cmd/kk/cmd/alpha/upgrade.go
- cmd/kk/cmd/root.go
- cmd/kk/cmd/upgrade/upgrade.go
- docs/commands/kk-create-phase.md
- docs/commands/kk-upgrade-phase.md
/kind feature
Add alpha before the phase run cmds to test and optimize them more easily and change the docs.
Fixes #
```
```
```release-note
```
```docs
Usage:
kk alpha create phase [command]
Available Commands:
binary      Download the binaries on the local
configure   Configure the k8s cluster with plugins, certs and PV
etcd        Install the ETCD cluster on the master
images      Down the container and pull the images before creating your cluster
init        Init the k8s cluster
join        Join the control-plane nodes and worker nodes in the k8s cluster
kubesphere  Install the kubesphere with the input version
os          Init the os configure
Usage:
kk alpha upgrade phase [command]
Available Commands:
binary      Download the binary and synchronize kubernetes binaries
images …
```
> fix: add alpha cmd before phase run cmds

- hack/version.sh
/kind bug
There is no version info in kk v3.0.1-alpha.0
So, this PR fixes the wrong path in go build ldflags.
Fixes #
```
```
```release-note
```
```docs
```
> fix wrong path in go build ldflags

- pkg/service/operation/file/containerd.go
- pkg/service/operation/file/crictl.go
- pkg/service/operation/file/docker.go
- pkg/service/operation/file/k3s.go
- pkg/service/operation/file/kubeadm.go
- pkg/service/operation/file/kubecni.go
- pkg/service/operation/file/kubectl.go
- pkg/service/operation/file/kubelet.go
- pkg/service/operation/file/runc.go
/kind bug
fix: a sha256 checking bug when downloading different versions of binary files.
Now, the binaries will download into the subdirectory, which is the directory tree as:
```
xxxx/kubeadm/v1.24.8/amd64/kubeadm
xxxx/kubeadm/v1.24.8/arm64/kubeadm
xxxx/kubeadm/v1.25.0/amd64/kubeadm
```
Fixes #
```
```
```release-note
```
```docs
```
> fix: a sha256 checking bug when downloading different versions of binary files

- .github/workflows/kubernetes-auto-support.yaml
- .github/workflows/release.yaml
- controllers/kkinstance/kkinstance_controller.go
- controllers/kkmachine/helpers.go
- controllers/kkmachine/kkmachine_controller.go
- test/e2e/config/e2e_conf.yaml
/kind bug
fix: add a lock to avoid duplicate IP assignments when creating KKInstances concurrently.
Fixes #
```
```
```release-note
```
```docs
```
> fix: add a lock to avoid duplicate IP assignments when creating KKInstances concurrently

- cmd/kk/pkg/loadbalancer/tasks.go
/kind bug
optimize the cmd used to get interface of nodes
Fixes #1690 
```
```
```release-note
```
```docs
```
> fix: redundant interface names leads to kubeVip pod failure

- cmd/kk/pkg/loadbalancer/tasks.go
bug
avoid deleting host ip route when do ""ip addr del " in module DeleteVIPModule
Fixes #1697
```
```
```release-note
```
```docs
```
> fix: module DeleteVIPModule cause node host interface down

- cmd/kk/pkg/version/kubesphere/ks_installer.go
- cmd/kk/pkg/version/kubesphere/templates/cc_v332.go
- cmd/kk/pkg/version/kubesphere/version_enum.go
/kind feature
Fixes #1705
```
```
```release-note
```
```docs
```
> feat(kk): ks v3.3.1 add support for k8s v1.24

- cmd/kk/pkg/bootstrap/os/tasks.go
- cmd/kk/pkg/k3s/templates/killall_script.go
- docs/commands/kk-delete-cluster.md
- docs/commands/kk-delete-node.md
- docs/network-configurations.md
- pkg/service/bootstrap/bootstrap.go
/kind feature
This PR allows kk to try to clean the network config created by flannel, cilium and calico when deleting a cluster.
Currently, `kubeadm reset` won't clean the legacy network config created by CNI. If we reinstall a cluster with the previous cluster config after deleting an existing one, new CNI pods may fail to start because of CNI bridge IP address conflicts. 
[k3s upstream](https://github.com/k3s-io/k3s/blob/master/install.sh#L677) now supports flannel cleanup, we need to keep synced with upstream, and add calico and cilium clean up abilities.
```
```
None
```release-note
```
```docs
```
> Feat: add cni virtual device deletion

- cmd/kk/pkg/k8e/tasks.go
- docs/k8e-versions.md
- version/components.json
kubernetes v1.25.5 is new stable long term support version.  
k8e distribution now support it.
/kind feature
let k8e support new kube stable version v1.25.5
Prior to Kubernetes 1.24, CNI plugins could also be managed by kubelet using the command line arguments cni-bin-dir and network-plugin. kubernetes 1.24 removes these command line arguments and CNI management is no longer the job of kubelet.
```
```
```release-note
add new kube version v1.25.5 to k8e distributions.
```
```docs
```
> feat: add v1.25.5 to k8e binary

- cmd/kk/pkg/container/docker.go
/kind bug
When using Harbor's robot account, the account format is similar to `robor$xxxxx`, and the special symbol `$` needs to be escaped to log in normally.
Fixes #
```
```
```release-note
```
```docs
```
> fix: docker login escape special characters

- cmd/kk/pkg/kubernetes/module.go
- cmd/kk/pkg/kubernetes/tasks.go
- cmd/kk/pkg/phase/kubernetes/modules.go
/kind cleanup
Fixes #
```
According to the definition of function `Execute`  about `SyncKubelet`, the task just changes the owner of `kubelet` binary. In addition, we can see the task of `SyncKubeBinary` do the work of syncing `kubelet` already.
As a result, maybe the name of  the task `SyncKubelet` changed to `ChownKubelet` is better for developers to understand.
```
```release-note
None
```
```docs
```
> chore: rename the task of SyncKubelet

- cmd/kk/pkg/kubernetes/tasks.go
- cmd/kk/pkg/plugins/dns/module.go
/kind cleanup
Fixes #
```
Fix the spelling mistakes of the tasks:
- `generateCoreDNSSvc` in `ClusterDNSMoule` 
- `generateCoreDNSSvc` in `OverrideCoreDNSService`
```
```release-note
None
```
```docs
```
> chore: fix spelling mistakes of  the tasks in coredns module

- cmd/kk/pkg/k3s/module.go
- cmd/kk/pkg/k3s/tasks.go
- cmd/kk/pkg/k8e/module.go
- cmd/kk/pkg/k8e/tasks.go
- cmd/kk/pkg/kubernetes/module.go
- cmd/kk/pkg/kubernetes/tasks.go
/kind bug
Add worker label according to host role
Fixes #
```
```
```release-note
```
```docs
```
> fix: Add worker label according to host role

- cmd/kk/pkg/etcd/module.go
- cmd/kk/pkg/etcd/tasks.go
/kind bug
fix: Add multiple etcd nodes failed
https://github.com/kubesphere/kubekey/issues/1837
Fixes #
```
```
```release-note
```
```docs
```
> fix: Add multiple etcd nodes failed

- cmd/kk/pkg/images/tasks.go
/kind/feature
Fixes #
```
add retry when push image error,without return error。
```
```release-note
```
```docs
```
> add default retry for artifact push image when some image push failed

- Makefile
- cmd/kk/pkg/kubernetes/tasks.go
- cmd/kk/pkg/kubernetes/templates/kubelet_env.go
- docs/config-example.md
/kind feature
support kebelet start custom argument when installing k8s.
Fixes #
https://github.com/kubesphere/kubekey/issues/1855
> support custom argument when start the kubelet

- cmd/kk/pkg/bootstrap/os/tasks.go
/kind bug
If we create cluster with VXLAN mode before，and when we reinstall the cluster with VXLAN mode again，we will meet the situation that we can not ping other nodes's pod. Because the VXLAN does not send the package to other node. This situation will occur at some calico version. 
We clean up the VXLAN interface when delete cluster, then reinstall the cluster with VXLAN mode again. The Calico VXLAN mode network works well.
So we need clean up the VXLAN interface when we delete the cluster.
> add clean up the VXLAN interface when delete the cluster

- cmd/kk/pkg/kubernetes/templates/v1beta2/kubeadm_config.go
/kind bug
Fix installation error.
> Failed to get container runtime cgroup driver.: Failed to exec command: sudo -E /bin/bash -c "containerd config dump | grep SystemdCgroup"
Fixes #1853
> [#1853] update the way to get containerd cgroup driver config

- cmd/kk/pkg/kubernetes/templates/v1beta2/kubeadm_config.go
If not, when we name a node as number, kubeadm will init failed:
```log
json: cannot unmarshal number into Go struct field APIServer.apiServer.certSANs of type string
```
> fix(kubeadm): certSANs use quotes, avoid to be parsed as int

- cmd/kk/pkg/registry/docker_registry_config.go
/kind cleanup
"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16
Fixes #
```
```
```release-note
None
```
```docs
```
> chore: remove refs to deprecated io/ioutil

- api/v1beta1/auth_types.go
- api/v1beta1/kkcluster_webhook.go
- config/crd/bases/infrastructure.cluster.x-k8s.io_kkclusters.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_kkclustertemplates.yaml
- config/crd/bases/infrastructure.cluster.x-k8s.io_kkinstances.yaml
- controllers/kkinstance/kkinstance_controller.go
/kind bug
add secret option for auth-type in kkcluster. the secret should container to key: `password` and `privateKey`. It will set default values for `password` and `privateKey` in `kkcluster.spec.nodes.auth`.
https://github.com/kubesphere/kubekey/issues/1875
> fix: add secret option to auth-type.

- docs/config-example.md
The example config file does not match with the latest code lines.
Fixes #
```
None
```
See also https://github.com/kubesphere/kubekey/blob/ba5daf36534f007a8afd92f8f0706e818adf80ca/cmd/kk/apis/kubekey/v1alpha2/etcd_types.go#L36
```release-note
None
```
```docs
None
```
> docs: correct the etcd related number type

- cmd/kk/pkg/artifact/manifest.go
/kind bug
fix: fix ubuntu version get
Fixes #1910
```
```
```release-note
None
```
```docs
```
> fix: fix ubuntu version get

- cmd/kk/pkg/images/tasks.go
- cmd/kk/pkg/images/utils.go
/kind bug
for imagefullName support more than two slash-separated, like 10.121.218.184:30002/cache/goharbor/notary-server-photon:v2.8.2, While the [OCI Distribution Specification](https://github.com/opencontainers/distribution-spec) supports more than two slash-separated components
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: imagefullName support more than two slash-separated

- cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
- cmd/kk/apis/kubekey/v1alpha2/default.go
- docs/config-example.md
/kind feature
support to use external dns to resolve control-plane domain
Fixes #
```
```
```release-note
```
```docs
```
> support to use external dns to resolve control-plane domain

- cmd/kk/pkg/plugins/network/templates/calico_v1.16+.go
- cmd/kk/pkg/plugins/network/templates/calico_v1.16-.go
Fixes #
```
```
```release-note
```
```docs
```
this calico felix config for k8s node with multi nics and different subnet ip, but i can connect with each other in underlay network. calico felix route rule source IP default  determined by the kernel; but in the scene i describe it will use nic IP which is not we want. with this config commited, we can avoid this happen .
> calico use node ip for felix route rule source ip

- cmd/kk/pkg/core/connector/ssh.go
/kind bug
fix  scp permission denied err
Fixes #1880
```
when do sudoscp  first call r.Conn.MkDirAll  to make remoteTmp  dir,  then scp file to remoteTmp  dir , 
at last move remoteTmp   to remote.   
note:  remoteTmp   = filepath.Join(common.TmpDir, remote)
pkg/core/connector/runner.go
func (r *Runner) SudoScp(local, remote string) error {
...
if err := r.Conn.MkDirAll(baseRemotePath, "", r.Host); err != nil {
return err
}
...
}
pkg/core/connector/ssh.go
func (c *connection) MkDirAll(path string, mode string, host Host) error {
if mode == "" {
mode = "775"
}
mkDstDir := fmt.Sprintf("mkdir -p -m %s %s || true", mode, path)
...
}
the reason for "scp  permission denied"  is  command "mkdir -p -m" only affect the last dir in path,   for example :
mkdir -p -m 775 …
```
> fix: scp permission denied 

- cmd/kk/pkg/binaries/kubernetes.go
/kind ui
/kind cli
Micro-fix info message.
old:
>downloading arm64 crictl v1.24.0 ...
> crictl is existed
>downloading arm64 etcd v3.4.13 ...
>etcd is existed
should be:
>downloading arm64 crictl v1.24.0 ...
> crictl exists.
>downloading arm64 etcd v3.4.13 ...
>etcd exists.
> update binary-check message

- cmd/kk/pkg/k8e/k8e_status.go
bug fixing
check slice ahead to avoid panic cause by slice index out of bounds.
when `sep` not empty, `strings.Split` always return a slice which length larger than one, so the original check not working.
if check not passed, return err for retry.
the pr is just a random thing for me after meeting a panic when using kk to setup my k8e cluster.
```
panic: runtime error: index out of range [0] with length 0
goroutine 563 [running]:
github.com/kubesphere/kubekey/v3/cmd/kk/pkg/k8e.(*K8eStatus).SearchNodesInfo(0xc0000aeb40, {0x2757f10?, 0xc000a12f00?})
github.com/kubesphere/kubekey/v3/cmd/kk/pkg/k8e/k8e_status.go:106 +0x33e
github.com/kubesphere/kubekey/v3/cmd/kk/pkg/k8e.(*GetClusterStatus).Execute(0xc000011608, {0x2757f10, 0xc000a12f00}) …
```
> fix: slice overflow panic sometimes during node info parsing

- cmd/kk/apis/kubekey/v1alpha2/default.go
- cmd/kk/apis/kubekey/v1alpha2/network_types.go
- cmd/kk/pkg/plugins/network/modules.go
- cmd/kk/pkg/plugins/network/templates/calico_v1.16+.go
- hack/sync-components.sh
- version/components.json
/kind feature
Update calico to v3.26.1 and support disable create default ippool
Fixes #
```
```
```release-note
Update calico to v3.26.1 and support disable create default ippool
```
```docs
```
> Update calico to v3.26.1

- cmd/kk/pkg/pipelines/add_nodes.go
/kind feature
This is a missing part of https://github.com/kubesphere/kubekey/pull/1901
Fixes #
```
```
```release-note
None
```
```docs
None
```
> feat: move the preInstall step ahead in the add node pipeline

- cmd/kk/apis/kubekey/v1alpha2/network_types.go
/kind bug
Fixes #
change default calico arg: IPV4POOL_NAT_OUTGOING to true
```
```
```release-note
change default calico arg: IPV4POOL_NAT_OUTGOING to true
```
```docs
```
> fix(calico): change default calico arg: IPV4POOL_NAT_OUTGOING to true

- cmd/kk/pkg/files/file.go
calculate sha256 file checksum by streaming in order to compatible with machine with limited memory size.
/kind feature
When I initiate harbor registry by kubekey command tool like this:
```shell
./kk init registry
```
It fails time by time with error message "Killed". After debug step by step, I found the root cause in file `cmd/kk/pkg/files/file.go` function `sha256sum`
```go
func (b *KubeBinary) Download() error {
for i := 5; i > 0; i-- {
...
if err := b.SHA256Check(); err != nil {
...
}
}
return nil
}
// SHA256Check is used to hash checks on downloaded binary. (sha256)
func (b *KubeBinary) SHA256Check() error {
output, err := sha256sum(b.Path())
...
return nil
}
func sha256sum(path string) (string, error) {
file, err := os.Open(path)
if err != nil {
return "", err
}
defer file.Close() …
```
> calculate sha256 file checksum by streaming

- cmd/kk/pkg/container/docker.go
ensure docker credentials save to $HOME/.docker/config.json
kind bug
centos  use "Defaults    always_set_home"  in /etc/sudoers， then  HOME in env is  "/root"  when use sudo ，so  config.json is always saved to /root/.docker/config.json，then  "mkdir -p /.docker && cp -f $HOME/.docker/config.json /.docker/ && chmod 0644 /.docker/config.json "  will be failed.  Kubelet  pull images from harbor pivate  registry    ImagePullBackOff 
Fixes #
```
```
```release-note
```
```docs
```
> fix  pull images from harbor pivate  registry  ImagePullBackOff 

- cmd/kk/pkg/loadbalancer/tasks.go
get redundant interface for kubevip when add k8s nodes
kind bug
first deploy k8s which has only one nodes, then use kk add 2 nodes to k8s cluster, and use kube-vip for loadbalancer.  now  the firs node vip_interface contains two calico interfaces:
```
- name: vip_interface
value: calic3e37beb20a scope link src 192.168.122.101
cali97a236bb38c scope link src 192.168.122.101
eno1
```
Fixes #
```
```
```release-note
```
```docs
```
> fix: redundant interface for kubevip when add k8s nodes

- cmd/kk/pkg/etcd/tasks.go
- cmd/kk/pkg/etcd/templates/backup_script.go
/kind bug
backup script doesn't work when set etcd dataDir to another dir except '/var/lib/etcd'
> fix: backup script doesn't work when set etcd dataDir to another dir except '/var/lib/etcd'

- cmd/kk/pkg/container/prepares.go
Fixes #
On certain machines with shells like zsh, errors may occur when using "if...which".
We can resolve this issue by replacing "which" with "command -v".
```bash
[qemu-41] ~ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
[qemu-41] ~ uname -a
Linux qemu-41 5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
before:
```
08:16:14 UTC message: [qemu-43]
downloading image: kubesphere/pause:3.8
08:16:14 UTC message: [qemu-45]
downloading image: kubesphere/pause:3.8
08:16:14 UTC message: [qemu-43]
pull image failed: Failed to exec command: sudo -E /bin/bash -c "env PATH=$PATH crictl pull kubesphere/pause:3.8 --platform amd64" 
env: ‘crictl’: No such file or directory: …
```
> Replace "which" with "command -v"

- cmd/kk/pkg/container/docker.go
- cmd/kk/pkg/container/module.go
- cmd/kk/pkg/container/templates/docker_service.go
when use kubekey docker and multus calico meet many issue with runtime ,  i meet docker runtime  stuck and restart it in stuck too.
when i use docker-ce deb package deploy, i found it use systemd manager docker and containerd  service like this pr to do .
i change docker runtime in that way fix the docker stuck issue.
Fixes #
```
```
```release-note
```
```docs
```
> make docker and containerd no parent-child process relationship

- cmd/kk/pkg/kubernetes/templates/kubeadm_config.go
/kind cleanup
The "ClusterConfiguration.DNS.Type" field has been removed in the [v1beta3 kubeadm config schema](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/#kubeadm-k8s-io-v1beta3-DNS) since CoreDNS is the only supported DNS server type by kubeadm. If we keep this field in v1beta3 kubeadm configuration, kubeadm will complain about this invalid field and print some warning logs during the installation process.
```
```
```release-note
None
```
```docs
```
> Fix: kubeadm v1beta3 dns config

- cmd/kk/cmd/upgrade/upgrade.go
- cmd/kk/pkg/bootstrap/precheck/module.go
- cmd/kk/pkg/common/kube_runtime.go
- cmd/kk/pkg/pipelines/upgrade_cluster.go
kind feature
add command flag "skip-dependency-check" when upgrade cluster 
```
example: kk upgrade cluster -f config-sample.yaml --skip-dependency-check
```
```release-note
```
```docs
```
> add flag skip-dependency-check when upgrade cluster

- cmd/kk/pkg/bootstrap/os/tasks.go
/kind bug
When deleting the cluster, delete the generated etcd certificates at the same time, to prevent the host from changing the internal ip, resulting in the redeployment failure.
None
>  fix : redeployment failure when internal ip is modified  

- cmd/kk/pkg/binaries/kubernetes.go
- cmd/kk/pkg/binaries/tasks.go
- cmd/kk/pkg/pipelines/artifact_export.go
/feature
Fixes #
Relax artifact strategy.
Configuring kubernetesDistributions will download kubeadm, kubelet, kubectl
Configuring component will download its value
Configuring image will download its value
the example like this:
```
```
```release-note
Relax artifact strategy. download which set.
```
```docs
```
> Relax artifact strategy

- cmd/kk/pkg/bootstrap/registry/module.go
Fixes #https://github.com/kubesphere/kubekey/issues/2156
```
```
```release-note
```
```docs
_   __      _          _   __
| | / /     | |        | | / /
| |/ / _   _| |__   ___| |/ /  ___ _   _
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
__/ |
|___/
21:09:27 CST [GreetingsModule] Greetings
21:09:29 CST message: [test-3]
Greetings, KubeKey!
21:09:29 CST success: [test-3]
21:09:29 CST [RegistryPackageModule] Download registry package
21:09:29 CST message: [localhost]
downloading amd64 harbor v2.5.3  ...
21:09:37 CST message: [localhost]
downloading amd64 docker 24.0.9  ...
21:09:37 CST message: [localhost]
downloading amd64 compose v2.2.2  ...
21:09:38 CST success: [LocalHost]
21:09:38 CST [ConfigureOSModule] …
```
> fix start docker error when init harbor

- cmd/kk/pkg/container/module.go
kind bug
Fixes #
```
kk version: build master
create cluster use containerd, there is no config for crictl in /etc/crictl.yaml
```
```release-note
```
```docs
```
> fix bug: not generate crictl config

- cmd/kk/pkg/plugins/network/templates/calico.tmpl
/kind bug
Added support for setting CALICO_IPV6POOL_BLOCK_SIZE, CALICO_IPV6POOL_VXLAN, CALICO_IPV6POOL_NAT_OUTGOING and FELIX_IPV6SUPPORT.
Hard coded CALICO_IPV6POOL_BLOCK_SIZE as 120. Need to make CALICO_IPV6POOL_BLOCK_SIZE and CALICO_IPV4POOL_BLOCK_SIZE configurable by having something like network.calico.ipv6PoolBlockSize and network.calico.ipv4PoolBlockSize.
Fixes #
```
```
```release-note
None
```
```docs
```
> Debugged calico.tmpl to support IPv6

- cmd/kk/pkg/bootstrap/registry/module.go
```release-note
fix config and start containerd on no registry node 
```
```docs
```
> fix config and start containerd on no registry node

- cmd/kk/pkg/kubernetes/module.go
/kind bug
Fixes #
```
kk version: build master
cmd: kk upgrade cluster -f config-sample.yaml 
when upgrade k8s v1.21.5 to v1.23.x , i receive error from kubeadm "postupgrade start version xxx is not support"
```
```release-note
```
```docs
```
> fix bug: upgrade k8s , kubeadm return coredns start version unsupported

- cmd/kk/pkg/container/docker.go
Fix the issue that the `/var/run/cri-dockerd.sock` file is not automatically deleted when stopping the cri-docker service, and when installing the cluster again, kk detects the existence of the `/var/run/cri-dockerd.sock` file and no longer installs the cri-docker service, which in turn leads to the failure of the cluster installation.
/kind bug
When stopping the cri-docker service, the `/var/run/cri-dockerd.sock` file is not automatically deleted.
When we install the cluster again, kk detects the existence of the `/var/run/cri-dockerd.sock` file and no longer installs the cri-docker service, which in turn leads to the failure of the cluster installation.
Fixes #
```
```
```release-note
```
```docs
```
> Fix the issue that the cri-dockerd.sock file is not automatically deleted when stopping the cri-docker service.

- cmd/kk/cmd/create/manifest.go
- cmd/kk/pkg/artifact/manifest.go
- cmd/kk/pkg/artifact/templates/manifest.go
Fixes #
```
```
```release-note
Support specifying Kubernetes when creating a manifest
```
```docs
```
> Support specifying Kubernetes when creating a manifest

- cmd/kk/cmd/artifact/export.go
- cmd/kk/pkg/artifact/tasks.go
- cmd/kk/pkg/common/artifact_runtime.go
Add Flag --skip-remove-artifact to remain kubekey/artifact dir after exporting an artifact
/kind feature
Some scenarios may require recreating artifact, such as adding a new image, which would need to re-download all files due to the deletion of the artifact directory. So, add an option to keep the artifact directory to reuse some of the files.
Fixes #
```
```
```release-note
```
```docs
```
> Add Flag --skip-remove-artifact to remain kubekey/artifact dir after exporting an artifact

- cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
- cmd/kk/pkg/bootstrap/customscripts/module.go
/kind feature
Support custom scripts executing on some specfic nodes when creating a cluster, make kubekey more flexible for different scenes. 
Take examples below：
```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
name: dubhe-open-cluster
spec:
hosts:
- { name: master, address: 192.168.10.1, internalAddress: 192.168.10.1, user: ubuntu, password: "ubuntu" }
- { name: storage, address: 192.168.10.2, internalAddress: 192.168.10.2, user: ubuntu, password: "ubuntu" }
roleGroups:
control-plane:
-  master
nfs-server:
- storage
system:
preInstall:
- name: install nfs server
role: nfs-server
bash: /bin/bash -x install_nfs_server.sh
materials:
- ./scripts/install_nfs_server.sh
```
preInstall script 'install nfs server' will only executed at storage node.
Fixes #
```
``` …
> feat: add CustomScripts.Role property

- cmd/kk/pkg/bootstrap/customscripts/tasks.go
/kind bug
when using custom scripts with materials, bash command' workdir is not at remoteTaskHome which saves the material files, so the custom scripts execute failed as it can not find the material files, change workdir to remoteTaskHome before bash command run makes it much better.
like this:
```yaml
spec:
system:
preInstall:
- name: install nfs server
role: nfs-server
bash: |
/bin/bash -x install_nfs_server.sh
materials:
- ./scripts/install_nfs_server.sh
```
Fixes #
```
```
```release-note
None
```
```docs
```
> feat: set CustomScriptTask workdir to remoteTaskHome

- cmd/kk/pkg/bootstrap/confirm/tasks.go
Use the following command to create a cluster: `kk create cluster -f cluster.yaml`.
If a Kubernetes version specified in cluster.yaml is not found in versions/components.json, the installation process should terminate. Instead of exiting after a failed SHA256 comparison following the download.
/kind feature
Optionally add one or more of the following kinds if applicable:
/kind flake
Check the supported k8s versions and terminate early in the precheck.
```
```
```release-note
no
```
> add check support k8s version

- cmd/kk/app/options/common.go
Fixes #
```
```
```release-note
none
```
```docs
```
> feat: change some description in command line.

- builtin/roles/precheck/env_check/defaults/main.yaml
- builtin/roles/precheck/env_check/tasks/etcd.yaml
/kind feature
base: https://github.com/kubesphere/kubekey/pull/2285
specify different standards for different environments
Fixes #
```
```
```release-note
change etcd_disk_wal_fysnc_duration_seconds to variable
```
```docs
```
> feat: change etcd_disk_wal_fysnc_duration_seconds to variable.

- builtin/roles/certs/renew-kubernetes/defaults/main.yaml
- builtin/roles/certs/renew-kubernetes/tasks/kube.yaml
- builtin/roles/certs/renew-kubernetes/tasks/main.yaml
fix: save default variable to defaults directory
/kind feature
base: https://github.com/kubesphere/kubekey/pull/2288
Fixes #
```
```
```release-note
save default variable to defaults directory for kk cert renew
```
```docs
```
> feat: save default variable to defaults directory

- cmd/kk/app/options/option.go
/kind bug
when use `--set` to set multi-line string value. The format of the string will change beyond expectations.
Fixes #
```
```
```release-note
unescape --set string
```
```docs
```
> fix: unescape --set string.

- cmd/kk/apis/kubekey/v1alpha2/etcd_types.go
- cmd/kk/pkg/etcd/tasks.go
- cmd/kk/pkg/etcd/templates/etcd_env.go
- cmd/kk/pkg/k3s/tasks.go
- cmd/kk/pkg/k8e/tasks.go
- cmd/kk/pkg/kubernetes/tasks.go
/kind feature
support custome etcd port
Fixes #
```
```
```release-note
support custome etcd port
```
```docs
```
> support custome etcd port

- cmd/kk/apis/kubekey/v1alpha2/etcd_types.go
- cmd/kk/pkg/etcd/tasks.go
- cmd/kk/pkg/etcd/templates/etcd_env.go
(cherry picked from commit 1dd1e54db02ab76cd39dc2a9b38ae9dd60ca1409)
(cherry picked from commit 3aa568db7bc09ce4543465f1cb4263df495fbf9f)
/kind feature
support custome etcd args
Fixes #
```
```
```release-note
support custome etcd args
```
```docs
```
> support custome etcd args

- builtin/roles/addons/cni/templates/calico/v3.27.yaml
- builtin/roles/init/init-os/templates/init-os.sh
/kind bug
when exec kubekey out of cluster. the /etc/hosts will occurred a incorrect record.like this:
the calico/node will get error ip for localhost like this:
Fixes #
```
```
```release-note
```
```docs
```
> fix: etc/hosts is incorrect when localhost is not belong cluster.

- cmd/kk/pkg/version/kubernetes/version_enum.go
/kind bug
fix: does not upgrade Kubernetes to v1.30
Fixes # https://github.com/kubesphere/kubekey/issues/2347
```
```
```release-note
fix: does not upgrade Kubernetes to v1.30
```
```docs
```
> fix: does not upgrade Kubernetes to v1.30

- cmd/kk/pkg/images/tasks.go
/kind bug
fix: does not push image to registry
```
16:21:47 CST success: [LocalHost]
16:21:47 CST [CopyImagesToRegistryModule] Push multi-arch manifest to private registry
16:21:47 CST Push multi-arch manifest list: 192.168.31.189/kubesphereio/thanos:v0.31.0
INFO[0220] Retrieving digests of member images
INFO[0220] trying next host - response was http.StatusNotFound host=192.168.31.189
WARN[0220] Couldn’t access image ‘“192.168.31.189/kubesphereio/thanos:v0.31.0-amd64”’. Skipping due to ‘ignore missing’ configuration.
16:21:47 CST message: [LocalHost]
push image 192.168.31.189/kubesphereio/thanos:v0.31.0 multi-arch manifest failed: all entries were skipped due to missing source image references; no manifest list to push
16:21:47 CST failed: [LocalHost]
error: …
```
> fix: does not push image to registry

- cmd/kk/app/options/option.go
- pkg/connector/kubernetes_ connector.go
- pkg/const/workdir.go
/kind feature
there is four dir in work_dir. should package it by default.
```text
workdir/
|-- projects/
|   |-- ansible-project1/
|   |   |-- playbooks/
|   |   |-- roles/
|   |   |   |-- roleName/
|   |   |   |   |-- tasks/
|   |   |   |   |   |-- main.yml
|   |   |   |   |-- defaults/
|   |   |   |   |   |-- main.yml
|   |   |   |   |-- templates/
|   |   |   |   |-- files/
|   |
|   |-- ansible-project2/
|   |-- ...
|
|-- runtime/
|-- group/version/
|   |   |-- pipelines/
|   |   |   |-- namespace/
|   |   |   |   |-- pipeline.yaml
|   |   |   |   |-- /pipelineName/variable/
|   |   |   |   |   |-- location.json
|   |   |   |   |   |-- hostname.json
|   |   |-- tasks/
|   |   |   |-- namespace/
|   |   |   |   |-- task.yaml
|   |   |-- configs/
|   |   |   |-- namespace/
|   |   | …
```
> fix: set default work_dir is "./kubekey".

- builtin/playbooks/artifact_export.yaml
- builtin/roles/init/init-artifact/tasks/download_by_curl.yaml
- builtin/roles/init/init-artifact/tasks/main.yaml
- builtin/roles/install/kubernetes/tasks/install_binaries.yaml
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
> fix: Change offline package directory.

- .github/workflows/gen-repository-iso.yaml
- hack/gen-repository-iso/dockerfile.almalinux90
- hack/gen-repository-iso/dockerfile.centos7
- hack/gen-repository-iso/dockerfile.debian10
- hack/gen-repository-iso/dockerfile.debian11
- hack/gen-repository-iso/dockerfile.ubuntu1804
- hack/gen-repository-iso/dockerfile.ubuntu2004
- hack/gen-repository-iso/dockerfile.ubuntu2204
- hack/gen-repository-iso/packages.yaml
/kind cleanup
remove centos and docker from dependencies repository
Centos7 is no longer maintained.
https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7
Kubekey uses binary to install docker, so removing Docker from the dependency package reduces the introduction of CVEs.
Fixes #
```
```
```release-note
remove centos and docker from dependencies repository
```
```docs
```
> remove centos and docker from dependencies repository

- builtin/roles/init/init-os/tasks/init_repository.yaml
- pkg/connector/local_connector.go
- pkg/connector/ssh_connector.go
/kind bug
- String formatting directly by `fmt.Sprintf` may cause unexpected error when executing a single command as a result of multiple double-quote transpositions. The more safe way is to use `exec.Command` function. 
- Fix from `file://` to `file:///` in `init_repository.yaml`
For more information on release notes see: https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md
-->
```release-note
- fix: ssh formatting exception bug when executing commands
- fix: from `file://` to `file:///` in `init_repository.yaml`
```
> fix: ssh formatting exception bug when executing commands

- pkg/connector/local_connector.go
- pkg/connector/ssh_connector.go
- pkg/converter/internal/functions.go
- pkg/converter/tmpl/template.go
- pkg/modules/command.go
…nction, to avoid unexpected `\r` symbolic with different os system.
/kind bug
Replace `bytes.TrimSuffix` with `bytes.TrimSpace` in `HostInfo` function, to avoid unexpected `\r` symbols with different os systems.
```release-note
fix: symbolic bug in GatherFacts function
```
> fix: symbolic bug in GatherFacts function

- builtin/roles/init/init-artifact/tasks/main.yaml
- pkg/connector/local_connector.go
- pkg/connector/ssh_connector.go
- pkg/project/helper.go
/kind bug
Fix some bugs: 
- Modify command execute way, which is more stable for most conditions.
- Fixed an issue where the `vars_files` parameter would not take effect due to the way the value was passed in the `dealVarsFiles` function.
- Ignore errors when executing `chrown` command.
```release-note
- Modify command execute way, which is more stable for most conditions.
- Fixed an issue where the `vars_files` parameter would not take effect due to the way the value was passed in the `dealVarsFiles` function.
- Ignore errors when executing `chrown` command.
```
> Modify execute command way, fix bug and optimize execution logic for playbook

- pkg/converter/tmpl/template.go
- pkg/executor/pipeline_executor.go
/kind bug
- fix the src path ends with `\n` in some conditions when using the `copy` playbook module.
- fix tags that don't work with `playbook.roles`.
```release-note
- fix the src path ends with `\n` in some conditions when using the `copy` playbook module.
- fix tags that don't work with `playbook.roles`.
```
> fix some bug when using playbook

- .github/workflows/kubernetes-auto-support.yaml
- cmd/kk/pkg/images/tasks.go
- hack/sync-components.sh
/kind cleanup
disable namespaceOverride on images push
kubekey already supports pushing multi-level path images. such as `docker.io/kubesphere/kube-apiserver:v1.31.2` to `dockerhub.kubekey.local/ks/kubesphere/kube-apiserver:v1.31.2`. So we can push images to the same project by this way.
configuration example:
```
...
registry:
privateRegistry: "dockerhub.kubekey.local/ks"   # If the repository is harbor, this configuration will push all images to the ks project
```
Fixes #
```
```
```release-note
disable namespaceOverride on images push
```
```docs
```
> disable namespaceOverride on images push

- .github/workflows/sync-vendor.yml
- builtin/roles/install/cri/defaults/main.yaml
- builtin/roles/install/image-registry/defaults/main.yaml
- go.mod
Reverts kubesphere/kubekey#2444
> Revert "fix: failed to install without image_registry"

- pkg/connector/connector.go
- pkg/const/common.go
- pkg/controllers/pipeline_controller.go
/kind design
Fixes #
```
```
```release-note
move env to _const.
```
```docs
```
> refactor: move env to _const.

- builtin/playbooks/artifact_images.yaml
- builtin/roles/install/image-registry/defaults/main.yaml
- builtin/roles/install/image-registry/tasks/load_images.yaml
- cmd/controller-manager/app/options/controller_manager.go
- cmd/kk/app/options/option.go
- cmd/kk/app/options/pipeline.go
- pkg/executor/pipeline_executor.go
run command `kk artifact images -c conf.yaml`
test config:
```yaml
apiVersion: kubekey.kubesphere.io/v1
kind: Config
metadata:
name: default
spec:
image_manifests:
- registry.cn-beijing.aliyuncs.com/kubesphereio/cni:v3.27.4
- registry.cn-beijing.aliyuncs.com/kubesphereio/coredns:1.8.6
- registry.cn-beijing.aliyuncs.com/kubesphereio/k8s-dns-node-cache:1.22.20
- registry.cn-beijing.aliyuncs.com/kubesphereio/kube-apiserver:v1.23.17
- registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controller-manager:v1.23.17
- registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controllers:v3.27.4
- registry.cn-beijing.aliyuncs.com/kubesphereio/kube-proxy:v1.23.17
- registry.cn-beijing.aliyuncs.com/kubesphereio/kube-scheduler:v1.23.17
- registry.cn-beijing.aliyuncs.com/kubesphereio/node:v3.27.4
- …
```
> fix: test kk push image to harbor.

- cmd/kk/cmd/create/cluster.go
- cmd/kk/pkg/common/kube_runtime.go
- cmd/kk/pkg/pipelines/create_cluster.go
- cmd/kk/pkg/pipelines/create_k3s_cluster.go
- cmd/kk/pkg/pipelines/create_k8e_cluster.go
(cherry picked from commit ea259db913552fd3a124aaa642615a8d1c4a0717)
/kind feature
support only etcd
Fixes #
```
```
```release-note
support only etcd
```
```docs
```
> support only etcd

- cmd/kk/pkg/images/images.go
- Updated the image pulling mechanism to conditionally format the pull command based on the command type (e.g., crictl).
- Improved code readability by reducing redundancy in command construction.
This change enhances flexibility in handling image pulls across different environments.
bug
`crictl pull` has never supported an argument named `platform`
Fixes [#TODO](https://github.com/kubesphere/kubekey/issues/2370)
```
```
None
```docs
```
> Refactor image pulling logic to support different pull commands, fix crictl pull failure

- cmd/kk/pkg/core/connector/ssh.go
bug
kk ssh to host will be blocked at [GreetingsModule] ，it will log nothing until timeout .
issue code:
debug output:
Fixes #
may fix: 
https://github.com/kubesphere/kubekey/issues/2046
https://github.com/kubesphere/kubekey/issues/2066
```
Not sure if it's a good solution, haven't done much testing
```
```release-note
None
```
```docs
```
> add set env to en_US.UTF-8.  make sure work with en language

- cmd/kk/pkg/container/templates/containerd_config.go
/kind bug
Correct indentation in containerd config tls module.
Fixes #
```
```
```release-note
```
```docs
```
> fix: containerd config tls module

- cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
- cmd/kk/pkg/images/images.go
- cmd/kk/pkg/images/tasks.go
- docs/config-example.md
/kind feature
Feat: add registry namespace rewrite policy, eg:
```yaml
registry:
namespaceRewrite:
policy: changePrefix
src: 
- namespace1
dest: library
```
Fixes #
```
```
```release-note
```
```docs
```
> feat: add registry namespace rewrite policy

- cmd/kk/apis/kubekey/v1alpha2/addons_types.go
- cmd/kk/pkg/addons/addons.go
- docs/addons.md
/kind feature
addon support yaml values to render yaml files, like helm values:
```yaml
- name: xxx                  # the name of addon
namespace: xxx             # namespace
sources:                    # support both yaml and chart
chart:                          
name: xxx              # the name of chart
repo:  xxx             # the name of chart repo (url)
path: xxx              # the location of chart  (path)
values:  xxx           # specify values for chart (string list)
valuesFile: xxx        # specify values file for chart (path / url)
yaml: 
path: []               # the location list of yaml (path / url) 
values:                # custom variables like helm values (not nessesary)
key1: xxx
map1:
subkey1: xxx
```
Fixes #
```
```
```release-note
```
```docs
```
> feat(addon): add yaml values to render yaml files, like helm values

- api/project/v1/conditional.go
- pkg/converter/tmpl/template.go
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
> fix: error parse when

- config/capkk/release/cluster-template.yaml
- pkg/controllers/infrastructure/inventory_controller.go
/kind feature
1.change default criSocket as same as dockerd
2. recreate hostCheckPlaybook when it's deleted.
Fixes #
```
```
```release-note
none
```
```docs
```
> feat: change default criSocket as same as dockerd

- cmd/kk/pkg/bootstrap/os/templates/init_script.go
- feature/builtin/roles/init/init-os/templates/init-os.sh
- pkg/service/bootstrap/templates/initOS.sh
Adding a node triggers drop _caches, and Pods using shm will restart
/kind bug
stop ufw firewalls and drop caches affect stability
Fixes #
stop ufw clears ipvs rules, affecting the k8s cluster stability。Dropping caches may cause service jitter and unexpected effects。
```
```
```release-note
Affects the node initialization phase when clusters are created or new nodes are added to existing clusters
```
```docs
```
> fix: Disabling ufw clears ipvs rules, and drop cache affects stability

- cmd/kk/pkg/kubernetes/templates/kubeadm_config.go
/kind bug
Solves the problem that kubelet's cgroup configuration always uses the default systemd
Fixes #
```
```
```release-note
Affects the node kubelet config when creating a cluster or adding a new node to an existing cluster
```
```docs
```
> fix: Fixed kubelet's cgroup configuration always using the default systemd

- cmd/kk/app/root.go
- cmd/kk/kubekey.go
/kind feature
default Silence logs. when use `-v xx` will print error stack log.
Fixes #
```
```
```release-note
Silence logs
```
```docs
```
> feat: Silence logs

- cmd/kk/pkg/core/connector/ssh.go
- cmd/kk/pkg/filesystem/task.go
Fix(connector): gracefully handle LANG environment setup failures
What this PR does / why we need it:
setenv 操作导致在kk 3.1.8/3.1.9 在centos/rockey linux 9.x下ssh fail ，导致无法正常部署； 经过验证不设置语言对在centos/rockey linux 9.x部署没有影响，建议setenv改为尽力而为方式更合适，失败情况下产生Warn即可。
Which issue(s) this PR fixes:
Fixes https://github.com/kubesphere/kubekey/issues/2546
(https://github.com/kubesphere/kubekey/issues/2546)
引入问题的原始pull， 影响3.1.7后面的所有版本
https://github.com/kubesphere/kubekey/pull/2489
```release-note
gracefully handle LANG environment setup
```
> Fix(connector): gracefully handle LANG environment setup failures-Update ssh.go

- builtin/core/playbooks/add_nodes.yaml
- builtin/core/roles/kubernetes/init-kubernetes/tasks/deploy_cluster_dns.yaml
- cmd/kk/app/builtin.go
- cmd/kk/app/builtin/add.go
- cmd/kk/app/options/builtin/add.go
- pkg/variable/helper.go
/kind feature
add command `add nodes` 
you can use two way to chose add nodes
1. define nodes in `add_nodes` group in inventory.yaml
```yaml
apiVersion: kubekey.kubesphere.io/v1
kind: Inventory
metadata:
name: default
namespace: default
spec:
groups:
add_nodes:
hosts:
- i-ntnxgrer
vars: null
etcd:
hosts:
- i-bi3mb19w
vars: null
k8s_cluster:
groups:
- kube_control_plane
- kube_worker
vars: null
kube_control_plane:
hosts:
- i-bi3mb19w
- i-ntnxgrer
- i-xcg3bb1u
vars: null
kube_worker:
hosts:
- i-bi3mb19w
- i-ntnxgrer
- i-xcg3bb1u
vars: null
hosts:
i-bi3mb19w:
connector:
host: 1.1.1.1
internal_ipv4: 1.1.1.1
i-ntnxgrer:
connector:
host: 1.1.1.2
internal_ipv4: 1.1.1.2
i-xcg3bb1u:
connector:
host: 1.1.1.3
internal_ipv4: 1.1.1.3
vars:
set_hostname: false
```
and then run `kk add nodes -i …
> feat: add command add nodes

- api/core/v1/config_types.go
- builtin/core/playbooks/hook/pre_install.yaml
- builtin/core/playbooks/precheck.yaml
- cmd/kk/app/options/option.go
- pkg/connector/connector.go
- pkg/connector/gather_facts.go
- pkg/connector/kubernetes_connector.go
- pkg/connector/local_connector.go
- pkg/connector/ssh_connector.go
- pkg/const/common.go
- pkg/const/workdir.go
- pkg/modules/command_test.go
- pkg/variable/helper.go
Add the `fact_caching` variable. Supported options: jsonfile, yamlfile, memory, or "" (empty string).
- `jsonfile`: Caches gathered facts locally at `<workdir>/runtime/gather_facts_caches/<inventory_name>.json`
- `yamlfile`: Caches gathered facts locally at `<workdir>/runtime/gather_facts_caches/<inventory_name>.yaml`
- `memory`: Caches facts in memory
- `""` (empty string): Disables caching and clears existing cache
test results:
Fixes #
```
```
```release-note
add gather_facts cache
```
```docs
```
> feat: add gather_facts cache

- builtin/core/playbooks/add_nodes.yaml
- builtin/core/playbooks/create_cluster.yaml
- builtin/core/roles/precheck/env_check/tasks/etcd.yaml
- builtin/core/roles/precheck/env_check/tasks/network.yaml
- cmd/kk/app/builtin/add.go
- cmd/kk/app/options/builtin/add.go
- cmd/kk/app/options/builtin/builtin.go
- cmd/kk/app/options/builtin/create.go
- cmd/kk/app/options/builtin/delete.go
- pkg/controllers/infrastructure/inventory_hostselector.go
- pkg/variable/helper.go
- pkg/variable/helper_test.go
- pkg/variable/variable.go
- pkg/variable/variable_get.go
- pkg/variable/variable_get_test.go
/kind feature
Support for auto-detecting nodes to add.
There are two executors available for adding nodes:
1. `kk add nodes`
This will add all nodes listed in the inventory that are not yet installed in the cluster.
2. `kk add nodes --control-plane node1,node2 --worker node1,node2`
This will only add the specified nodes to the cluster as control-plane or worker nodes.
Ensure their connection details are provided in the inventory's hosts file.
Fixes #
https://github.com/kubesphere/kubekey/pull/2557
```
```
```release-note
Support for auto-detecting nodes to ad
```
```docs
```
> feat: Support for auto-detecting nodes to add.

- cmd/kk/pkg/core/task/const.go
```
When downloading offline, it often timed out. Now it is set to 2 hours. Although it is already very long, the time is still not enough if you rely on all the downloads, so it will be extended to 5 hours.
```
```release-note
DefaultTimeout 2h->5h
```
```docs
```
> Update DefaultTimeout to 5h

- builtin/core/playbooks/add_nodes.yaml
- builtin/core/roles/init/init-os/tasks/init_localdns.yaml
- builtin/core/roles/init/init-os/tasks/main.yaml
- builtin/core/roles/init/init-os/templates/init-os.sh
- plugins/roles/etcd/restore/tasks/main.yaml
/kind feature
The init-os process has two types of logic:
1. **Always executes on every node**, including:
- `init_localdns`
- `init_ntpserver`
2. **Only executes on new Kubernetes nodes**, including:
- Downloading repo packages
- Running initialization scripts
- Resetting the `/tmp` directory
- Modifying the hostname
test results:
Fixes #
https://github.com/kubesphere/kubekey/issues/1787
```
```
```release-note
More detailed init-os rules
```
```docs
```
> feat: More detailed init-os rules

- builtin/core/playbooks/delete_nodes.yaml
- cmd/kk/app/builtin/add.go
- cmd/kk/app/builtin/delete.go
- cmd/kk/app/options/builtin/delete.go
- pkg/converter/internal/functions.go
- pkg/converter/tmpl/template_test.go
/kind feature
add `kk delete nodes` command:
```shell
Delete a cluster nodes
Usage:
kk delete nodes {node1 node2 ...} [flags]
Aliases:
nodes, node
Flags:
-a, --artifact string            Path to a KubeKey artifact
-c, --config string              the config file path. support *.yaml 
--container-manager string   Container runtime: docker, containerd. default is docker (default "docker")
-d, --debug                      Debug mode, after a successful execution of Playbook, will retain runtime data, which includes task execution status and parameters.
-h, --help                       help for nodes
-i, --inventory string           the host list file path. support *.yaml
-n, --namespace string           the namespace which playbook will be executed, all reference resources(playbook, config, …
```
> feat: add delete nodes command

- builtin/core/playbooks/delete_cluster.yaml
- builtin/core/playbooks/delete_nodes.yaml
- builtin/core/playbooks/vars/create_cluster_kubernetes.yaml
- builtin/core/playbooks/vars/delete_cluster.yaml
- builtin/core/roles/init/init-os/tasks/init_localdns.yaml
- builtin/core/roles/init/init-os/tasks/main.yaml
- builtin/core/roles/kubernetes/init-kubernetes/tasks/init_kubernetes.yaml
- builtin/core/roles/kubernetes/init-kubernetes/tasks/main.yaml
- builtin/core/roles/kubernetes/join-kubernetes/tasks/join_kubernetes.yaml
- builtin/core/roles/kubernetes/join-kubernetes/tasks/main.yaml
/kind feature
Configurable local DNS file in `localDNS` variable
1. set in config.yaml
```shell
cat >> config.yaml << EOF
localDNS:
- /etc/hosts
- xxxx
EOF
kk create cluster -c config.yaml
```
2. set in parameter
```shell
kk create cluster --set localDNS=["/etc/hosts/","xxx"]
```
Fixes #
https://github.com/kubesphere/kubekey/issues/2540
```
```
```release-note
Configurable local DNS file
```
```docs
```
> feat: Configurable local DNS file

- pkg/proxy/internal/file_storage.go
Fixes #
Unexpected error during initial resource listing
```
```
```release-note
Unexpected error during initial resource listing
```
```docs
```
> fix: Unexpected error during initial resource listing

- pkg/executor/block_executor.go
- pkg/executor/playbook_executor.go
- pkg/executor/task_executor.go
- pkg/modules/setup.go
- pkg/modules/setup_test.go
/kind feature
add a `setup` module. run gather_fact by `setup` module
Fixes #
```
```
```release-note
run gather_facts by module
```
```docs
```
> feat: run gather_facts by module

- cmd/kk/pkg/container/templates/containerd_service.go
- pkg/service/containermanager/templates/containerd.service
Add `LimitMEMLOCK=infinity` configuration to the containerd systemd service file to remove memory locking limitations and support advanced container workloads.
The current containerd systemd service configuration has a default memory lock limit that can prevent certain workloads from running properly. This limitation affects:
- **GPU workloads**: NVIDIA/AMD GPU containers require locked memory for device mappings
- **eBPF programs**: Network policies, monitoring, and security features need to lock eBPF maps in memory
- **High-performance computing**: Applications requiring large amounts of locked memory for performance
- **Real-time applications**: Containers that need guaranteed memory residency to avoid swap latency
```diff
[Service]
ExecStartPre=-/sbin/modprobe overlay …
```
> feat: Add LimitMEMLOCK=infinity to containerd systemd service

- pkg/executor/task_executor.go
- pkg/modules/assert.go
- pkg/modules/assert_test.go
/kind cleanup
Eliminate duplicate parse logic.
Fixes #
```
```
```release-note
none
```
```docs
```
> fix: Eliminate duplicate parse logic.

- api/core/v1/playbook_types.go
- cmd/kk/app/options/builtin/add.go
- cmd/kk/app/options/builtin/artifact.go
- cmd/kk/app/options/builtin/certs.go
- cmd/kk/app/options/builtin/create.go
- cmd/kk/app/options/builtin/delete.go
- cmd/kk/app/options/builtin/init.go
- cmd/kk/app/options/builtin/precheck.go
- cmd/kk/app/options/option.go
- cmd/kk/app/options/run.go
- pkg/executor/playbook_executor.go
/kind cleanup
Fixes #
debug field is unnecessary.
```
```
```release-note
delete debug field in playbook
```
```docs
```
> fix: delete debug field

- api/project/v1/playbook_test.go
- api/project/v1/role.go
- pkg/const/workdir.go
- pkg/executor/block_executor.go
- pkg/executor/playbook_executor.go
- pkg/executor/role_executor.go
- pkg/project/path.go
- pkg/project/project.go
- pkg/project/project_test.go
- pkg/project/testdata/playbooks/playbook5.yaml
- pkg/project/testdata/roles/role3/meta/main.yaml
/kind feature
Adding role dependencies
You can define dependencies in `roles/{role}/meta/main.yaml`:
```text
|-- roles/
|  |-- meta/
|  |  |-- main.yaml
```
Example:
```yaml
dependencies:
- role: other_role
```
Fixes #
```
```
```release-note
add role dependency
```
```docs
```
> feat: add role dependency

- pkg/web/api/result.go
- pkg/web/resources.go
/feature
add sshPort of listIP result
Fixes #
```
```
```release-note
none
```
```docs
```
> fix: add sshPort of listIP result

- .github/workflows/gen-repository-iso.yaml
- README.md
- README_zh-CN.md
- hack/gen-repository-iso/dockerfile.debian12
- hack/gen-repository-iso/packages.yaml
What type of PR is this?
Add one of the following kinds:
/kind feature
What this PR does / why we need it:
Support [Debian Stable 12 Bookworm](https://wiki.debian.org/DebianReleases) which has already been released for 2 years.
Comparing to debian 11, the glusterfs version updated to v10 to support debian 12, yq version updated to 4.46.1.
> feat: Add support for building Debian 12 Bookworm repository iso

- builtin/core/roles/image-registry/docker-compose/tasks/main.yaml
- builtin/core/roles/image-registry/harbor/tasks/main.yaml
- builtin/core/roles/image-registry/harbor/templates/harbor.service
- builtin/core/roles/image-registry/harbor/templates/harbor.yml
- builtin/core/roles/image-registry/tasks/main.yaml
/kind bug
when init registry ,some harbor version config will shown as <no_value>
fix harbor version config 
Fixes #
```
None
```
```release-note
fix harbor verson config path
```
```docs
```
> bugfix: fix harbor verson config path

- builtin/core/playbooks/artifact_images.yaml
- builtin/core/roles/download/tasks/images.yaml
- builtin/core/roles/image-registry/tasks/main.yaml
/kind feature
Add a switch to control whether to download the image.
In some cases, when the image is already confirmed to be complete, there’s no need to verify its integrity with the remote registry.
Fixes #
https://github.com/kubesphere/kubekey/issues/2706
```
```
```release-note
Add a switch to control whether to download the image.
```
```docs
```
> fix: add condition to check download_image in playbooks and tasks
