kubesphere/kubekey

README.md
=> add motivation

pkg/cluster/etcd/etcd.go
=> privilege escalation

pkg/cluster/kubernetes/tmpl/kubeadm.go, pkg/config/default.go
create allinone node to add authorized_keys
=> add authorized_keys

pkg/container-engine/docker/docker.go
=> display docker install info

pkg/cluster/kubernetes/master.go, pkg/util/executor/executor.go
=> support custom kubeadm config

cmd/create/config.go, cmd/delete.go, pkg/config/config.go, pkg/delete/delete.go
=> refine commands

OWNERS
It triggers a pr merging to reply /lgtm and /approve at same time . But only /lgtm not works.
=> test lgtm label bug

README.md, go.sum, pkg/apis/kubekey/v1alpha1/default.go, pkg/apis/kubekey/v1alpha1/plugins_types.go, pkg/config/config.go, pkg/config/default.go, pkg/images/default.go, pkg/images/images.go, pkg/kubesphere/tmpl.go, pkg/plugins/storage/ceph-rbd/ceph-rbd.go, pkg/plugins/storage/local-volume/openebs.go, pkg/plugins/storage/nfs-client/nfs-client.go, pkg/plugins/storage/storage.go
=> add RBD storage support

docs/storage-client.md, pkg/plugins/storage/glusterfs/glusterfs.go, pkg/plugins/storage/storage.go
=> add glusterfs storage support

cmd/create/cluster.go, pkg/config/default.go, pkg/images/default.go, pkg/util/util.go
1. Check  config.yaml in current dir.
2. When k8s is v1.18.x, pull image `xxx/pause:v3.2`.
=> add version compare

pkg/util/manager/task-run.go, pkg/util/runner/runner.go
Fix: task timeout, but not exit.
=> task exits after timeout

pkg/apis/kubekey/v1alpha1/default.go, pkg/util/util.go
=> Recognize home dir

README.md, docs/config-example.md, go.mod, go.sum, pkg/cluster/preinstall/initOS.go, pkg/cluster/preinstall/precheck.go, pkg/cluster/preinstall/preinstall.go, pkg/install/install.go, pkg/util/runner/runner.go
=> confirmation before installation

go.mod, pkg/kubesphere/manifests.go
imagePullPolicy IfNotPresent to Always
=> IfNotPresent to Always

docs/config-example.md
Signed-off-by: FeynmanZhou <pengfeizhou@yunify.com>
=> update config-example.md for ssh port hints

cmd/cluster.go, cmd/delete.go, cmd/scale.go, pkg/cluster/preinstall/init_os.go, pkg/cluster/preinstall/precheck.go, pkg/delete/delete.go, pkg/install/install.go, pkg/scale/scale.go, pkg/util/executor/executor.go, pkg/util/manager/manager.go
https://github.com/kubesphere/kubekey/issues/110
=> provide -y

pkg/util/ssh/dialer.go
=> Increase timeout

README.md, docs/README_zh-CN.md
=> Add file docs/README_zh-CN.md

.github/workflows/ci.yml, README.md, README_zh-CN.md
Signed-off-by: shaowenchen <mail@chenshaowen.com>
=> add auto build and upload

cmd/upgrade.go, pkg/cluster/kubernetes/nodes.go, pkg/cluster/kubernetes/tmpl/kubeadm.go, pkg/cluster/kubernetes/upgrade.go, pkg/scale/scale.go, pkg/upgrade/upgrade.go
=> add upgrade cluster

README.md, README_zh-CN.md, docs/config-example.md
Signed-off-by: FeynmanZhou <pengfeizhou@yunify.com>
=> update KubeKey docs

pkg/kubesphere/manifests.go
=> add jwtSecret

pkg/kubesphere/manifests.go
=> add storage clusterrole

README.md, README_zh-CN.md
/cc @pixiake Please also update kubekey to supported the latest versions.
=> Update supported K8s versions

pkg/plugins/storage/storage.go
=> fix deploy rbd provisioner

docs/config-example.md, pkg/apis/kubekey/v1alpha1/default.go, pkg/apis/kubekey/v1alpha1/kubernetes_types.go, pkg/cluster/kubernetes/tmpl/kubeadm.go
=> supprot custom kube-proxy mode

README.md, docs/config-example.md
Signed-off-by: Ray Zhou <ray@yunify.com>
=> Change the default K8s version from 1.17.8 to 1.17.9

docs/config-example.md
Signed-off-by: huanggze <loganhuang@yunify.com>
Ref. https://github.com/kubesphere/kubekey/issues/173
=> update config example

pkg/delete/delete.go
=> clean /etc/kubernetes

Makefile, cmd/cluster.go, cmd/root.go, cmd/scale.go, cmd/upgrade.go, pkg/cluster/kubernetes/master.go, pkg/cluster/preinstall/prepull_images.go, pkg/delete/delete.go, pkg/install/install.go, pkg/scale/scale.go, pkg/upgrade/upgrade.go, pkg/util/executor/executor.go, pkg/util/manager/manager.go
=> add skip pre pull images

pkg/apis/kubekey/v1alpha1/default.go, pkg/plugins/network/flannel/tmpl.go
=> update flannel to v0.12.0

pkg/apis/kubekey/v1alpha1/default.go, pkg/cluster/preinstall/prepull_images.go, pkg/plugins/network/calico/tmpl-v1.16+.go, pkg/plugins/network/calico/tmpl-v1.16-.go, pkg/plugins/network/network.go
=> update calico to v3.15.1

docs/config-example.md, pkg/kubesphere/manifests.go
=> add telemetry

pkg/kubesphere/manifests.go
=> fix character

pkg/kubesphere/kubesphere.go
=> update result path

cmd/deploy.go, cmd/kubesphere.go, cmd/root.go, go.mod, go.sum, pkg/deploy/client.go, pkg/deploy/kubesphere.go
=> deploy KubeSphere on the existing K8s

pkg/cluster/etcd/etcd.go, pkg/cluster/kubernetes/master.go, pkg/cluster/kubernetes/nodes.go, pkg/cluster/kubernetes/upgrade.go, pkg/cluster/preinstall/init_os.go, pkg/cluster/preinstall/precheck.go, pkg/cluster/preinstall/prepull_images.go, pkg/container-engine/docker/docker.go, pkg/delete/delete.go, pkg/kubesphere/kubesphere.go, pkg/plugins/network/network.go, pkg/plugins/storage/images.go, pkg/plugins/storage/storage.go, pkg/upgrade/policy.go, pkg/util/manager/task_run.go
=> remove useless parameters

README.md, README_zh-CN.md
Signed-off-by: FeynmanZhou <pengfeizhou@yunify.com>
=> add SUSE Linux to the supported OS list

cmd/delete.go, cmd/delete_cluster.go
=> update delete cluster

pkg/cluster/kubernetes/master.go, pkg/cluster/kubernetes/nodes.go, pkg/delete/delete.go, pkg/plugins/dns/dns.go, pkg/plugins/dns/nodelocaldns.go, pkg/plugins/network/network.go, pkg/upgrade/kubernetes.go, pkg/upgrade/kubesphere.go, pkg/upgrade/upgrade.go, pkg/util/runner/runner.go
=> refine deploy kubernetes

go.mod, go.sum, pkg/deploy/create_objects.go, pkg/deploy/kubesphere.go, pkg/upgrade/kubesphere.go, pkg/util/client.go, pkg/util/manager/task_run.go
=> server side apply

README.md, README_zh-CN.md, docs/turn-off-SELinux.md, docs/turn-off-SELinux_zh-CN.md
Signed-off-by: honglei <shenhongleigood@163.com>
fix this issue [Permission denied](https://github.com/kubesphere/kubekey/issues/206)
=> Add a little note（SELinux） to the readme

README.md, README_zh-CN.md, cmd/delete_node.go, pkg/delete/delete.go
https://github.com/kubesphere/kubekey/issues/193
=> add node delete

pkg/delete/delete.go
=> update delete node

pkg/cluster/kubernetes/master.go, pkg/cluster/kubernetes/nodes.go, pkg/cluster/preinstall/init_os.go, pkg/install/install.go, pkg/scale/scale.go, pkg/upgrade/kubernetes.go, pkg/upgrade/precheck.go
=> refine upgrade

pkg/cluster/preinstall/tmpl/init_os.go
Signed-off-by: Duan Jiong <djduanjiong@gmail.com>
=> Make sure the iptables utility doesn't use the nftables backend.

pkg/container-engine/docker/docker.go, scripts/docker-install.sh
=> update docker judgement conditions

pkg/upgrade/precheck.go
=> get kubeconfig automatically

docs/addons.md
=> add docs about csi-qingcloud

pkg/upgrade/kubernetes.go
=> refresh kubelet config

pkg/addons/install.go, pkg/addons/manifests/install.go, pkg/cluster/kubernetes/master.go, pkg/deploy/kubesphere.go, pkg/kubesphere/kubesphere.go, pkg/plugins/dns/dns.go, pkg/upgrade/kubernetes.go, pkg/upgrade/kubesphere.go
=> refine install step

pkg/addons/install.go
=> use cluster kubeconfig

README.md, README_zh-CN.md, docs/kubernetes-versions.md
=> support kubernetes versions

docs/addons.md
Signed-off-by: zhangmin <arminzhang@yunify.com>
=>  rbd addon examples

docs/config-example.md
Signed-off-by: Benjamin <benjamin@yunify.com>
=> Adjust legacy notification description

pkg/upgrade/precheck.go
=> update get version

pkg/upgrade/precheck.go
=> fix get k8s version

README.md, README_zh-CN.md
Signed-off-by: Sherlock113 sherlockxu@yunify.com
Fix https://github.com/kubesphere/kubekey/issues/282
=> Dependency requirement update

pkg/cluster/preinstall/tmpl/init_os.go
to avoid too many open files error
Signed-off-by: zackzhangkai <zackzhang@yunify.com>
=> add ulimit

scripts/docker-install.sh
https://github.com/kubesphere/kubekey/issues/284
=> update docker install

pkg/cluster/preinstall/tmpl/init_os.go
Signed-off-by: zackzhangkai <zackzhang@yunify.com>
=> modify bash

pkg/add/add.go, pkg/cluster/etcd/etcd.go, pkg/cluster/etcd/tmpl/etcdbackup.go, pkg/install/install.go
=> Add Backup etcd data regularly

pkg/addons/charts/install.go, pkg/apis/kubekey/v1alpha1/addons_types.go
=> support specify chart version

pkg/cluster/etcd/etcd.go, pkg/cluster/kubernetes/master.go, pkg/cluster/preinstall/tmpl/init_os.go, pkg/delete/delete.go
=> add zombie processing and add sudo

cmd/root.go
Signed-off-by: zackzhangkai <zackzhang@yunify.com>
=> fix exec command

pkg/kubesphere/kubesphere.go
fix #302 
Signed-off-by: “Fuchange fu_changjie@qq.com
=> fix sed-erro about PrivateRegistry

README.md, README_zh-CN.md, pkg/install/install.go
fix #300 
add a Note on README
add a error if hostname have any capital letter
I'm not sure it's the best to add it here. Comments are welcome
Signed-off-by: fu_changjie <fu_changjie@qq.com>
=> uppercaseNodeName

cmd/init.go, cmd/init_os.go, cmd/root.go, go.mod, go.sum, pkg/add/add.go, pkg/bootstrap/init.go, pkg/bootstrap/os.go, pkg/cluster/etcd/etcd.go, pkg/cluster/kubernetes/master.go, pkg/delete/delete.go, pkg/install/install.go, pkg/kubesphere/kubesphere.go, pkg/upgrade/upgrade.go, pkg/util/executor/executor.go, pkg/util/manager/manager.go, scripts/docker-install.sh, version/version.go
=> add init operating system

pkg/cluster/etcd/etcd.go, pkg/cluster/kubernetes/master.go, pkg/cluster/kubernetes/nodes.go, pkg/cluster/preinstall/precheck.go
=> fix nodename judgment

pkg/install/install.go
=> add the detection address at LB

pkg/install/install.go
=> update the detection policy

api/v1alpha1/cluster_types.go, api/v1alpha1/default.go, pkg/install/install.go
=> update lb precheck

api/v1alpha1/cluster_types.go
=> Update eted odd check and Whether a node exists

scripts/docker-install.sh
=> update docker version to 19.03.13

api/v1alpha1/default.go, api/v1alpha1/kubernetes_types.go, pkg/cluster/etcd/etcd.go, pkg/cluster/etcd/tmpl/etcdbackup.go
=> update define etcd script dir

api/v1alpha1/cluster_types.go, config/crd/bases/kubekey.kubesphere.io_clusters.yaml, config/rbac/role.yaml, config/samples/kubekey_v1alpha1_cluster.yaml
=> update crd scop

api/v1alpha1/default.go, api/v1alpha1/network_types.go, pkg/plugins/network/flannel/tmpl.go
=> Add the exposure of the flannel parameter

api/v1alpha1/default.go, pkg/cluster/preinstall/prepull_images.go, pkg/plugins/network/cilium/tmpl.go, pkg/plugins/network/network.go
=> Add the cilium supported

pkg/delete/delete.go
https://github.com/kubesphere/kubekey/issues/317
=> Update error display

api/v1alpha1/cluster_types.go
=> Update the judgment of nodes in a group

Dockerfile, api/v1alpha1/cluster_types.go, config/manager/kustomization.yaml, config/manager/manager.yaml, config/rbac/role.yaml, controllers/cluster_controller.go, controllers/install.go, manifests/deploy.yaml, pkg/add/add.go, pkg/addons/install.go, pkg/bootstrap/init.go, pkg/cluster/kubernetes/master.go, pkg/config/parse.go, pkg/delete/delete.go, pkg/install/install.go, pkg/upgrade/upgrade.go, pkg/util/executor/executor.go, pkg/util/manager/manager.go, pkg/util/ssh/dialer.go
=> addons charts

pkg/add/add.go, pkg/cluster/preinstall/init_os.go, pkg/install/install.go, pkg/upgrade/upgrade.go
Signed-off-by: stoneshi-yunify <stoneshi@yunify.com>
fix typos in messages
=> fix typos in messages

pkg/cluster/kubernetes/master.go, pkg/cluster/kubernetes/tmpl/kubeadm.go, pkg/util/executor/executor.go
=> update K8s with the kube-bench tool

Dockerfile, api/v1alpha1/default.go, pkg/install/install.go, pkg/util/ssh/ssh.go
=> supported privateKey

api/v1alpha1/default.go, pkg/plugins/network/calico/tmpl-v1.16+.go
=> update calico to v3.16.3

api/v1alpha1/cluster_types.go, api/v1alpha1/default.go, pkg/cluster/kubernetes/master.go, pkg/util/executor/executor.go
=> return validate result

pkg/cluster/etcd/etcd.go
=> Upgrade configuration when upgrading etcd

api/v1alpha1/cluster_types.go, api/v1alpha1/default.go
https://github.com/kubesphere/kubekey/issues/343
=> fix lb check

config/default/manager_auth_proxy_patch.yaml, manifests/deploy.yaml
=> update kube-rbac-proxy image

.gitignore, pkg/bootstrap/os.go, pkg/kubesphere/kubesphere.go
=> Remove redundant newline with fmt.Println

pkg/cluster/preinstall/preinstall.go, pkg/install/install.go
=> google object storage is supported

scripts/downloadKubekey.sh
=> add download script

README.md, README_zh-CN.md, pkg/cluster/preinstall/preinstall.go, scripts/downloadKubekey.sh
=> update download script

cmd/cert.go, cmd/list_cert.go, pkg/cert/cert.go, scripts/docker-install.sh
Signed-off-by: Forest-L lilin@yunify.com
=> Added cluster certificate expiration date to list

pkg/cluster/preinstall/preinstall.go
Not everyone willing to go through the all documents before using kk. So we just give to a friendly tips.
=> Giving a friendly tips with the network isseus

cmd/cluster.go
It will be very convenience if we give a default value.
=> Align the default k8s version with the doc said

cmd/completion.go
=> Add completion support for kk

cmd/cert.go, cmd/list_cert.go, cmd/renew_cert.go, go.mod, pkg/cert/cert.go
=> add cluster certs check and cluster certs renew

apis/kubekey/v1alpha1/default.go, pkg/cluster/kubernetes/master.go, pkg/cluster/kubernetes/tmpl/kubeadm.go, pkg/cluster/kubernetes/tmpl/kubelet.go, pkg/cluster/preinstall/prepull_images.go
=> multi container runtime

pkg/cluster/kubernetes/tmpl/kubeadm.go
=> update etcd certs file

pkg/cluster/etcd/tmpl/certs.go, pkg/cluster/etcd/tmpl/etcd.go, pkg/cluster/etcd/tmpl/etcdbackup.go, pkg/cluster/kubernetes/tmpl/kubeadm.go, pkg/cluster/kubernetes/tmpl/kubelet.go, pkg/cluster/preinstall/prepull_images.go, pkg/config/from_cluster.go, pkg/config/generate.go, pkg/config/parse.go, pkg/deploy/kubesphere.go, pkg/images/images.go, pkg/kubesphere/kubesphere.go, pkg/kubesphere/manifests.go, pkg/plugins/storage/local-volume/openebs.go
=> support aliyun images repo

pkg/install/install.go, pkg/plugins/network/network.go, pkg/util/manager/manager.go, pkg/util/manager/run_task.go
=> support none network plugin installation

pkg/kubesphere/kubesphere.go, pkg/kubesphere/manifests.go
=> Fix the nightly installation errors

pkg/cluster/kubernetes/tmpl/kubeadm.go
=> fix kubeadm template

README.md, README_zh-CN.md, docs/check-renew-certificate.md
=> Add renew certificate readme

apis/kubekey/v1alpha1/cluster_types.go, pkg/cluster/kubernetes/master.go, pkg/cluster/kubernetes/nodes.go
Supports advance labeling of nodes to facilitate workload scheduling based on node labels.
=> support for adding node labels

.all-contributorsrc, .gitignore, CONTRIBUTORS.md, README.md, README_zh-CN.md
Comment on Issue or Pull Request, asking `@all-contributors` to add a contributor:
```
@all-contributors please add @<username> for <contributions>
```
=> show all contributors

pkg/cluster/kubernetes/tmpl/kubeadm.go
=> update RotateKubeletServerCertificate and RotateKubeletClientCertificate

docs/config-example.md
=> update config-example format

pkg/cluster/preinstall/tmpl/init_os.go
Fix network problem caused by kernel argument.
See https://imroc.io/posts/kubernetes/troubleshooting-with-kubernetes-network  & https://kubesphere.com.cn/forum/d/3383-ksaws-eks-member/17
=> add init script

go.mod, go.sum
Reverts kubesphere/kubekey#436
=> Revert "Bump github.com/go-logr/logr from 0.1.0 to 0.4.0"

.github/settings.yml, .goreleaser.yml
Signed-off-by: Sherlock113 <sherlockxu@yunify.com>
=> Update KubeKey desc

cmd/add_nodes.go, cmd/upgrade.go, go.mod, go.sum, pkg/add/add.go, pkg/cluster/preinstall/preinstall.go, pkg/upgrade/upgrade.go
=> Fix download-cmd parameter about adding nodes and updating cluster

.github/OWNERS, .github/release-drafter.yml, .github/workflows/release-drafter.yml
=> Add GitHub action for release drafter

go.mod, pkg/add/add.go
=> Fix: compile the abnormal

cmd/cluster.go, cmd/root.go, pkg/cluster/delete/delete.go, pkg/cluster/install/install.go, pkg/cluster/install/tasks.go, pkg/cluster/upgrade/precheck.go, pkg/config/parse.go, pkg/k3s/config/service.go, pkg/k3s/master.go, pkg/k3s/nodes.go, pkg/kubesphere/kubesphere.go, pkg/kubesphere/manifests.go, pkg/util/executor/executor.go, pkg/util/manager/manager.go
=> support for choosing whether to deploy local storage

README_zh-CN.md
Signed-off-by: lxm <lxm.xupt@gmail.com>
=> fix readme zh_CN

apis/kubekey/v1alpha1/default.go, pkg/cluster/upgrade/kubesphere.go, pkg/kubernetes/preinstall/precheck.go
=> update default kubernetes version to v1.19.8

pkg/cluster/upgrade/kubesphere.go, pkg/cluster/upgrade/precheck.go, pkg/kubesphere/kubesphere.go
=> supported upgrade ks

.github/workflows/release-drafter.yml
I've tested this. Please see also https://github.com/LinuxSuRen/kubekey/runs/2293130478
=> Fix the release-drafter errors

pkg/cluster/upgrade/kubernetes.go, pkg/kubernetes/master.go, pkg/kubernetes/tmpl/kubeadm.go
=> Use master's IP as advertise-address

scripts/docker-install.sh
=> update install-docker script

pkg/kubesphere/manifests.go
=> sync ks-installer cluster configuration

pkg/kubesphere/manifests.go
Signed-off-by: misteruly <lanpeng@yunify.com>
=> add configuration parameters

pkg/kubernetes/config/v1beta2/kubeadm.go
Signed-off-by: misteruly <lanpeng@yunify.com>
=> Set the bind-adress default to 0.0.0.0

pkg/k3s/config/service.go, pkg/kubesphere/kubesphere.go
=> Add default parameters for k3s

.goreleaser.yml, pkg/plugins/network/network.go
=> don't retain the old manifeats of network plugin

pkg/cluster/delete/delete.go, pkg/etcd/etcd.go
=> retain etcd and kubectl that already exists

pkg/bootstrap/configuration/init_script.go, pkg/bootstrap/dependencies/os.go, pkg/container-engine/docker/docker.go, scripts/docker-install.sh
=> update initialization configuration

pkg/kubesphere/manifests.go
=> Support setting zone for KubeSphere

pkg/cluster/upgrade/precheck.go, pkg/kubernetes/preinstall/precheck.go, pkg/util/util.go
=> add docker version checking

README.md, README_zh-CN.md, cmd/config.go, cmd/upgrade.go, config/samples/kubekey_v1alpha1_cluster.yaml, docs/config-example.md
Signed-off-by: johnniang <johnniang@fastmail.com>
=> Update k8s and ks version to latest

docs/addons.md
=> update addons doc

pkg/util/ssh/ssh.go
Signed-off-by: haozi007 <knowledgehao@163.com>
=> support close for connection

docs/config-example.md
=> update example config

pkg/plugins/storage/local-volume/openebs.go
Signed-off-by: misteruly <lanpeng@yunify.com>
=> Table becomes space

pkg/etcd/etcd.go
=> Fix typo: helthCheck -> healthCheck

pkg/etcd/tmpl/etcdbackup.go
as title～
Ref https://github.com/kubesphere/kubekey/issues/546
=> Set Etcdendpoint to local node instead of all etcd members in etcd-backup.sh

controllers/kubekey/cluster_controller.go
=> match image's registry

pkg/util/manager/run_task.go
Modified the timer in run_task.go
Resolve the problem of inconsistent task timeout control. I move the timer into the goruntine, and every goruntine has a timer. Because of that, the time of each timer will be vary close.
Which issue(s) this PR fixes:
Fix #552
=> Fix: modified the timer in run_task.go

docs/turn-off-SELinux_zh-CN.md
Modified the chinese quotation marks to english marks that in the command.
=> fix: quotation marks change to the english

scripts/downloadKubekey.sh
Use the `command -v tar` to check if the `tar` command is existed. And then, echo the diffrent  prompt.
=> fix: modify the shell scripts

pkg/cluster/upgrade/kubernetes.go
There is a bug when upgrading the cluster it will make kubernetes endpoint only have one master node's address.
=> fix: upgrade cluster make kubernetes endpoint change

apis/kubekey/v1alpha1/default.go
=> fix: prevent setting lb and internal load balancer at the same time

docs/ha-mode.md
Add a basic document on how to use the internal load balancer.
=> docs: add ha-mode.md

experiment/kubernetes/control-plane/tasks/tasks.go, experiment/utils/action/command.go, experiment/utils/action/copy.go, experiment/utils/action/interface.go, experiment/utils/action/template.go, experiment/utils/action/webserver.go, experiment/utils/ending/ending.go, experiment/utils/ending/status_enum.go, experiment/utils/ending/task_result.go, experiment/utils/pipeline/task.go, experiment/utils/vars/vars.go
=> Experiment: solve task and action recycle dependency

experiment/utils/config/manager.go, experiment/utils/logger/logger_test.go, experiment/utils/pipeline/const.go, experiment/utils/pipeline/task.go
=> Experiment: fix some logger bug

experiment/core/pipeline/const.go, experiment/core/pipeline/module.go, experiment/core/pipeline/pipeline.go, experiment/pipeline/kubernetes/create.go, experiment/pipeline/kubernetes/module/control_plane/module.go
=> Experiment: make pipeline module Lazy Initialization

experiment/core/action/base.go, experiment/core/config/nodeConfig.go, experiment/core/connector/connection.go, experiment/core/connector/ssh/ssh.go, experiment/core/runner/runner.go, experiment/core/util/file.go, experiment/core/util/util.go, experiment/pipeline/kubernetes/module/control_plane/module.go
=> Experiment: add scp and fetch function

experiment/core/action/template.go, experiment/core/common/common.go, experiment/core/connector/connection.go, experiment/core/connector/ssh/ssh.go, experiment/core/logger/logger.go, experiment/core/pipeline/module.go, experiment/core/pipeline/task.go, experiment/core/prepare/base.go, experiment/core/prepare/prepare.go, experiment/core/runner/runner.go, experiment/core/util/file.go, experiment/pipeline/kubernetes/module/control_plane/module.go, experiment/pipeline/loadbalancer/module/module.go, experiment/pipeline/loadbalancer/module/templates/haproxy.cfg, experiment/pipeline/loadbalancer/module/templates/haproxy.yaml
=> Experiment: Add a loadblancer demo pipeline

.github/ISSUE_TEMPLATE/bug_report.yaml
Fix: same id exists in issues template body
=> fix: same id exists in body

experiment/core/prepare/base.go, experiment/core/prepare/prepare.go, experiment/pipeline/loadbalancer/module/module.go, experiment/pipeline/loadbalancer/module/tasks.go
=> Experiment: complete loadbalancer module

pkg/container-engine/docker/docker.go
=> fix: solve the bug that kk lacks a task to install docker

pkg/core/action/template.go, pkg/core/common/common.go, pkg/core/connector/interface.go, pkg/core/connector/runtime.go, pkg/core/pipeline/pipeline.go, pkg/pipelines/common/common.go, pkg/pipelines/common/kube_prepare.go, pkg/pipelines/common/kube_runtime.go, pkg/pipelines/create_cluster.go, pkg/pipelines/etcd/module.go, pkg/pipelines/initialization/tasks.go, pkg/pipelines/kubernetes/kubernetes_status.go, pkg/pipelines/kubernetes/module.go, pkg/pipelines/kubernetes/prepares.go, pkg/pipelines/kubernetes/tasks.go, pkg/pipelines/plugins/network/modules.go, pkg/pipelines/plugins/network/prepares.go, pkg/pipelines/plugins/network/tasks.go, pkg/pipelines/plugins/network/templates/calico_v1.16+.go, pkg/pipelines/plugins/network/templates/calico_v1.16-.go
Create kubernetes pipeline basically completed.
=> Experiment: add NetworkPluginModule(calico) 

pkg/core/ending/task_result.go, pkg/core/modules/task.go, pkg/pipelines/plugins/network/modules.go, pkg/pipelines/plugins/network/tasks.go, pkg/pipelines/plugins/network/templates/cilium.go, pkg/pipelines/plugins/network/templates/flannel.go
* CNI supports flannel and Cilium 
* make task result display each to each
=> Experiment: support more network plugin and modify task result

cmd/cluster.go, pkg/core/pipeline/pipeline.go
=> Experiment: move logo to pipeline init function

apis/kubekey/v1alpha1/default.go, pkg/core/util/util.go, pkg/pipelines/common/common.go, pkg/pipelines/images/tasks.go, pkg/pipelines/kubernetes/tasks.go
=> Experiment: sync master branch latest ContainerRuntimeEndpoint config

cmd/add_nodes.go, pkg/pipelines/add_nodes.go
=> Experiment: add AddNodesPipeline

cmd/delete_node.go, pkg/core/connector/interface.go, pkg/core/connector/runtime.go, pkg/pipelines/bootstrap/config/module.go, pkg/pipelines/bootstrap/confirm/module.go, pkg/pipelines/common/kube_runtime.go, pkg/pipelines/delete_node.go, pkg/pipelines/kubernetes/module.go, pkg/pipelines/kubernetes/tasks.go
=> Experiment: add DeleteNodePipeline

cmd/cluster.go, cmd/upgrade.go, pkg/cluster/upgrade/kubernetes.go, pkg/cluster/upgrade/precheck.go, pkg/cluster/upgrade/upgrade.go, pkg/config/generate.go, pkg/config/parse.go, pkg/kubesphere/kubesphere.go, pkg/kubesphere/manifests.go, pkg/kubesphere/templates.go
* Support to deploy of the alpha version of ks-installer
* Support upgrade k8s version to v1.22.1 and ks to v3.2.0. kk will upgrade k8s version to v1.21.5 first and then upgrade ks, finally upgrade k8s to v1.22.1
=> Support KubeSphere v3.2.0

cmd/list_cert.go, cmd/renew_cert.go, pkg/cluster/install/install_test.go, pkg/pipelines/certs/module.go, pkg/pipelines/certs/tasks.go, pkg/pipelines/check_certs.go, pkg/pipelines/common/common.go, pkg/pipelines/common/loader.go, pkg/pipelines/renew_certs.go
* add list_certs pipeline and renew_certs pipeline
=> Experiment: add pipelines that about certificates

pkg/pipelines/certs/tasks.go
=> Experiment: renew certs support k8s version > v1.20.0

pkg/cluster/certs/cert.go
The `kubeadm alpha certs` subcommand was removed after kubeadm v1.20.0.
So, this pr make kk use the following command to renew certs when kubeadm version > v1.20.0 :
```
kubeadm certs renew
```
=> fix: renew certs support k8s version > v1.20.0

.github/workflows/ci.yml, .github/workflows/release.yaml
=> github ci upgrade go 1.16

.github/workflows/ci.yml, .github/workflows/release.yaml, Dockerfile, Makefile, build.sh
Change the dockerfile image and build.sh docker image to golang:1.16.
Github actions checkout add config just like kubesphere:
```
with:
fetch-depth: 0
```
=> dockerfile build from golang:1.16

pkg/kubesphere/manifests.go
=> upgrade ks-installer manifest

.github/workflows/ci.yml, .github/workflows/release.yaml
=> modify git fetch depth

.github/workflows/ci.yml, cmd/cluster.go, pkg/bootstrap/precheck/module.go, pkg/certs/module.go, pkg/certs/prepares.go, pkg/certs/tasks.go, pkg/certs/templates/certs_renew_script.go, pkg/certs/templates/certs_renew_service.go, pkg/common/loader.go, pkg/kubesphere/tasks.go, pkg/pipelines/add_nodes.go, pkg/pipelines/create_cluster.go, pkg/pipelines/delete_cluster.go, pkg/pipelines/upgrade_cluster.go, pkg/version/kubesphere/version_enum.go
* Add AutoRenewCertsModule
* Sync master branch new feature
=> dev-v2.0.0: add AutoRenewCertsModule

pkg/bootstrap/os/tasks.go, pkg/certs/tasks.go, pkg/container/containerd.go, pkg/container/docker.go, pkg/core/connector/interface.go, pkg/core/connector/runner.go, pkg/core/connector/ssh.go, pkg/etcd/tasks.go, pkg/k3s/tasks.go, pkg/kubernetes/tasks.go, pkg/utils/util.go
* Fix a permission denied error
=> dev-v2.0.0: fix permission denied error

controllers/kubekey/cluster_controller.go
* Clear condition array before run new job
=> dev-v2.0.0: reconcile func clear condition before run new job

docs/config-example.md, pkg/kubesphere/manifests.go, pkg/kubesphere/templates.go
Change externalElasticsearchUrl to externalElasticsearchHost at cc, and make the definition more clear.
please see kubesphere/kubesphere#3829.
Fixes kubesphere/kubesphere#3829.
=> Change externalElasticsearchUrl to externalElasticsearchHost at cc

docs/config-example.md, pkg/kubesphere/manifests.go, pkg/kubesphere/templates.go
Reverts kubesphere/kubekey#742
=> Revert "Change externalElasticsearchUrl to externalElasticsearchHost at cc"

controllers/kubekey/cluster_controller.go, controllers/kubekey/update_cluster.go, pkg/pipelines/add_nodes.go, pkg/pipelines/create_cluster.go
* Fix CR conditions not clear bug
=> dev-v2.0.0:  fix conditions bug

controllers/kubekey/cluster_controller.go
* Make operator delete error job
=> dev-v2.0.0:  operator delete err job

controllers/kubekey/cluster_controller.go
* Fix the operator controller spends to much time to creating a new job
=> dev-v2.0.0: fix operator spends to much time to creating new job

controllers/kubekey/cluster_controller.go, controllers/kubekey/update_cluster.go, pkg/k3s/tasks.go, pkg/kubernetes/kubernetes_status.go, pkg/kubernetes/tasks.go
* Save base64 encode kube config by ConfigMap
=> dev-v2.0.0: save base64 encode kubeconfig by configmap

pkg/etcd/tasks.go
* Fix etcd generate certs name error
=> dev-v2.0.0: fix etcd certs error

cmd/ctl/options/io_options.go, cmd/ctl/plugin/list.go, cmd/ctl/plugin/plugin.go, cmd/ctl/root.go, pkg/binaries/k3s.go
* Support plugin mode
* Fix k3s arm64 download bug
=> dev-v2.0.0: support plugin mode

README.md, README_zh-CN.md, docs/config-example.md
* Update readme for ha-mode doc
* Update config-example for ha-mode
=> dev-v2.0.0: update config example

pkg/kubernetes/module.go, pkg/plugins/network/modules.go, pkg/plugins/network/prepares.go, pkg/plugins/network/tasks.go, pkg/plugins/network/templates/kubectl_ko.go, pkg/plugins/network/templates/kubeovn_v1.16+.go, pkg/plugins/network/templates/kubeovn_v1.16-.go
* Sync master branch kube-ovn module
=> dev-v2.0.0: sync master branch kube-ovn module

pkg/certs/tasks.go, pkg/k3s/tasks.go, pkg/kubernetes/tasks.go
* fix a kube config file ownner bug
* fix a tar file that extracts to a wrong dir bug
=> dev-v2.0.0: fix a kube config file owner bug

pkg/container/containerd.go, pkg/container/docker.go, pkg/k3s/tasks.go, pkg/kubernetes/tasks.go
Fix binary file's name are different from their origin name
=> dev-v2.0.0: fix binary file's name are different from their origin name

cmd/cluster.go, pkg/cluster/upgrade/kubernetes.go, pkg/cluster/upgrade/precheck.go, pkg/config/generate.go, pkg/config/parse.go, pkg/kubesphere/kubesphere.go, pkg/kubesphere/manifests.go, pkg/kubesphere/templates.go
* Release-1.2 branch support kubesphere v3.2.1
=> [release-1.2] support kubesphere v3.2.1

pkg/kubesphere/modules.go
The same as this PR(#800), but it is for kubekey v2.0.0.
=> fix a bug that private registry can't be set when os env KKZONE is cn

apis/kubekey/v1alpha1/cluster_types.go, apis/kubekey/v1alpha1/kubernetes_types.go, apis/kubekey/v1alpha2/kubernetes_types.go, controllers/kubekey/cluster_controller.go, pkg/certs/prepares.go, pkg/container/prepares.go, pkg/core/connector/host.go, pkg/core/task/local_task.go, pkg/core/task/remote_task.go, pkg/etcd/prepares.go, pkg/etcd/tasks.go, pkg/k3s/prepares.go, pkg/plugins/network/modules.go, pkg/plugins/network/prepares.go, pkg/version/kubesphere/version_enum.go
=> Refactoring code.

pkg/kubesphere/kubesphere.go
Fix variable is an empty string
/cc @pixiake
=> [release-1.2] fix variable is an empty string

pkg/common/loader.go
Fix the flag `--with-kubernetes` is not working
=> fix flag --with-kubernetes is not working

pkg/cluster/upgrade/precheck.go
Fix upgrade command to check ks version error
=> [release-1.2] fix upgrade check ks version error

pkg/binaries/k3s.go, pkg/binaries/kubernetes.go
=> show the download progress.

cmd/ctl/upgrade/upgrade.go, pkg/pipelines/upgrade_cluster.go
Support [--yes] parameter when upgrade cluster
Fix #793
=> Support [--yes] parameter when upgrade cluster

pkg/core/connector/runtime.go, pkg/core/task/remote_task.go
=> fix handle error node bug

pkg/core/task/remote_task.go
FIx a nil pointer error happened when deleting a host.
=> fix handle error node nil pointer

pkg/plugins/network/modules.go
=>  fix(cilium&flannel): remove `OldK8sVersion` of `prepare` in `deployFlannel` and `deployCilium`

pkg/plugins/network/tasks.go, pkg/plugins/network/templates/kubeovn_v1.16+.go
* Fix kubeovn yaml lint bug
* Fix using wrong kubeovn template file
=> fix kubeovn yaml lint bug

controllers/kubekey/cluster_controller.go
Add pipeline status check：
1. Operation on the cluster is prohibited until the pipeline is completed.
=> Optimize the operator logic

apis/kubekey/v1alpha2/default.go, apis/kubekey/v1alpha2/network_types.go, pkg/config/templates/cluster.go, pkg/images/tasks.go, pkg/plugins/network/modules.go, pkg/plugins/network/tasks.go, pkg/plugins/network/templates/multus.go
=> multus support

pkg/kubernetes/tasks.go
=> Fix savekubeconfig： use InternalAddress that can't be connected when kk is not running in k8s node internal network.

pkg/cluster/upgrade/upgrade.go
Fix the pipeline task doesn't skip.
=> [release-1.2] fix pipeline doesn't skip

pkg/container/containerd.go
Fix containerd binary file not found errror.
=> fix containerd file not found error

docs/kubernetes-versions.md, pkg/version/kubernetes/version_enum.go
=> [release-2.0] Manual cherrypick #888 Support Kubernetes 1.23

cmd/ctl/create/cluster.go, pkg/common/kube_runtime.go, pkg/common/loader.go
Fix `--container-manager` flag doesn't work.
=> fix: --container-manager flag doesn't work

pkg/kubernetes/templates/v1beta2/kubeadm_config.go
=> fix: remove unneed logs in GetKubeletConfiguration

cmd/ctl/artifact/export.go, pkg/images/images.go, pkg/images/module.go, pkg/images/tasks.go, pkg/utils/containerruntime/runtime.go
Modify the ImagePushModule to use the containerd SDK. That will make the codes more graceful and easy to manage. But for now, kk only supports offline install on containerd environment or docker 18.09, 20.04.
=> modify ImagePushModule to use the containerd SDK

pkg/images/images.go, pkg/images/tasks.go
fix: push image failed by containerd client.
When we use the containerd client to import and push images, there are some problem like: `400 Bad Request`,`server gave http response to https client` .e.g. So, i modify the code to use the command line `ctr import` and `ctr push` .
=> fix: push image failed by containerd client

pkg/artifact/tasks.go, pkg/images/images.go
fix: images name and tar parse failed.
=> fix: images name and tar parse failed

pkg/bootstrap/precheck/tasks.go
fix: upgrade check ks version error.
=> fix: upgrade check ks version error

pkg/certs/tasks.go
When the user is `root`, and using the command `./kk certs renew -f config.yaml` will report a `are the same file` warning message.
So, I add a condition to skip when the user is `root`.
=> fix: report `are the same file` warning message when coping kubeconfig

apis/kubekey/v1alpha2/cluster_types.go, apis/kubekey/v1alpha2/manifest_types.go, cmd/ctl/add/add_nodes.go, cmd/ctl/init/init_registry.go, cmd/ctl/options/common_options.go, cmd/ctl/upgrade/upgrade.go, pkg/artifact/tasks.go, pkg/artifact/templates/manifest.go, pkg/binaries/k3s.go, pkg/binaries/kubernetes.go, pkg/binaries/registry.go, pkg/binaries/tasks.go, pkg/config/templates/cluster.go, pkg/files/file.go, pkg/images/images.go, pkg/pipelines/add_nodes.go, pkg/pipelines/init_registry.go, pkg/pipelines/upgrade_cluster.go
* Artifact supports to contain registry binaries
* AddNodes pipeline, Upgrade pipeline and InitRegistry pipelines support to use the artifact.
=> artifact supports to contain registry binaries

pkg/artifact/tasks.go, pkg/bootstrap/os/tasks.go, pkg/images/tasks.go
Modify MD5 file name and artifact directory tree.
=> modify MD5 file name and artifact directory tree.

pkg/binaries/k3s.go, pkg/binaries/kubernetes.go, pkg/binaries/registry.go, pkg/binaries/tasks.go, pkg/bootstrap/registry/tasks.go, pkg/container/containerd.go, pkg/container/docker.go, pkg/etcd/tasks.go, pkg/files/file.go, pkg/k3s/tasks.go, pkg/kubernetes/tasks.go, pkg/utils/containerruntime/runtime.go
* Modify the KubeKey `workdir` directory tree.
* modify k3s kube config.
=> modify workdir directory tree.

hack/gen-repository-iso/dockerfile.centos7, hack/gen-repository-iso/dockerfile.ubuntu1604, hack/gen-repository-iso/dockerfile.ubuntu1804, hack/gen-repository-iso/dockerfile.ubuntu2004, hack/gen-repository-iso/download-pkgs.sh, pkg/bootstrap/os/module.go, pkg/bootstrap/os/repository/repository_deb.go, pkg/bootstrap/os/repository/repository_rpm.go, pkg/bootstrap/os/tasks.go
* Remove RepositoryModule install packages command `yum install yum-utils`. 
* Add dockerfile that can generate repository iso file.
* RepositoryModule adds a defer function to reset os repository when its tasks failed.
=> remove yum install yum-utils 

apis/kubekey/v1alpha2/kubernetes_types.go, apis/kubekey/v1alpha2/network_types.go, pkg/common/kube_runtime.go, pkg/config/templates/cluster.go, pkg/core/connector/runtime.go, pkg/core/pipeline/pipeline.go, pkg/plugins/network/modules.go
* Fix the logger entry nil pointer panic.
* Modify multus-cni config structure.
* Fix some typo.
=> fix logger nil pointer panic

cmd/ctl/add/add_nodes.go, cmd/ctl/create/cluster.go, pkg/artifact/tasks.go, pkg/artifact/templates/manifest.go, pkg/common/kube_runtime.go, pkg/images/tasks.go, pkg/pipelines/add_nodes.go, pkg/pipelines/create_cluster.go
* change field `skip-install-packages` to `with-packages`
* Add 5 retries in image push function.
=> change field `skip-install-packages` to `with-packages`

docs/manifest-example.md, docs/zh/manifest_and_artifact.md
Add a zh doc introducing the new features of kubekey.
Please take a look at this PR, thanks.
/cc @kubesphere/sig-installation @kubesphere/sig-docs 
Fixes #
```
```
```release-note
```
```docs
```
=> add a zh doc introducing the new features of kubekey

docs/features.md, docs/registry.md
Signed-off-by: feng <guofeng@yunify.com>
Add a complete list of  features for KubeKey
Fixes #
```
```
```release-note
```
```docs
```
=> Add features list for KubeKey

docs/manifest-example.md
Fix some incorrect fields.
Fixes #1071 #
```
```
```release-note
```
```docs
```
=> modify manifest example

cmd/ctl/artifact/export.go, cmd/ctl/artifact/images/images.go, cmd/ctl/artifact/images/push.go, pkg/bootstrap/precheck/module.go, pkg/bootstrap/precheck/tasks.go, pkg/common/kube_runtime.go, pkg/filesystem/module.go, pkg/images/module.go, pkg/images/tasks.go, pkg/pipelines/artifact_export.go
/kind feature
Add a command to push images.
> Note: A container manager(docker, containerd) is required in the kubekey work node
Usages:
```
./kk artifact images push -f config.yaml 
./kk artifact images push -f config.yaml -a kubekey-artifact.tar.gz
./kk artifact images push -f config.yaml --images-dir ./kubekey/images
```
Fixes #
```
```
```release-note
```
```docs
```
=> add images push command

pkg/images/images.go
/kind bug
Make push image to support namespace override.
Fixes #
```
```
```release-note
```
```docs
```
=> make push image to support namespace override

.goreleaser.yml, pkg/k3s/tasks.go, pkg/kubernetes/tasks.go
/kind bug
1. Fix the error of kubeconfig's permission in non-root user.
2. [Packaging only the binaries](https://goreleaser.com/customization/archive/?h=readme#packaging-only-the-binaries) in release package. 
Fixes #
```
```
```release-note
```
```docs
```
=> Fix the error of kubeconfig's permission in non-root user

cmd/ctl/artifact/artifact.go, cmd/ctl/artifact/export.go, cmd/ctl/create/manifest.go, docs/manifest_and_artifact.md
add manifest and artifact en doc
Fixes #
```
```
```release-note
```
```docs
```
=> add manifest and artifact en doc

docs/commands/kk-add-nodes.md, docs/commands/kk-add.md, docs/commands/kk-artifact-export.md, docs/commands/kk-artifact-images-push.md, docs/commands/kk-artifact-images.md, docs/commands/kk-artifact.md, docs/commands/kk-certs-check-expiration.md, docs/commands/kk-certs-renew.md, docs/commands/kk-certs.md, docs/commands/kk-completion.md, docs/commands/kk-create-cluster.md, docs/commands/kk-create-config.md, docs/commands/kk-create-manifest.md, docs/commands/kk-create.md, docs/commands/kk-delete-cluster.md, docs/commands/kk-delete-node.md, docs/commands/kk-delete.md, docs/commands/kk-init-os.md, docs/commands/kk-init-registry.md, docs/commands/kk-init.md, docs/commands/kk-plugin-list.md, docs/commands/kk-plugin.md, docs/commands/kk-upgrade.md, docs/commands/kk-version.md, docs/commands/kk.md
Add kk command doc. You can preview it from this link: https://github.com/24sama/kubekey/blob/v2.0.0/docs/commands/kk.md 
Fixes #
```
```
```release-note
```
```docs
```
=> add kk command doc

README.md, docs/roadmap.md
Update the roadmap.
Fixes #
```
```
```release-note
```
```docs
```
=> update the roadmap

pkg/certs/module.go
/kind bug
Fixes #1147
Signed-off-by: cumirror <jacksontong@yunify.com>
=> Fix #1147: Error in the script used to automatically update certificate in cluster.

docs/config-example.md
Signed-off-by: vincent <vincent@kubesphere.io>
config-example.md add containerManager kata NFD example 
Fixes #
```
```
```release-note
config-example.md add containerManager kata NFD example
```
config-example.md add containerManager kata NFD example
```docs
config-example.md add containerManager kata NFD example
```
=> add containerManager kata NFD

README.md, README_zh-CN.md, docs/commands/kk-init-os.md, pkg/bootstrap/confirm/tasks.go, pkg/bootstrap/os/repository/repository_deb.go, pkg/bootstrap/os/repository/repository_rpm.go, pkg/bootstrap/os/tasks.go, pkg/bootstrap/precheck/const.go
/kind bug
Fixes #1051
```
Since `kk` works by accessing the node via ssh and then executing a shell command, it is not suitable to use the `ipvs` library for this task.
And when using shell commands to clear the IPVS rules, it may fail because the `ipvsadm` command does not exist on the node. So, we can only use our best efforts to clear the ipvs rules.
```
None
```release-note
```
```docs
```
Signed-off-by: laminar <fangtian@kubesphere.io>
=> fix #1051: Best efforts to clear ipvs rules.

README_zh-CN.md
Initialize the deployment to choose a different container runtime
=> Initialize  choose container runtime

pkg/container/templates/containerd_config.go
/kind bug
Fixes #1165 
```
```
https://github.com/containerd/containerd/blob/main/docs/cri/registry.md
=> fix containerd registry authorization failed

docs/manifest-example.md
Fix manifest example yaml file indentation problem.
Fixes #
```
```
```release-note
```
```docs
```
=> fix manifest example yaml file indentation problem

Dockerfile, Dockerfile.binaries, config/default/manager_auth_proxy_patch.yaml, config/manager/kustomization.yaml, controllers/kubekey/cluster_controller.go, go.mod, manifests/deploy.yaml
/kind cleanup
update kk operator to latest
Fixes #
```
```
```release-note
```
```docs
```
=> update kk operator to latest

apis/kubekey/v1alpha2/default.go, docs/config-example.md, docs/manifest-example.md, pkg/artifact/manifest.go, pkg/artifact/templates/manifest.go, pkg/binaries/kubernetes.go, pkg/bootstrap/confirm/tasks.go, pkg/bootstrap/precheck/const.go, pkg/bootstrap/precheck/tasks.go, pkg/bootstrap/registry/module.go, pkg/common/common.go, pkg/config/templates/cluster.go, pkg/container/containerd.go, pkg/container/docker.go, pkg/container/module.go, pkg/container/templates/containerd_config.go, pkg/container/templates/docker_config.go, pkg/files/file.go, pkg/images/tasks.go, pkg/images/utils.go, pkg/kubernetes/templates/v1beta2/kubeadm_config.go, pkg/registry/docker_registry_config.go
/kind feature
Support containerd v1.6.2 and separate it from docker.
Fixes #1131 #812
```
```
```release-note
```
```docs
```
=> support containerd v1.6.2 and separate it from docker

cmd/ctl/add/add_nodes.go, cmd/ctl/create/cluster.go, cmd/ctl/options/common_options.go, controllers/kubekey/cluster_controller.go, controllers/kubekey/update_cluster.go, main.go, pkg/common/kube_runtime.go
Signed-off-by: Ben Ye <ben.ye@bytedance.com>
/kind feature
This pr adds the support to specify the kubekey namespace. Currently it is hardcoded and it is not suitable for us who has strong namespace name requirement.
Fixes #1176 
```
```
```release-note
```
```docs
```
=> Make kubekey namespace configurable

pkg/config/generate.go, pkg/version/kubesphere/ks_installer.go, pkg/version/kubesphere/templates/cc_v330.go, pkg/version/kubesphere/version_enum.go
/kind feature
support kubesphere v3.3.0
Fixes #
```
```
```release-note
```
```docs
```
=> support kubesphere v3.3.0

pkg/config/templates/cluster.go
/kind cleanup
Fixes #
```
```
```release-note
```
```docs
```
=> delete auths field

pkg/version/kubesphere/templates/cc_v330.go
/kind bug
add cc v3.3.0 "zone" and "namespace_override" fields
Fixes #
```
```
```release-note
```
```docs
```
=> add cc v3.3.0 "zone" and "namespace_override" fields

docs/commands/kk-create-config.md
deafult -> default
```release-note
NONE
```
```docs
```
=> Fix typo in kk-create-config.md

apis/kubekey/v1alpha2/cluster_types.go, apis/kubekey/v1alpha2/default.go, cmd/ctl/artifact/images/push.go, go.mod, go.sum, pkg/bootstrap/precheck/module.go, pkg/bootstrap/precheck/tasks.go, pkg/core/connector/dialer.go, pkg/core/connector/host.go, pkg/core/connector/interface.go, pkg/core/connector/ssh.go, pkg/core/task/remote_task.go, pkg/pipelines/add_nodes.go, pkg/pipelines/artifact_export.go, pkg/pipelines/check_certs.go, pkg/pipelines/create_cluster.go, pkg/pipelines/delete_cluster.go, pkg/pipelines/delete_node.go, pkg/pipelines/init_dependencies.go, pkg/pipelines/init_registry.go, pkg/pipelines/renew_certs.go, pkg/pipelines/upgrade_cluster.go
/kind feature
Add a "timeout" option for the host TCP connection to establish
There are 2 changes:
* add a `timeout` field, and its default value is 10 seconds
* close the SSH connection at the end of each task
* add a `GreetingsModule` for testing ssh connection.
Fixes #
```
```
```release-note
```
```docs
```
=> add a "timeout" option for the host TCP connection to establish

cmd/ctl/artifact/images/push.go, pkg/bootstrap/precheck/module.go, pkg/bootstrap/precheck/tasks.go
/kind cleanup
remove cri pre-check which is in the ImagesPushPipeline
Fixes #
```
```
```release-note
```
```docs
```
=> remove cri pre-check which is in the ImagesPushPipeline

cmd/ctl/init/init_os.go, pkg/artifact/manifest.go, pkg/bootstrap/os/module.go, pkg/bootstrap/os/repository/repository.go, pkg/bootstrap/os/repository/repository_deb.go, pkg/bootstrap/os/repository/repository_rpm.go, pkg/bootstrap/os/rollback.go, pkg/bootstrap/os/tasks.go, pkg/common/kube_runtime.go, pkg/pipelines/init_dependencies.go, pkg/pipelines/init_registry.go
/kind feature
* support init os command to use an artifact
* repository module supports for RHEL, Debian
Fixes #1223 
Fixes #1224
```
```
```release-note
```
```docs
```
=> support init os command to use artifact

pkg/version/kubesphere/templates/cc_v330.go
/kind bug
fix missing cc field value.
Fixes #1225
```
```
```release-note
```
```docs
```
=> fix missing cc field value.

hack/gen-repository-iso/packages.yaml
/kind bug
fix centos iso file missing conntrack
Fixes #
```
```
```release-note
```
```docs
```
=> fix centos iso file missing conntrack

pkg/core/pipeline/pipeline.go, pkg/core/task/remote_task.go
/kind cleanup
modify close ssh connect logic
Fixes #
```
```
```release-note
```
```docs
```
=> modify close ssh connect logic

pkg/bootstrap/confirm/tasks.go, pkg/common/local_runtime.go
/kind cleanup
* add auto-generate local ssh key in "localRuntime"
* Modify the log print
Fixes #
```
```
```release-note
```
```docs
```
=> add auto-generate local ssh key in "localRuntime"

pkg/binaries/registry.go, pkg/bootstrap/registry/module.go, pkg/bootstrap/registry/tasks.go
/kind bug
* Make sure that both `/etc/ssl/registry/ssl` and "/etc/docker/certs.d/dockerhub.kubekey.local" have registry certs files.
* Fix missing docker binary when artifact contains the harbor binaries.
Fixes #
```
```
```release-note
```
```docs
```
=> sync certs file to all nodes ssl dir

docs/commands/kk-artifact-export.md, docs/commands/kk-init-os.md, docs/manifest_and_artifact.md, docs/zh/manifest_and_artifact.md
update artifact doc
Fixes #
```
```
```release-note
```
```docs
```
=> update artifact doc

pkg/registry/docker_registry_config.go
/kind cleanup
Remove printing fatal log.
Fixes #
```
```
```release-note
```
```docs
```
=> remove printing fatal log

docs/config-example.md, docs/manifest-example.md, pkg/config/templates/cluster.go, pkg/images/tasks.go, pkg/registry/docker_registry_config.go
/kind bug
This PR https://github.com/kubesphere/kubekey/pull/1258 causes a new bug, which is `skipTLSVerify` can not clearly distinguish between skipping TLS verify and using HTTP.
Fixes https://github.com/kubesphere/kubekey/pull/1258
```
```
```release-note
```
```docs
```
=> fix  "skipTLSVerify" field can not clearly distinguish between skipping TLS verify and using HTTP.

pkg/container/module.go, pkg/container/templates/containerd_config.go
/kind bug
fix containerd does not apply insecureRegistries in config.toml
Fixes #1268 #1270
=> fix: fix containerd does not apply insecureRegistries in config.toml

pkg/version/kubesphere/ks_installer.go
Add k8s v1.23 support for KubeSphere
Fixes #
```
```
```release-note
```
```docs
```
=> Add k8s v1.23 support for KubeSphere

pkg/bootstrap/confirm/tasks.go, pkg/common/loader.go, pkg/images/tasks.go
/kind bug
If `--with-kubernetes` is specified, it can override the configuration of `spec.kubernetes` in the configuration file.
Fixes #
```
```
```release-note
```
```docs
```
=> Fix: --with-kubernetes override the configuration of spec.kubernetes

pkg/kubesphere/tasks.go, pkg/pipelines/create_cluster.go, pkg/version/kubesphere/templates/installer.go
/kind cleanup
Change ks-installer label "app=ks-install" to "app=ks-installer"
Fixes #
```
```
```release-note
```
```docs
```
=> fix: change ks-installer label "app=ks-install" to "app=ks-installer"

pkg/bootstrap/confirm/tasks.go, pkg/bootstrap/precheck/tasks.go, pkg/common/common.go
add a notice when deploying k8s v1.24
#1274 
```
```
```release-note
```
```docs
```
=> doc: add a notice when deploying k8s v1.24

.github/workflows/gen-repository-iso.yaml, Makefile, hack/gen-repository-iso/dockerfile.ubuntu2204, hack/gen-repository-iso/packages.yaml
Signed-off-by: muzi502 <muzi502.li@gmail.com>
Add support for building ubuntu 22.04 repository iso
Fixes # https://github.com/kubesphere/kubekey/issues/1281
```
```
```release-note
```
```docs
```
=> Add support for building ubuntu 22.04 repository iso

pkg/kubernetes/templates/v1beta2/kubeadm_config.go
/kind bug
Remove kubelet pod pid limit
Fixes #https://github.com/kubesphere/kubekey/issues/1305
```
```
```release-note
```
```docs
```
=> fix: remove kubelet pod pid limit

pkg/bootstrap/os/common.go, pkg/bootstrap/os/tasks.go
/kind cleanup
cleanup: remove unused host cache
Fixes #
```
```
```release-note
```
```docs
```
=> cleanup: remove unused host cache

pkg/artifact/manifest.go, pkg/config/generate.go, pkg/core/pipeline/pipeline.go
/kind feature
feat: add a notice after creating a kubekey file
Fixes #
```
```
```release-note
```
```docs
```
=> feat: add a notice after creating a kubekey file

README.md, apis/kubekey/v1alpha2/default.go
* Modify readme 
* Make k8s v1.23.7 as the default version
Fixes #
```
```
```release-note
```
```docs
```
=> doc: modify readme and make k8s v1.23.7 as the default version

pkg/bootstrap/os/module.go, pkg/bootstrap/os/tasks.go, pkg/certs/module.go, pkg/pipelines/delete_node.go
/kind bug
Replace the "ClearOSEnvironmentModule" in the "DeleteNodePipeline" with the "ClearNodeOSModule". Because sometimes, the user deletes a node but doesn't want to remove the `/var/openebs` directory.
Fixes #
```
```
```release-note
```
```docs
```
=> fix: replace the "ClearOSEnvironmentModule" in the "DeleteNodePipeline" with the "ClearNodeOSModule"

docs/config-example.md, pkg/bootstrap/confirm/tasks.go
doc: modify prompt text
Fixes #
```
```
```release-note
```
```docs
```
=> doc: modify prompt text

cmd/ctl/create/config.go
Fixes #1333 
```
```
```release-note
```
```docs
```
=> doc: modify the command flag description

pkg/bootstrap/precheck/tasks.go
/kind bug
fix: can't upgrade k8s version when ks version does not changed
Fixes #
```
```
```release-note
```
```docs
```
=> fix: can't upgrade k8s version when ks version does not changed

pkg/kubernetes/templates/v1beta2/kubeadm_config.go
/kind bug
fix: the default cgroup driver wrong configured
Fixes #1346 
```
```
```release-note
```
```docs
```
=> fix: the default cgroup driver wrong configured

README.md, README_zh-CN.md
=> update supported kubernetes versions

docs/kubekey-autocompletion.md
=> [#1390] fix kk bash completion doc

pkg/pipelines/artifact_export.go
fix：remove GreetingModule that is in the ArtifactPipeline
Fixes #1387 
```
```
```release-note
```
```docs
```
=> fix：remove GreetingModule that is in the ArtifactPipeline

pkg/kubernetes/templates/kubelet_service.go
/kind feature
https://github.com/kubernetes/kubernetes/issues/56850
```
Failed to get system container stats for "/system.slice/kubelet.service": failed to get cgroup stats for "/system.slice/kubelet.service": failed to get container info for "/system.slice/kubelet.service": unknown container "/system.slice/kubelet.service"
```
Enable CPUAccounting and MemoryAccounting for kubelet by default
```
[Unit]
Description=kubelet: The Kubernetes Node Agent
Documentation=http://kubernetes.io/docs/
[Service]
CPUAccounting=true
MemoryAccounting=true
ExecStart=/usr/local/bin/kubelet
Restart=always
StartLimitInterval=0
RestartSec=10
[Install]
WantedBy=multi-user.target
```
Fixes #
```
```
```release-note
```
```docs
```
=> default enable kernel cpu and memory accounting

pkg/bootstrap/os/tasks.go
/kind bug
Fix: check Linux package manager error.
In some Linux distributions, using `which` command will return some message, so we need to check whether the command return `err`.
Fixes #
```
```
```release-note
```
```docs
```
=> fix: check linux package manager error

pkg/images/tasks.go, pkg/plugins/storage/templates/openebs.go
/kind feature
Upgrade OpenEBS to 3.3.0
Fixes #
```
```
```release-note
```
```docs
```
=> upgrade OpenEBS to 3.3.0

pkg/k3s/tasks.go, pkg/loadbalancer/module.go
/kind bug
fix bug that v1.21+ k3s can not join other master nodes normally when create a highly available cluster, and change incorrect description when create kube-vip daemonset
Fixes #
```
```
```release-note
```
```docs
```
=> fix k3s(v1.21+) add other master nodes bug

apis/kubekey/v1alpha2/default.go, pkg/files/file.go
/kind feature
update helm to v3.9.0
update harbor to v2.5.3
Fixes #
```
```
```release-note
```
```docs
```
=> upgrade helm and harbor

pkg/version/kubesphere/ks_installer.go, pkg/version/kubesphere/templates/cc_v331.go, pkg/version/kubesphere/version_enum.go
/kind feature
Support installation of kubesphere v3.3.1 
Fixes #
```
```
```release-note
Support installation of kubesphere v3.3.1 
```
```docs
```
=> feat: support kubesphere v3.3.1

exp/cluster-api-provider-kubekey/Dockerfile, exp/cluster-api-provider-kubekey/pkg/service/operation/file/binary.go
/kind bug
Fix a security issue by adding ca-certificates in Dockerfile.
Fixes #
```
```
```release-note
```
```docs
```
=> feat: add ca-certificates in Dockerfile

.github/workflows/gen-repository-iso.yaml, hack/gen-repository-iso/dockerfile.almalinux90, hack/gen-repository-iso/packages.yaml
Add support for building AlmaLinux 9.0 repository iso
```
```
```release-note
```
```docs
```
=> feat: Add support for building AlmaLinux 9.0 repository iso

hack/gen-repository-iso/dockerfile.almalinux90, hack/gen-repository-iso/packages.yaml
Fixes #
```
```
```release-note
```
```docs
```
=> fix: building AlmaLinux 9.0 repository iso

exp/cluster-api-provider-kubekey/Dockerfile, exp/cluster-api-provider-kubekey/controllers/kkinstance_controller_phase.go, exp/cluster-api-provider-kubekey/pkg/service/binary/binary.go, exp/cluster-api-provider-kubekey/pkg/service/interface.go
/kind bug
1. Fix the bug that some OS root user cannot find kubeadm.
2. Make the go mod in dockerfile uses cache.
Fixes #
```
```
```release-note
```
```docs
```
=> Fix the bug that some OS root user cannot find kubeadm.

apis/kubekey/v1alpha2/cluster_types.go, apis/kubekey/v1alpha2/default.go, pkg/loadbalancer/module.go, pkg/loadbalancer/tasks.go, pkg/loadbalancer/templates/k3sKubevipManifest.go, pkg/loadbalancer/templates/kubevipManifest.go, pkg/pipelines/delete_cluster.go, pkg/pipelines/delete_node.go
/kind feature
Support kube-vip BGP mode
Fixes #
```
```
```release-note
```
```docs
```
=> Support kube-vip BGP mode

exp/cluster-api-provider-kubekey/test/e2e/config/e2e_conf.yaml, exp/cluster-api-provider-kubekey/test/e2e/data/infrastructure-kubekey/v1beta1/bases/cluster-with-kcp.yaml, exp/cluster-api-provider-kubekey/test/e2e/quick_start_test.go
/kind cleanup
cleanup: modify e2e config template
Fixes #
```
```
```release-note
```
```docs
```
=> cleanup: modify e2e config template

pkg/loadbalancer/module.go, pkg/loadbalancer/tasks.go
/kind feature
When a highly available cluster created with kube-vip is deleted,the cluster's network interface will retain the vip,so the vip needs to be cleaned up.
Fixes #
```
```
```release-note
```
```docs
```
=> Clean up the vip when delete cluster or nodes

.github/Jenkinsfile
/kind chore
Using [ks-devops](https://github.com/kubesphere/ks-devops/) to replace GitHub Actions. This only responsible for the PR building.
I will disable the GitHub Actions PR config once this works well for a week (or more time).
Fixes #
```
```
```release-note
None
```
```docs
None
```
=> Using Jenkins Pipeline to replace GitHub Actions

pkg/loadbalancer/module.go
/kind bug
fix delete VIP skip bug
Fixes #
```
```
```release-note
```
```docs
```
=> fix delete VIP skip bug

pkg/k3s/module.go, pkg/k3s/prepares.go, pkg/k3s/tasks.go, pkg/k3s/templates/k3sRegistryConfig.go, pkg/kubernetes/templates/v1beta2/kubeadm_config.go, pkg/registry/k3s_registries.go, pkg/utils/util.go
/kind feature
Automatic `registries.yaml` generation for k3s when using private container image registry.
Fixes #
```
```
```release-note
```
```docs
```
=> feat: auto generate k3s registries.yaml

pkg/bootstrap/registry/module.go
/kind bug
fix: registry node missing certs file.
Fixes #
```
```
```release-note
```
```docs
```
=> fix: registry node missing certs file

pkg/loadbalancer/tasks.go
/kind bug
When using kube-vip for high availability, kubekey will bind the **VIP** to the interface where the host ip is located. This can lead to a problem.Take `VIP=192.168.100.2` for example,if the host also has such as `192.168.100.2xx` ip address, then the `192.168.100.2xx` interface will be searched out resulting in errors.
The solution is to add a space before and after the ip when getting the interface.
Fixes #
```
```
```release-note
```
```docs
```
=> fix get interface bug

cmd/ctl/create/cluster.go, pkg/common/kube_runtime.go, pkg/kubernetes/module.go, pkg/kubernetes/tasks.go, pkg/kubernetes/templates/v1beta2/kubeadm_config.go, pkg/pipelines/create_cluster.go
/kind feature
use [CIS kubernetes benchmark](https://www.cisecurity.org/benchmark/kubernetes) to hardening the k8s cluster
create cluster command:
```
./kk create cluster --with-security-enhancement
```
Fixes #
```
```
```release-note
Add command '--with-security-enhancement' when create k8s cluster or add nodes
```
```docs
```
=> Add security enhancement command when create a cluster or add nodes 

cmd/ctl/artifact/import.go, cmd/ctl/create/phase/configure.go, cmd/ctl/create/phase/images.go, cmd/ctl/create/phase/init.go, cmd/ctl/create/phase/join.go, cmd/ctl/create/phase/os.go, docs/commands/kk-artifact-import.md, docs/commands/kk-create-phase.md, docs/commands/kk-upgrade-phase.md, pkg/alpha/binary/task.go, pkg/alpha/etcd/modules.go, pkg/alpha/images/create_images.go, pkg/alpha/images/modules.go, pkg/alpha/kubesphere/upgrade_kubesphere.go, pkg/alpha/precheck/modules.go, pkg/container/module.go
/kind feature
Add the docs for phase run, and fix some bug for phase run.
Fixes #
```
Fix two problems about the phase run:
One is adding the docker binary path in the cache when create phase images because it will install the docker and containerd.
The other is deleting the ksDependencyCheck in the first three upgrade phase run cmd, because it will cause fault due to the upgrade k8s version and the origin ks version.  
```
```release-note
```
```docs
```
=> feat: add phase run doc and fix some bug during the test

apis/kubekey/v1alpha1/groupversion_info.go, apis/kubekey/v1alpha2/cluster_types.go, apis/kubekey/v1alpha2/groupversion_info.go, cmd/ctl/create/cluster.go, pkg/bootstrap/os/repository/repository_deb.go, pkg/bootstrap/os/repository/repository_rpm.go, pkg/bootstrap/os/tasks.go
/kind feature
Fixes # [1486](https://github.com/kubesphere/kubekey/issues/1486)
```
```
```release-note
```
```docs
```
=> feat: Add rpms and debs support.

docs/config-example.md
Fixes #
```
```
```release-note
```
```docs
```
=> docs: Update config-example.md

pkg/kubernetes/templates/v1beta2/kubeadm_config.go
kind bug
fix bug
SupportPodPidsLimit is GA Feature, we do not need it at Feature Gates Configuration
Fixes #
```
```
```release-note
```
```docs
```
=> fix: remove "SupportPodPidsLimit" Feature Gate configuration

cmd/kk/cmd/create/cluster.go, cmd/kk/pkg/common/kube_runtime.go, cmd/kk/pkg/pipelines/create_cluster.go
/kind feature
Fix case issue in struct Argument.
Fixes #
```
```
```release-note
```
```docs
```
=> fix: argument field case issue

pkg/kubernetes/tasks.go, pkg/kubernetes/tasks_test.go
/kind bug
fix: calculate next version error
Fixes #
```
```
```release-note
```
```docs
```
=> fix: calculate next version error

.github/workflows/gen-repository-iso.yaml
/kind bug
fix: github action check error
Fixes https://github.com/kubesphere/kubekey/actions/runs/3296111026
```
```
```release-note
```
```docs
```
=> fix: github action check error

api/v1beta1/containermanager_types.go, api/v1beta1/kkmachine_webhook.go, config/crd/bases/infrastructure.cluster.x-k8s.io_kkinstances.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_kkmachines.yaml, config/crd/bases/infrastructure.cluster.x-k8s.io_kkmachinetemplates.yaml, pkg/service/containermanager/containerd.go, pkg/service/containermanager/docker.go, pkg/service/containermanager/service.go, pkg/service/containermanager/templates/cri-docker.service, pkg/service/containermanager/templates/cri-docker.socket, pkg/service/containermanager/templates/daemon.json, pkg/service/containermanager/templates/docker.service, pkg/service/operation/file/checksum/internal_checksum.go, pkg/service/operation/file/docker.go, test/e2e/config/e2e_conf.yaml, test/e2e/data/infrastructure-kubekey/v1beta1/bases/cluster-with-kcp.yaml, test/e2e/data/infrastructure-kubekey/v1beta1/bases/md.yaml
/kind feature
Fixes #1434
```
```
```release-note
```
```docs
```
=> CAPK support to install docker

.github/Jenkinsfile
Fixes #
```
```
```release-note
```
```docs
```
=> modify jenkinsfile

pkg/service/binary/k3s/binary.go, pkg/service/binary/kubernetes/binary.go, pkg/service/containermanager/containerd.go, pkg/service/containermanager/docker.go, pkg/service/repository/repository.go, pkg/service/util/downloader.go
/kind bug
fix log print wrong message
Fixes #
```
```
```release-note
```
```docs
```
=> fix log print wrong message

cmd/kk/pkg/k3s/tasks.go, cmd/kk/pkg/k3s/templates/k3sService.go
/kind feature
support k3s `--docker` and `--container-runtime-endpoint` flag, so we can use alternative CRI implementation.
Fixes #
```
```
```release-note
```
```docs
```
=> Feat: add k3s container runtime config

.github/workflows/ci.yml, .github/workflows/gen-repository-iso.yaml
/kind bug
fix the bug generating two release pages
Fixes #
```
```
```release-note
```
```docs
```
=> fix the bug generating two release pages

Makefile
/kind bug
fix set components yaml image name error
Fixes #
```
```
```release-note
```
```docs
```
=> fix set components yaml image name error

README.md, README_zh-CN.md
Signed-off-by: Vinson Zou <vinsonzou@users.noreply.github.com>
Fixes #
```
```
```release-note
```
```docs
```
=> docs: update README [skip ci]

docs/components-versions.md
fix issue #1433
Signed-off-by: Deshi Xiao <xiaods@gmail.com>
quote from request "like calico which default version information is in [apis/kubekey/v1alpha1/default.go](https://github.com/kubesphere/kubekey/blob/986449b5790df0928fff9605bd885c9836db622c/apis/kubekey/v1alpha1/default.go#L43) instead of a document , so have a document to show versions of plugins and components used by kubekey can help users troubleshoot version compatibility issues more easily"
this changed based on  [v1alpha2](https://github.com/kubesphere/kubekey/blob/master/cmd/kk/apis/kubekey/v1alpha2/default.go).
Fixes #1433 
```
```
```release-note
```
```docs
```
=> docs: add versions of default plugins and components used by kubekey

docs/kubernetes-versions.md
error: No SHA256 found for kubeadm. v1.24.8 is not supported.
To See: https://kubernetes.io/releases/patch-releases/#1-24
Fixes # v1.24.8 -> v1.24.7
```
```
```release-note
```
```docs
```
=> doc:Update kubernetes-version.md

cmd/kk/pkg/bootstrap/confirm/tasks.go, cmd/kk/pkg/images/tasks.go, cmd/kk/pkg/kubernetes/tasks.go, cmd/kk/pkg/kubernetes/templates/v1beta2/kubeadm_config.go, cmd/kk/pkg/pipelines/add_nodes.go, cmd/kk/pkg/pipelines/create_cluster.go
/kind bug
fix some feature-gates removed in k8s v1.25.x
Fixes #1593
Fixes #1592
```
```
```release-note
```
```docs
```
=> fix some feature-gates removed in k8s v1.25.x

templates/cluster-template.yaml
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> modify cluster-template.yaml

cmd/kk/pkg/binaries/registry.go, cmd/kk/pkg/files/file.go
/kind bug
print a warning log about download harbor arm64
#1553
```
```
```release-note
```
```docs
```
=> print a warning log about download harbor arm64

cmd/kk/pkg/version/kubernetes/version_enum.go
/kind cleanup
Auto generate support versions list for `kk version --show-supported-k8s`
Fixes #
```
```
```release-note
```
```docs
```
=> Auto generate support versions list

cmd/kk/cmd/alpha/alpha.go, cmd/kk/cmd/alpha/cri/cri.go, cmd/kk/cmd/alpha/cri/migrate_cri.go, cmd/kk/cmd/root.go
/kind api-change
/kind cleanup
move cri command to alpha
Fixes #
```
```
```release-note
```
```docs
```
=> move cri command to alpha

cmd/kk/apis/kubekey/v1alpha2/cluster_types.go
/kind bug
fix the field difference between yaml and json
Fixes #
```
```
```release-note
```
```docs
```
=> fix the field difference between yaml and json

apis/kubekey/v1alpha2/default.go, pkg/bootstrap/os/tasks.go, pkg/etcd/tasks.go, pkg/etcd/templates/backup_script.go, pkg/etcd/templates/backup_service.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> [release-2.3] Fix etcd script to delete other files when there is no space left on device

apis/kubekey/v1alpha2/default.go, pkg/bootstrap/os/tasks.go, pkg/etcd/tasks.go, pkg/etcd/templates/backup_script.go, pkg/etcd/templates/backup_service.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> [release-2.2] Fix etcd script to delete other files when there is no space left on device

apis/kubekey/v1alpha2/default.go, pkg/bootstrap/os/tasks.go, pkg/etcd/tasks.go, pkg/etcd/templates/backup_script.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> [release-2.1] Fix etcd script to delete other files when there is no space left on device

apis/kubekey/v1alpha2/default.go, pkg/bootstrap/os/tasks.go, pkg/etcd/tasks.go, pkg/etcd/templates/backup_script.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> [release-2.0] Fix etcd script to delete other files when there is no space left on device

apis/kubekey/v1alpha1/default.go, pkg/cluster/delete/delete.go, pkg/etcd/tmpl/etcdbackup.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> [release-1.2] Fix etcd script to delete other files when there is no space left on device

apis/kubekey/v1alpha1/default.go, pkg/cluster/delete/delete.go, pkg/etcd/tmpl/etcdbackup.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> [release-1.1] Fix etcd script to delete other files when there is no space left on device

.github/workflows/kubernetes-auto-support.yaml, .github/workflows/release.yaml
/kind cleanup
* Upgrade qsctl version
* Auto synchronize artifacts to OSS
Fixes #
```
```
```release-note
```
```docs
```
=> Auto synchronize artifacts to OSS

hack/sync-components.sh
/kind cleanup
The new version of qsctl has no `--force` parameter.
Fixes #
```
```
```release-note
```
```docs
```
=> remove --force for qsctl

cmd/kk/cmd/artifact/images/push.go
/kind cleanup
Fixes #
```
```
```release-note
```
```docs
```
=> cleanup(kk): remove greeting module

cmd/kk/pkg/images/tasks.go
/kind bug
Fixes #
```
```
```release-note
```
```docs
```
=> fix(kk): handle the duplicate image name which in the kk artifact

cmd/kk/pkg/pipelines/create_cluster.go
add some code comments to avoid confusion, see #1689 
```
```
```release-note
```
```docs
```
=> docs: instruction on kubeVip module invocation

docs/config-example.md
Fixes #1702
```
```
```release-note
```
```docs
```
=> docs: instruction on avoiding issue 1702

cmd/kk/pkg/bootstrap/registry/module.go
/kind cleanup
Fix typo and tune description in registry bootstrap module:
* Tune description of `installRegistryBinary` task
* Fix typo `startRgistryService` to `startRegistryService`
```
None
```
```release-note
None
```
```docs
```
=> Fix typo and tune description in registry bootstrap module

cmd/kk/pkg/bootstrap/confirm/tasks.go, cmd/kk/pkg/bootstrap/confirm/tasks_test.go
/kind bug
Fixes #1781
```
```
```release-note
```
```docs
```
=> fix: RefineDockerVersion can not parse zero minor version correctly

cmd/kk/apis/kubekey/v1alpha2/etcd_types.go, cmd/kk/pkg/etcd/tasks.go, cmd/kk/pkg/etcd/templates/etcd_env.go, docs/config-example.md
/kind feature
add more etcd parameters
Fixes #
```
```
```release-note
add more etcd parameters
```
```docs
```
=> add more etcd parameters

hack/gen-repository-iso/dockerfile.centos7
bug
Fixes #1790
```
```
```release-note
```
```docs
```
=> fix: unable to build centos7 iso

.github/workflows/gen-repository-iso.yaml, hack/gen-repository-iso/dockerfile.debian11, hack/gen-repository-iso/packages.yaml
Add one of the following kinds:
/kind feature
Support Debian Stable 11,  https://wiki.debian.org/DebianReleases.
Reference: #1470
=> feat: Add support for building Debian 11 repository iso

cmd/kk/pkg/certs/module.go, cmd/kk/pkg/k3s/module.go, cmd/kk/pkg/k3s/tasks.go, cmd/kk/pkg/k8e/module.go, cmd/kk/pkg/k8e/tasks.go, cmd/kk/pkg/kubernetes/module.go, cmd/kk/pkg/kubernetes/tasks.go
* kubeconfig is only for ops user, worker node don't need kubeconfig
Signed-off-by: Deshi Xiao <xiaods@gmail.com>
/kind bug
Fixes #1663
User feedback:
When kubekey do installation it adds kubectl and kube config on all worker nodes. I understand why it needs on masters but why it needs on workers i don`t understand i think it is like security bug of installation
```release-note
```
```docs
```
=> fix: remove syncKubeConfigToWorker with strict security concerns

cmd/kk/cmd/delete/delete_cluster.go, cmd/kk/pkg/bootstrap/confirm/module.go, cmd/kk/pkg/pipelines/delete_cluster.go
Make `./kk delete cluster -y` effective
=> fix(cluster): delete cluster confirm skip

cmd/kk/apis/kubekey/v1alpha2/cluster_types.go, cmd/kk/pkg/container/module.go, cmd/kk/pkg/container/templates/docker_config.go
feature
Fixes #
```
support Configure the default bridge network
```
```release-note
```
```docs
config:
registry:
bridgeIP: "10.110.0.0/24"
ex: daemon.json
{
"bip": "10.110.0.1/24"
}
```
=> support Configure the default bridge network

cmd/kk/pkg/bootstrap/os/templates/init_script.go, cmd/kk/pkg/bootstrap/registry/certs.go, cmd/kk/pkg/bootstrap/registry/module.go, cmd/kk/pkg/bootstrap/registry/tasks.go, cmd/kk/pkg/k3s/tasks.go
/kind feature
supported custom local registry domain
Fixes #
```
```
```release-note
supported custom local registry domain
```
```docs
```
=> feat: supported custom local registry domain

cmd/kk/cmd/delete/delete_node.go, cmd/kk/pkg/bootstrap/confirm/module.go, cmd/kk/pkg/pipelines/delete_node.go
Make `kk delete node -y` effective.
=> fix(node): delete node confirm skip

hack/version.sh
Add one of the following kinds:
/kind bug
Fixes #1851
=> [#1851] fix hack/version.sh incorrect git version

README.md, README_zh-CN.md
=> [doc] Update README to state that Debian 11 Bullseye is supported

cmd/kk/pkg/bootstrap/os/templates/init_script.go
/kind bug
init the kernel parameter
Which causing abnormal health check of Pod: net.ipv4.tcp_tw_reuse
Which modified causing abnormal NAT: net.ipv4.tcp_tw_recycle
Which modified causing network connection failure: net.ipv4.conf.all.rp_filter, net.ipv4.conf.default.rp_filter.
=> fix: change default kernel paramter.

cmd/kk/pkg/images/images.go
In online mode, specify image platform when pull will be helpful.
=> perf(image): pull image specify arch

docs/CAPKK-Developer-Guide.md, docs/zh/CAPKK开发文档.md
/kind cleanup
Add capkk documents
Fixes #
```
```
```release-note
```
```docs
```
=> Add capkk documents

cmd/kk/cmd/plugin/list.go, cmd/kk/pkg/artifact/manifest.go, cmd/kk/pkg/artifact/tasks.go, cmd/kk/pkg/bootstrap/customscripts/tasks.go, cmd/kk/pkg/client/kubernetes/client.go, cmd/kk/pkg/common/artifact_runtime.go, cmd/kk/pkg/core/connector/ssh.go, cmd/kk/pkg/core/util/file.go, cmd/kk/pkg/etcd/certs.go, cmd/kk/pkg/files/file.go, cmd/kk/pkg/images/tasks.go, cmd/kk/pkg/k3s/k3s_status.go, cmd/kk/pkg/k8e/k8e_status.go, cmd/kk/pkg/kubernetes/kubernetes_status.go
/kind cleanup
ioutil Deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code.
We already use Go 1.19, so we can change to use os or io package.
Fixes #
```
```
```release-note
```
```docs
```
=> use os or io package to replace ioutil package

cmd/kk/pkg/bootstrap/os/module.go, cmd/kk/pkg/bootstrap/os/tasks.go
/kind bug
When we remove node from cluster, we will execute "ResetNetworkConfig" and “RemoveFiles” task. At task of "RemoveFiles", it will delete files including "/etc/systemd/system/kubelet.service" and "/etc/systemd/system/kubelet.service.d". But there is no operation for stop kubelet service. So kubelet service will get some errors when execute "DaemonReload"  task last.
So, we need to stop kubelet service first, then we can execute "RemoveFiles" task.
Fixes #
```
```
```release-note
```
```docs
```
=> stop kubelet service first when remove worker node.

cmd/kk/pkg/pipelines/add_nodes.go, cmd/kk/pkg/pipelines/artifact_export.go, cmd/kk/pkg/pipelines/create_cluster.go, cmd/kk/pkg/pipelines/delete_cluster.go
/kind feature
Having a more clear code style.
Fixes #
```
None
```
```release-note
None
```
```docs
None
```
=> chore: remove the duplicated switch statements

cmd/kk/apis/kubekey/v1alpha2/cluster_types.go, cmd/kk/apis/kubekey/v1alpha2/default.go, cmd/kk/apis/kubekey/v1alpha2/kubernetes_types.go, cmd/kk/pkg/bootstrap/os/templates/init_script.go, cmd/kk/pkg/common/kube_prepare.go, cmd/kk/pkg/common/loader.go, cmd/kk/pkg/kubernetes/module.go, cmd/kk/pkg/kubernetes/tasks.go, cmd/kk/pkg/kubernetes/templates/audit.go, cmd/kk/pkg/kubernetes/templates/v1beta2/kubeadm_config.go, hack/sync-components.sh
/kind feature
Support for enabling kube-apiserver auditing
Fixes #
```
```
```release-note
```
```docs
```
=> feat: Support for enabling kube-apiserver auditing

controllers/kkcluster/kkcluster_controller.go, controllers/kkinstance/kkinstance_controller.go, controllers/kkmachine/kkmachine_controller.go
/kind bug
First check if the finalizer exists, then proceed with the patch operation.
=> add finalizer be more robust

templates/cluster-template.yaml
/kind feature
when use `generate cluster`. it will generate autoscaler resource and machinehealthycheck resource
add autoscaler and machinehealthycheck in template.yaml
=> feat: add autoscaler and machinehealthycheck

cmd/kk/pkg/version/kubesphere/ks_installer.go, cmd/kk/pkg/version/kubesphere/templates/cc_v340.go, cmd/kk/pkg/version/kubesphere/version_enum.go
/kind feature
update version to v3.1.0-rc.0
=> update version to v3.1.0-rc.0

docs/commands/kk-create-cluster.md
It is helpful for the newcomers to use the flag `--download-cmd`.
Fixes #
```
```
See also the test output:
```release-note
```
```docs
```
=> docs: add a new example of kk create with specific download cmd

cmd/kk/apis/kubekey/v1alpha2/manifest_types.go, cmd/kk/pkg/artifact/manifest.go, cmd/kk/pkg/binaries/kubernetes.go, docs/manifest-example.md
(cherry picked from commit 4a4c85b36b39b0455288775e2ae9d84b4134a4f8)
/kind cleanup
add calicoctl to artifact
Fixes #
```
```
```release-note
```
```docs
```
=> add calicoctl to artifact

pkg/service/containermanager/templates/config.toml
/kind bug
config.toml has not current params.
when config privateRegistry. like that.
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: KKCluster
metadata:
name: '${CLUSTER_NAME}'
spec:
registry:
privateRegistry: ""
namespaceOverride: ""
auth:
username: ""
password: ""
insecureSkipVerify: false
plainHTTP: false
certsPath: ""
```
An error will occur during deployment.
=> fix: Modify incorrect parameters

cmd/kk/apis/kubekey/v1alpha2/default.go
/kind feature
update default etcd version to v3.5.6
Fixes #
```
```
```release-note
```
```docs
```
=> update default etcd version to v3.5.6

cmd/kk/pkg/kubernetes/module.go, cmd/kk/pkg/kubernetes/tasks.go, cmd/kk/pkg/pipelines/add_nodes.go
Fixes #
```
```
```release-note
```
```docs
```
=> support kk add and delete node with master role

cmd/kk/apis/kubekey/v1alpha2/cluster_types.go, cmd/kk/pkg/pipelines/create_cluster.go, docs/config-example.md
/kind feature
In many cases, users need to install some packages before running `kk`. For instance: `chrony`, or `conntrack`.
Fixes #
```
None
```
```release-note
Add an initial step during the cluster creating phase
```
```docs
See also the example file
```
=> feat: add an initial stage at the very start cluster creating phase

cmd/kk/pkg/version/kubesphere/templates/cc_v340.go, cmd/kk/pkg/version/kubesphere/templates/installer.go
/kind cleanup
sync kubesphere v3.4.0 manifests
Fixes #
```
```
```release-note
```
```docs
```
=> sync kubesphere v3.4.0 manifests

cmd/kk/pkg/bootstrap/os/tasks.go, cmd/kk/pkg/bootstrap/precheck/tasks.go, cmd/kk/pkg/kubernetes/kubernetes_status.go, cmd/kk/pkg/kubernetes/module.go, cmd/kk/pkg/kubernetes/tasks.go, cmd/kk/pkg/version/kubernetes/version_enum.go, cmd/kk/pkg/version/kubesphere/ks_installer.go
/kind bug
fix KubeSphere version check error
Fixes #
https://github.com/kubesphere/kubekey/issues/1932
```
```
```release-note
```
```docs
```
=> fix: version check error

cmd/kk/pkg/plugins/network/modules.go, cmd/kk/pkg/plugins/network/templates/flannel.go
Fixes : I create a cluster use flannel but receive error , when k8s version in v1.25
```
flannel use PodSecurityPolicy, PodSecurityPolicyremove in k8s v1.25. so we use use the PodSecurity Admission.
see flannel PR [https://github.com/flannel-io/flannel/pull/1586](url)
```
```release-note
```
```docs
```
=> fix bug: when k8s version > v1.25.0 ,use flannel error

cmd/kk/pkg/bootstrap/registry/certs.go
Fixes #
```
```
```release-note
```
fix a few function names on comments
```docs
```
=> cmd: fix a few function names on comments

cmd/kk/apis/kubekey/v1alpha2/network_types.go, cmd/kk/pkg/plugins/network/tasks.go, cmd/kk/pkg/plugins/network/templates/hybridnet.go
/kind bug
Fix hybridnet configuration bug
Fixes #
```
```
```release-note
Fix hybridnet configuration bug
```
```docs
```
=> Fix hybridnet configuration bug

cmd/kk/apis/kubekey/v1alpha2/default.go, version/components.json
/kind feature
update docker version to 24.0.6
Fixes #
```
```
```release-note
update docker version to 24.0.6
```
```docs
```
=> update docker version to 24.0.6

cmd/kk/apis/kubekey/v1alpha2/addons_types.go, cmd/kk/pkg/addons/charts.go
/kind feature
It would be great if allowing users to choose wait or not when installing helm addon.
Fixes #
```
```
```release-note
```
```docs
feat: add the wait option for the helm addon config
```
=> feat: add the wait option for the helm addon config

cmd/kk/apis/kubekey/v1alpha2/cluster_types.go, cmd/kk/pkg/etcd/templates/etcd_env.go, cmd/kk/pkg/kubernetes/tasks.go, cmd/kk/pkg/kubernetes/templates/kubeadm_config.go, cmd/kk/pkg/pipelines/init_registry.go, cmd/kk/pkg/version/kubernetes/version_enum.go
Support v1beta3 of kubeadm config to to support the installation of kubernetes 1.27+
Fixes #
```
```
```release-note
Support v1beta3 of kubeadm config
```
```docs
```
=> Support v1beta3 of kubeadm config

cmd/kk/pkg/version/kubesphere/ks_installer.go, cmd/kk/pkg/version/kubesphere/templates/cc_v341.go, cmd/kk/pkg/version/kubesphere/version_enum.go
/kind feature
Fixes #
add support v3.4.1 for kubesphere
```
```
```release-note
add support v3.4.1 for kubesphere
```
```docs
```
=> fix(release): add support v3.4.1 for kubesphere

cmd/kk/pkg/core/util/ip.go
/kind feature
Fixes #
```
```
```release-note
add an env `KKLOCALIP` to specific local ip address for allinone cluster
```
```docs
```
=> add KKLOCALIP env to specify local ip address for allinone cluster

cmd/kk/pkg/bootstrap/registry/certs.go, cmd/kk/pkg/bootstrap/registry/tasks.go
/kind cleanup
refine installition of registry logic，avoid always using the host name as the repository domain.
Fixes #
```
```
```release-note
refine installition of registry logic
```
```docs
```
=> refine installition of registry logic

cmd/kk/pkg/etcd/templates/etcd_env.go, cmd/kk/pkg/kubernetes/tasks.go
/kind cleanup
Fix typos
* `Kubenretes` to `Kubernetes`
* etcd `ETCD_PEER_CLIENT_CERT_AUTH`  default value from `True` to `true` https://etcd.io/docs/v3.4/op-guide/configuration/#--peer-client-cert-auth
```
None
```
```release-note
None
```
=> Chores: fix typo

cmd/kk/pkg/bootstrap/os/tasks.go
keep chrony config file clean and consistency when install and uninstall cluster in the same nodes
Fixes #
```
```
```release-note
```
```docs
```
=> keep chrony config file clean and consistency when install and uninstall cluster in the same nodes

cmd/kk/apis/kubekey/v1alpha2/cluster_types.go, cmd/kk/apis/kubekey/v1alpha2/default.go, cmd/kk/pkg/bootstrap/os/tasks.go, cmd/kk/pkg/bootstrap/os/templates/init_script.go, cmd/kk/pkg/bootstrap/registry/certs.go, cmd/kk/pkg/core/connector/host.go, cmd/kk/pkg/core/connector/interface.go, cmd/kk/pkg/etcd/certs.go, cmd/kk/pkg/etcd/prepares.go, cmd/kk/pkg/etcd/tasks.go, cmd/kk/pkg/k3s/tasks.go, cmd/kk/pkg/k8e/tasks.go, cmd/kk/pkg/kubernetes/tasks.go, cmd/kk/pkg/kubernetes/templates/kubeadm_config.go, cmd/kk/pkg/kubesphere/tasks.go, cmd/kk/pkg/plugins/network/modules.go, cmd/kk/pkg/plugins/network/templates/calico_v1.16+.go, docs/config-example.md, pkg/service/bootstrap/bootstrap.go
/kind feature
add ipv6 support in k8s and calico  config,it compatible only ipv4 provide
like doc/config-example.md
just change host.internalAddress, kubePodsCIDR, kubeServiceCIDR with ipv6 address and cidr, you can deploy k8s with calico support ipv4/ipv6 cluster
and it compatible only ipv4 provide
Fixes #
```
```
```release-note
```
```docs
```
=> add ipv6 support in k8s and calico  config,it compatible only ipv4 provide

cmd/kk/pkg/container/containerd.go
/kind bug
Fixes #2143
```
```
```release-note
```
```docs
```
=> fix #2143: My bin directory was deleted by installContainerdMoudle

cmd/kk/apis/kubekey/v1alpha2/default.go, cmd/kk/apis/kubekey/v1alpha2/kubernetes_types.go, cmd/kk/pkg/binaries/kubernetes.go, cmd/kk/pkg/bootstrap/confirm/tasks.go, cmd/kk/pkg/bootstrap/os/templates/init_script.go, cmd/kk/pkg/bootstrap/precheck/tasks.go, cmd/kk/pkg/common/common.go, cmd/kk/pkg/common/kube_prepare.go, cmd/kk/pkg/container/docker.go, cmd/kk/pkg/container/module.go, cmd/kk/pkg/container/templates/cri_dockerd_service.go, cmd/kk/pkg/files/file.go, cmd/kk/pkg/kubernetes/module.go, cmd/kk/pkg/kubernetes/tasks.go, cmd/kk/pkg/pipelines/add_nodes.go, cmd/kk/pkg/pipelines/create_cluster.go, cmd/kk/pkg/pipelines/upgrade_cluster.go, cmd/kk/pkg/version/kubernetes/version_enum.go, hack/sync-components.sh, version/components.json
/kind feature
1. update cri-dockerd to v0.3.9
2. upgrade Kubernetes directly to v1.24+ with Docker runtime
Fixes #
```
```
```release-note
Support upgrade kubernetes to v1.24+ with Docker runtime
```
```docs
```
=> Support upgrade kubernetes to v1.24+ with Docker runtime

cmd/kk/apis/kubekey/v1alpha2/cluster_types.go, cmd/kk/pkg/bootstrap/os/templates/init_script.go, cmd/kk/pkg/bootstrap/registry/certs.go, cmd/kk/pkg/bootstrap/registry/module.go, cmd/kk/pkg/bootstrap/registry/tasks.go, cmd/kk/pkg/images/tasks.go
Fixes #
```
```
```release-note
support multi-level image warehouse path push
```
```docs
```
=> support multi-level image warehouse path push

version/components.json
/kind cleanup
upgrade sha256 for cri-docker
Fixes #
```
```
```release-note
upgrade sha256 for cri-docker
```
```docs
```
=> upgrade sha256 for cri-docker

cmd/kk/pkg/container/module.go
kind bug
Fixes #
```
fix bug: create cluster error，cri-docker binary error
```
```release-note
```
```docs
```
=> fix bug: add missing Skip for InstallCriDockerdModule

hack/gen-repository-iso/dockerfile.ubuntu2204, hack/gen-repository-iso/packages.yaml
Fixes #
```
```
```release-note
Add ubuntu2204 cuda for iso repo
```
```docs
```
=> Add ubuntu2204 cuda for iso repo

cmd/kk/pkg/binaries/kubernetes.go
/kind bug
fix: add containermanager binary to artifact
Fixes #
```
add containermanager binary to artifact
```
```release-note
```
```docs
```
=> fix: Relax artifact strategy. add containerManager

cmd/kk/pkg/kubernetes/tasks.go
/kind cleanup
add kubekey-system to system workspace
Fixes #
```
```
```release-note
/kind cleanup
```
```docs
```
=> add kubekey-system to system workspace

cmd/kk/pkg/bootstrap/os/templates/init_script.go, cmd/kk/pkg/etcd/templates/etcd_service.go, cmd/kk/pkg/plugins/network/templates/calico.tmpl
/kind cleanup
system performance optimization
1. Add kernel parameters to prevent keepalive connection failures.
2. Set cpu and memory priorities for etcd
3. fix calico ipv6 mistake
Fixes #
```
```
```release-note
system performance optimization
```
```docs
```
=> system performance optimization

cmd/kk/apis/kubekey/v1alpha2/network_types.go, cmd/kk/pkg/plugins/network/tasks.go, cmd/kk/pkg/plugins/network/templates/calico.tmpl
/kind cleanup
add replicas and nodeselector fields for calico
Fixes #
```
```
```release-note
add replicas and nodeselector fields for calico
```
```docs
```
=> add replicas and nodeselector fields for calico

cmd/kk/pkg/binaries/kubernetes.go, cmd/kk/pkg/images/tasks.go, cmd/kk/pkg/version/kubernetes/version_enum.go
/kind cleanup
update kube-vip version to v0.7.2
Fixes #
```
```
```release-note
update kube-vip version to v0.7.2
```
```docs
```
=> update kube-vip version to v0.7.2

pkg/service/operation/file/template.go
Fixes #
```
```
```release-note
```
```docs
```
=> fix: close file

cmd/kk/cmd/create/phase/init.go, cmd/kk/cmd/upgrade/phase/images.go, cmd/kk/cmd/upgrade/phase/nodes.go
fix function name in comment
Fixes #
```
```
```release-note
```
```docs
```
=> chore: fix function name in comment

cmd/kk/app/server.go, go.mod, pkg/project/project.go
Fixes #
```
```
```release-note
fix: Modify comments
```
```docs
```
=> fix: Modify comments

builtin/fs.go, builtin/inventory/config.yaml, builtin/inventory/inventory.yaml, builtin/roles/install/cri/tasks/install_containerd.yaml, cmd/kk/app/options/builtin.go, cmd/kk/app/options/option.go, example/Makefile, pkg/apis/kubekey/v1/config_types.go, pkg/connector/connector.go, pkg/connector/local_connector.go, pkg/connector/ssh_connector.go, pkg/controllers/pipeline_controller.go, pkg/modules/command.go, pkg/modules/command_test.go, pkg/modules/copy.go, pkg/modules/module.go, pkg/modules/module_test.go, pkg/modules/template.go, pkg/project/builtin.go, pkg/project/git.go, pkg/project/local.go, pkg/project/project.go, plugins/playbooks/sonobuoy.yaml, plugins/roles/etcd/backup/defaults/main.yaml, plugins/roles/etcd/restore/defaults/main.yaml, plugins/roles/sonobuoy/defaults/main.yaml, plugins/roles/sonobuoy/tasks/main.yaml, plugins/roles/sonobuoy/templates/plugins/e2e-ks.yaml, plugins/roles/sonobuoy/templates/plugins/kube-bench-master.yaml, plugins/roles/sonobuoy/templates/plugins/kube-bench.yaml
/kind feature
1. add sonobuoy plugin
execute the sonobuoy in a node. use kubeconfig to connect kubernetes cluster.
the kubernetes cluster will create sonobuoy job.
2. fixed `--set` is invalid in array value
3. change Connector method CopyFile to PutFile
4. fixed copy or template dir invalid
Fixes #
```
```
```release-note
add sonobuoy plugin
```
```docs
```
=> feat: add sonobuoy plugin.

pkg/connector/connector.go, pkg/connector/kubernetes_ connector.go, pkg/connector/local_connector.go, pkg/connector/ssh_connector.go, plugins/playbooks/sonobuoy.yaml, plugins/roles/sonobuoy/defaults/main.yaml, plugins/roles/sonobuoy/tasks/main.yaml, plugins/roles/sonobuoy/templates/plugins/e2e-ks.yaml, plugins/roles/sonobuoy/templates/plugins/kube-bench-master.yaml, plugins/roles/sonobuoy/templates/plugins/kube-bench.yaml
/kind feature
when set connector to kubernetes. it will execute command local with environment: `KUBECONFIG`
the kubeconfig file will store in {{ work_dir }}/kubernetes/{{ inventory_name }}
Fixes #
```
```
```release-note
add kubernetes connector
```
```docs
```
=> feat: add kubernetes connector

builtin/roles/install/etcd/defaults/main.yaml, builtin/roles/install/etcd/files/etcd.service, builtin/roles/install/etcd/tasks/install_etcd.yaml, builtin/roles/precheck/env_check/tasks/cri.yaml, builtin/roles/precheck/env_check/tasks/etcd.yaml, builtin/roles/precheck/env_check/tasks/main.yaml, builtin/roles/precheck/env_check/tasks/network.yaml, builtin/roles/precheck/env_check/tasks/nfs.yaml, builtin/roles/precheck/env_check/tasks/os.yaml, pkg/converter/tmpl/filter_extension.go, pkg/converter/tmpl/filter_extension_test.go, pkg/converter/tmpl/template_test.go, pkg/executor/executor.go
/kind feature
1. add io check for etcd node.
2. add configuration parameters to configure etcd's network traffic priority, CPU priority, and CPU mode.
Fixes #
```
```
```release-note
```
```docs
https://cwiki.yunify.com/pages/viewpage.action?pageId=145920824
https://etcd.io/docs/v3.5/tuning/
```
=> feat: add etcd io precheck.

builtin/playbooks/artifact_export.yaml, builtin/playbooks/artifact_images.yaml, builtin/playbooks/precheck.yaml, builtin/roles/init/init-artifact/defaults/main.yaml, builtin/roles/init/init-artifact/tasks/download_by_curl.yaml, builtin/roles/init/init-artifact/tasks/main.yaml, builtin/roles/install/image-registry/defaults/main.yaml, builtin/roles/install/image-registry/tasks/load_images.yaml, builtin/roles/install/image-registry/tasks/main.yaml, builtin/roles/install/image-registry/templates/harbor.config, builtin/roles/precheck/artifact_check/tasks/main.yaml, cmd/kk/app/artifact.go, cmd/kk/app/options/artifact.go, cmd/kk/app/options/create.go, cmd/kk/app/options/option.go, go.mod, go.sum, pkg/converter/tmpl/template_test.go, pkg/modules/gen_cert.go, pkg/modules/gen_cert_test.go, pkg/modules/image.go, pkg/modules/module.go, pkg/variable/helper.go
/feature
add artifact command to export offline package and sync images
`kk artifact export`: export offline package which contains images
the images will store local: the blobs store in the same directory, the manifest store in separate directories。
`kk artifact images`: sync local images to remote.
should set necessary arguments.
test result: will sync to remote registry
Fixes #
```
```
```release-note
add artifact command
```
```docs
https://github.com/oras-project/oras-go
```
=> feat: Add artifact command

builtin/playbooks/precheck.yaml, builtin/roles/init/init-os/tasks/init_repository.yaml, builtin/roles/precheck/env_check/defaults/main.yaml, builtin/roles/precheck/env_check/tasks/cri.yaml, builtin/roles/precheck/env_check/tasks/etcd.yaml, builtin/roles/precheck/env_check/tasks/main.yaml, builtin/roles/precheck/env_check/tasks/network.yaml, builtin/roles/precheck/env_check/tasks/nfs.yaml, builtin/roles/precheck/env_check/tasks/os.yaml, cmd/kk/app/options/precheck.go, cmd/kk/app/pipeline.go, cmd/kk/app/precheck.go, cmd/kk/app/run.go, pkg/manager/controller_manager.go, pkg/proxy/transport.go
/kind feature
1. add check item for kk precheck command
2. when mount iso, bak specify file for repository
Fixes #
```
```
```release-note
```
```docs
```
=> feat: add check item for kk precheck command

pkg/apis/core/v1/base.go, pkg/apis/kubekey/v1alpha1/task_types.go, pkg/executor/executor.go
/kind feature
add ignore_errors to playbook, role and block.
the task use the most closely configuration.
Fixes #
```
```
```release-note
add ignore_errors to playbook, role and block.
```
```docs
```
=> fix: add ignore_errors to playbook, role and block

README.md, builtin/roles/precheck/env_check/tasks/network.yaml, docs/zh/001-project.md, docs/zh/002-playbook.md, docs/zh/003-role.md, docs/zh/004-task.md, docs/zh/005-module.md, docs/zh/101-syntax.md, docs/zh/201-variable.md, pkg/apis/core/v1/role.go
add documentation
Fixes #
```
```
```release-note
add documentation
```
```docs
```
=> doc: add docs

.github/.stale.yaml, .github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/custom.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/OWNERS, .github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml, .github/release-drafter.yml, .github/settings.yml, .github/workflows/build-multiarch.yaml, .github/workflows/goreleaser.yml, .goreleaser.yml, Makefile
/kind feature
Fixes #
```
```
```release-note
add github action
```
```docs
```
=> add github action

.github/workflows/build-multiarch.yaml, .github/workflows/goreleaser.yml
/kind feature
Fixes #
```
```
```release-note
none
```
```docs
```
=> fix: release action error

.github/workflows/goreleaser.yml
Fixes #
```
```
```release-note
```
```docs
```
=> fix: golangci-lint

.goreleaser.yml
Fixes #
```
```
```release-note
none
```
```docs
```
=> fix: add goreleaser

builtin/roles/init/init-artifact/tasks/pki.yaml, builtin/roles/precheck/env_check/tasks/cri.yaml, builtin/roles/precheck/env_check/tasks/etcd.yaml, builtin/roles/precheck/env_check/tasks/network.yaml, builtin/roles/precheck/env_check/tasks/nfs.yaml, builtin/roles/precheck/env_check/tasks/os.yaml, pkg/apis/core/v1/taggable.go, pkg/executor/executor.go
/kind feature
when set tag in parent block. tag can be inherited by it's child block
Fixes #
```
```
```release-note
tag can be inherited
```
```docs
```
=> fix: tag can be inherited

cmd/kk/apis/kubekey/v1alpha2/dns_types.go, cmd/kk/pkg/bootstrap/os/templates/init_script.go
/kind feature
Support config custom hosts entry of cluster nodes.
For example, use config below to config harbor hosts entry:
```yaml
spec:
dns:
nodeEtcHosts: |
192.168.0.69  harbor.example.com
```
Fixes #
```
```
```release-note
Support spec.dns.nodeEtcHosts property to add node /etc/hosts entry.
```
```docs
```
=> feature/ support add nodeEtcHosts entry

cmd/kk/pkg/bootstrap/os/templates/init_script.go, cmd/kk/pkg/bootstrap/precheck/tasks.go, cmd/kk/pkg/kubernetes/kubernetes_status.go
/kind cleanup
refine tasks logic
- kernel config
```
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
```
- The 'featuregate' parameter is not subject to mandatory checks.
- Avoid repeatedly fetching initial data.
Fixes #
```
```
```release-note
```
```docs
```
=> refine tasks logic

cmd/controller-manager/app/server.go, cmd/kk/app/artifact.go, cmd/kk/app/certs.go, cmd/kk/app/create.go, cmd/kk/app/init.go, cmd/kk/app/precheck.go, cmd/kk/app/run.go, pkg/connector/kubernetes_ connector.go, pkg/modules/fetch.go, pkg/modules/gen_cert_test.go, pkg/modules/image.go, pkg/proxy/internal/file_storage.go, pkg/variable/source/source.go, plugins/roles/sonobuoy/tasks/main.yaml
/kind feature
Fixes #
```
```
```release-note
set base default dir for kubernetes connector.
```
```docs
```
=> feat: set base default dir for kubernetes connector.

.goreleaser.yml, builtin/inventory/config.yaml, cmd/kk/app/options/builtin.go
/kind bug
change yaml dependency package to k8s.io/apimachinery/pkg/util/yaml
Fixes #
```
```
```release-note
defaultConfig is not render
```
```docs
```
=> bug: defaultConfig is not render.

builtin/playbooks/certs_renew.yaml, builtin/playbooks/create_cluster.yaml, pkg/project/helper.go
/kind bug
var_files defined error, change to vars_files
Fixes #
```
```
```release-note
var_files defined error
```
```docs
```
=> fix: var_files defined error

builtin/roles/install/kubernetes/tasks/init_kubernetes.yaml, pkg/connector/connector.go, pkg/connector/ssh_connector.go, pkg/modules/command_test.go
/kind feature
Fixes #
```
```
```release-note
add ssh private key connector method.
```
```docs
```
=> add ssh private key connector method

builtin/roles/install/kubernetes/tasks/deploy_cluster_dns.yaml, builtin/roles/install/kubernetes/templates/dns/coredns.deployment
Fixes #
1. use pretty format configmap
before: the Corefile show in one line with string. 
after: the Corefile show with pretty format.
2. use custom service(coredns) instance of default service(kube-dns)
```
```
```release-note
coredns configmap is not correct.
```
```docs
```
=> fix: coredns configmap is not correct.

builtin/roles/install/kubernetes/defaults/main.yaml, builtin/roles/install/kubernetes/tasks/deploy_cluster_dns.yaml, builtin/roles/install/kubernetes/templates/dns/nodelocaldns.daemonset, builtin/roles/install/kubernetes/templates/kubeadm/kubeadm-init.v1beta2, builtin/roles/install/kubernetes/templates/kubeadm/kubeadm-init.v1beta3, docs/zh/101-syntax.md, pkg/converter/tmpl/filter_extension.go, pkg/converter/tmpl/filter_extension_test.go
/kind feature
1. add param to ip_range.
2. fix nodelocaldns is not deploy.
Fixes #
```
```
```release-note
add param to ip_range.
```
```docs
```
=> feat: add param to ip_range.

builtin/roles/install/kubernetes/templates/dns/coredns.deployment
/kind bug
Fixes #
```
```
```release-note
misspelling
```
```docs
```
=> fix: misspelling

README_ja-JP.md, README_zh-CN.md
Fixes #
```
```
```release-note
```
```docs
```
=> docs: add Japanese README

cmd/kk/pkg/version/kubesphere/templates/cc_v341.go
/kind bug
fix: KKZONE=cn is invalid for kubesphere v3.4.1
Fixes #
```
```
```release-note
fix: KKZONE=cn is invalid for kubesphere v3.4.1
```
```docs
```
=> fix: KKZONE=cn is invalid for kubesphere v3.4.1

config/helm/values.yaml, pkg/converter/internal/functions.go
/kind cleanup
Fixes #
```
```
```release-note
```
```docs
```
=> feat: delete unuse function.

builtin/playbooks/create_cluster.yaml
feature
Modify addons/* setup hosts, from `k8s_cluster|random` to `kube_control_plane|random`
Fixes None
=> feat: modify addons/* setup hosts

cmd/kk/app/options/option.go, pkg/apis/kubekey/v1/config_types.go, pkg/apis/kubekey/v1/config_types_test.go
/kind feature
1, `--set` can set multi-value by separator `,` like this: `--set k1=v1,k2=v2`
2, compatible v1 string contains `=`
Fixes #
```
```
```release-note
```
```docs
```
=> feat: --set contains multi string "=".

cmd/kk/pkg/images/tasks.go
/kind bug
fix: push manifest failed if private registry contian multi-path
Fixes #
```
```
```release-note
fix: push manifest failed if private registry contian multi-path
```
```docs
```
=> fix: push manifest failed if private registry contian multi-path

builtin/roles/addons/cni/defaults/main.yaml, builtin/roles/addons/cni/tasks/cilium.yaml
bug
add/modify missing value
Add `operator_replicas` param for cilium, and reformat code.
=> Fix k8s cni binary template bug

.github/workflows/golangci-lint.yml
Fixes #
```
```
```release-note
```
```docs
```
=> feat: support run without vendor.

OWNERS, pkg/proxy/api_resources.go, pkg/proxy/transport.go
/kind bug
Fixes #
```
```
```release-note
none
```
```docs
```
=> fix: error local router.

pkg/manager/command_manager.go
/kind bug
Fixes #
```
```
```release-note
none
```
```docs
```
=> fix: graceful delete runtime dir.

builtin/playbooks/artifact_export.yaml, builtin/roles/init/init-artifact/tasks/main.yaml, pkg/modules/image.go
Fixes #
```
```
```release-note
none
```
```docs
fix: image pull failed
```
=> fix: image pull failed

cmd/kk/app/artifact.go, pkg/manager/command_manager.go
/kind bug
Fixes #
```
```
```release-note
artifact package exclude `certs`
```
```docs
```
=> fix: artifact package exclude `certs`

pkg/connector/connector.go, pkg/connector/kubernetes_connector.go, pkg/connector/local_connector.go, pkg/connector/local_connector_test.go, pkg/connector/ssh_connector.go, pkg/const/common.go, pkg/manager/command_manager.go
/kind feature
Fixes #
```
```
```release-note
```
```docs
```
=> add `sudo` and SHELL in connector

pkg/connector/connector.go, pkg/connector/kubernetes_connector.go, pkg/connector/local_connector.go, pkg/connector/ssh_connector.go, pkg/const/common.go, pkg/executor/pipeline_executor.go, pkg/manager/command_manager.go
/kind bug
add `sudo_password` to use sudo mod.
Fixes #
```
```
```release-note
add `sudo_password` to use sudo mod.
```
```docs
```
=> add `sudo_password` to use sudo mod.

cmd/kk/pkg/artifact/manifest.go, cmd/kk/pkg/images/images.go
/kind feature
support use aliyuncs for manifest
Fixes #
```
```
```release-note
support use aliyuncs for manifest
```
```docs
```
=> support use aliyuncs for manifest

cmd/kk/pkg/artifact/templates/manifest.go, cmd/kk/pkg/files/file.go, feature/builtin/roles/init/init-artifact/defaults/main.yaml, feature/hack/auto-update-version.py, feature/hack/fetch-kubernetes-hash.sh, feature/hack/sync-components.sh, hack/auto-update-version.py, hack/fetch-kubernetes-hash.sh, hack/sync-components.sh
/kind cleanup
update k8s base url to https://dl.k8s.io
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/change-package-repository/
https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
Fixes #
```
```
```release-note
update k8s base url to https://dl.k8s.io
```
```docs
```
=> update k8s base url to https://dl.k8s.io

builtin/roles/install/cri/defaults/main.yaml, builtin/roles/install/image-registry/defaults/main.yaml, go.mod
/kind bug
Fixes #
```
```
```release-note
None
```
```docs
```
=> fix: failed to install without image_registry

builtin/roles/install/cri/defaults/main.yaml, builtin/roles/install/image-registry/defaults/main.yaml, go.mod
Reverts kubesphere/kubekey#2442
=> Revert "fix: failed to install without image_registry"

pkg/service/containermanager/templates/config.toml
Fixes #
```
```
```release-note
None
```
```docs
```
=> support changing root dir

cmd/kk/apis/kubekey/v1alpha2/cluster_types.go, cmd/kk/pkg/bootstrap/registry/tasks.go, cmd/kk/pkg/bootstrap/registry/templates/harbor.go, cmd/kk/pkg/bootstrap/registry/templates/harbor.yml.tmpl, docs/config-example.md
/kind feature
support config registry data dir:
```yaml
registry:
...
registryDataDir: /mnt/registry
```
Fixes #
```
```
```release-note
```
```docs
```
=> feat: support config registry data dir

cmd/kk/apis/kubekey/v1alpha2/cluster_types.go, cmd/kk/pkg/bootstrap/registry/module.go, cmd/kk/pkg/container/containerd.go, cmd/kk/pkg/container/docker.go, cmd/kk/pkg/container/module.go, cmd/kk/pkg/container/templates/containerd_config.go, cmd/kk/pkg/container/templates/docker_config.go, docs/config-example.md
/kind feature
support config docker contaninerd data dir:
```yaml
registry:
...
containerdDataDir: /var/lib/containerd
dockerDataDir: /var/lib/docker
```
Fixes #
```
```
```release-note
```
```docs
```
=> Feat support config docker contaninerd data dir

api/project/v1/conditional.go, api/project/v1/playbook.go, pkg/const/common.go, pkg/converter/tmpl/template.go, pkg/converter/tmpl/template_test.go, pkg/executor/task_executor.go, pkg/modules/assert.go, pkg/modules/assert_test.go, pkg/modules/copy.go, pkg/modules/debug.go, pkg/modules/set_fact.go, pkg/modules/template.go, pkg/variable/helper.go, pkg/variable/helper_test.go, pkg/variable/variable_get.go, pkg/variable/variable_merge.go
/kind feature
Extended parsing of go/template output
Fixes #
```
```
```release-note
Adding generic methods to template parsing
```
```docs
```
=> feat: Adding generic methods to template parsing

builtin/capkk/roles/precheck/env_check/tasks/network.yaml, builtin/capkk/roles/uninstall/kubernetes/tasks/network.yaml, pkg/connector/connector.go, pkg/connector/kubernetes_connector.go, pkg/connector/local_connector.go, pkg/connector/ssh_connector.go, pkg/const/common.go, pkg/controllers/core/pipeline_controller.go, pkg/executor/task_executor.go
/kind bug
use EOF to pass command. the actual command like:
Fixes #2497 
```
```
```release-note
ssh command no need to escape
```
```docs
```
=> fix: command no need to escape

.github/workflows/kubernetes-auto-support.yaml, cmd/kk/pkg/version/kubernetes/version_enum.go
/kind cleanup
Supported upgrade k8s to v1.32
Fixes #
```
```
```release-note
Supported upgrade k8s to v1.32
```
```docs
```
=> Supported upgrade k8s to v1.32

cmd/kk/app/builtin/create.go, cmd/kk/app/options/builtin/create.go
/kind feature
add create config command.
- `create config` output as stdout
- `create config -o xxx` output as a file
Fixes #
```
```
```release-note
add create config command
```
```docs
```
=> feat: add create config command

cmd/kk/app/builtin/delete.go, cmd/kk/app/options/builtin/delete.go, pkg/converter/tmpl/template_test.go, pkg/variable/helper.go, pkg/variable/variable.go, pkg/variable/variable_get.go, pkg/variable/variable_merge.go
Thread-safe reading and writing.
change Lock to RWLock to avoid read value when value is writing.
Fixes #
```
```
```release-note
Thread-safe reading and writing
```
```docs
```
=> feat: Thread-safe reading and writing

api/core/v1alpha1/task_types.go, api/project/v1/block.go, builtin/capkk/playbooks/add_node.yaml, builtin/capkk/roles/install/cni/tasks/calico.yaml, builtin/capkk/roles/install/cni/tasks/main.yaml, builtin/capkk/roles/install/kubernetes/tasks/main.yaml, builtin/core/roles/install/cni/tasks/calico.yaml, builtin/core/roles/precheck/env_check/tasks/etcd.yaml, pkg/converter/converter.go, pkg/executor/task_executor.go
/kind feature
add register_type to register value better. support: string(default), json, yaml.
Fixes #
```
```
```release-note
add register_type
```
```docs
```
=> feat: add register_type

builtin/capkk/roles/uninstall/cri/tasks/uninstall_cridockerd.yaml, builtin/capkk/roles/uninstall/cri/tasks/uninstall_docker.yaml, builtin/core/roles/uninstall/cri/tasks/uninstall_cridockerd.yaml, builtin/core/roles/uninstall/cri/tasks/uninstall_docker.yaml, builtin/core/roles/uninstall/etcd/tasks/main.yaml, builtin/core/roles/uninstall/kubernetes/tasks/main.yaml
/kind feature
add more ignore_errors when run kk delete xxx. 
Fixes #
```
```
```release-note
add more ignore_errors when run kk delete xxx. 
```
```docs
```
=> feat: add more ignore_errors when kk delete

cmd/kk/pkg/version/kubernetes/version_enum.go
/kind cleanup
Supported upgrade k8s to v1.33
Fixes #
```
```
```release-note
Supported upgrade k8s to v1.33
```
```docs
```
=> Supported upgrade k8s to v1.33

.github/workflows/golangci-lint.yaml, builtin/core/roles/uninstall/kubernetes/tasks/main.yaml
delete /var/log/pods/ when delete cluster.
If /var/log/pods/ is not cleaned up, static pods may accumulate unexpected restarts due to lingering log files interfering with their lifecycle.
Fixes #
```
```
```release-note
delete /var/log/pods/
```
```docs
```
=> feat: delete /var/log/pods/

cmd/kk/app/options/option.go
/kind bug
Fixes #
```
```
```release-note
fix: support [a].[b] in set argument
```
```docs
```
=> fix: support [a].[b] in set argument

builtin/capkk/roles/install/cri/defaults/main.yaml, builtin/capkk/roles/install/cri/templates/containerd.config, builtin/capkk/roles/install/cri/templates/cri_docker.service, builtin/core/defaults/config/v1.23.15.yaml, builtin/core/roles/install/cri/templates/containerd.config, builtin/core/roles/install/cri/templates/cri_docker.service, builtin/core/roles/kubernetes/init-kubernetes/templates/kubeadm/kubeadm-init.v1beta2, builtin/core/roles/kubernetes/init-kubernetes/templates/kubeadm/kubeadm-init.v1beta3, builtin/core/roles/kubernetes/join-kubernetes/templates/kubeadm/kubeadm-join.v1beta2, builtin/core/roles/kubernetes/join-kubernetes/templates/kubeadm/kubeadm-join.v1beta3
/kind design
configurable sandbox image like: kk create cluster --set cri.sandbox_image_tag=3.6
Fixes #
```
```
```release-note
configurable sandbox image
```
```docs
```
=> fix: configurable sandbox image

builtin/core/roles/init/init-artifact/defaults/main.yaml
/kind design
change kubernetes download url
Fixes #
```
```
```release-note
change kubernetes download url
```
```docs
```
=> fix: change kubernetes download url

api/project/v1/playbook.go, cmd/kk/app/options/run.go, docs/zh/modules/prometheus.md, pkg/connector/connector.go, pkg/connector/prometheus_connector.go, pkg/const/common.go, pkg/executor/task_executor.go, pkg/modules/debug.go, pkg/modules/debug_test.go, pkg/modules/module.go, pkg/modules/prometheus.go, pkg/modules/prometheus_test.go, pkg/variable/helper.go, pkg/variable/helper_test.go
```
/kind feature
```
support prometheus tasks in playbook
```release-note
support prometheus tasks in playbook
```
```docs
```
1. Query with formatting options
```
tasks:
- name: Get Prometheus metrics
prometheus:
query: sum(rate(node_cpu_seconds_total{mode='idle'}[5m]))
format: value # or table 
register: prometheus_result
- name: Debug Prometheus Module
debug:
msg: "{{ .prometheus_result }}"
```
2. Query with time parameter
```
tasks:
- name: Get Prometheus metrics
prometheus:
query: go_goroutines
time: 2025-05-15T12:00:00Z
register: prometheus_result
- name: Debug Prometheus Module
debug:
msg: "{{ .prometheus_result }}"
```
3. Get Prometheus server info
```
tasks:
- name: Get Prometheus metrics
prometheus:
info: true
register: prometheus_result
- name: Debug Prometheus Module
debug: …
```
=> support prometheus tasks

cmd/kk/app/options/builtin/add.go, cmd/kk/app/options/builtin/builtin.go, cmd/kk/app/options/builtin/create.go, cmd/kk/app/options/builtin/delete.go
Based on the Kubernetes version, each has recommended CRI types and versions. Simply using `--container-manager` to switch CRIs is not sufficient.
It's better to configure it in `config.yaml` (with recommended CRI versions provided as comments when generating this file).
Fixes #
```
```
```release-note
delete --container-manager argument
```
```docs
```
=> feat: delete --container-manager argument

builtin/capkk/roles/install/cri/defaults/main.yaml, builtin/core/roles/install/cri/defaults/main.yaml
/kind bug
Fixes #
```
```
```release-note
none
```
```docs
```
=> fix: error cri_socket

pkg/connector/ssh_connector.go, pkg/const/common.go
/kind feature
add ssh auth private_key_content in inventory like:
```yaml
apiVersion: kubekey.kubesphere.io/v1
kind: Inventory
metadata:
name: default
spec:
hosts:
i-ntnxgrer:
connector:
host: 172.16.0.3
private_key_content: |
-----BEGIN OPENSSH PRIVATE KEY-----
xxxxxx
-----END OPENSSH PRIVATE KEY-----
internal_ipv4: 172.16.0.3
i-xcg3bb1u:
connector:
host: 172.16.0.4
private_key_content: |
-----BEGIN OPENSSH PRIVATE KEY-----
xxxxxxx
-----END OPENSSH PRIVATE KEY-----
internal_ipv4: 172.16.0.4
```
Fixes #
```
```
```release-note
add ssh auth private_key_content
```
```docs
```
=> feat: add ssh auth private_key_content

pkg/modules/assert.go, pkg/modules/command.go, pkg/modules/copy.go, pkg/modules/debug.go, pkg/modules/fetch.go, pkg/modules/gen_cert.go, pkg/modules/image.go, pkg/modules/module.go, pkg/modules/set_fact.go, pkg/modules/template.go
Add details to the module comments.
Fixes #
```
```
```release-note
none
```
```docs
```
=> doc: Add details to the module comments.

cmd/kk/app/options/web.go, cmd/kk/app/web.go, pkg/manager/manager.go, pkg/manager/web_manager.go, pkg/web/openapi.go, pkg/web/schema.go
/kind feature
run `kk web --schema-path xxx` to serve schema json
test results:
Fixes #
```
```
```release-note
add schema service
```
```docs
```
=> feat: add schema service

builtin/core/roles/kubernetes/init-kubernetes/tasks/init_kubernetes.yaml, builtin/core/roles/kubernetes/join-kubernetes/tasks/join_kubernetes.yaml, pkg/converter/tmpl/template_test.go
/kind feature
add annotations to node
Fixes #
https://github.com/kubesphere/kubekey/issues/1785
```
```
```release-note
add annotations to node
```
```docs
```
=> feat: add annotations to node

.golangci.yaml, builtin/core/roles/precheck/env_check/tasks/kubernetes.yaml, pkg/executor/task_executor.go, pkg/web/handler.go
/kind bug
Before: The progress bar display for file operations is not working properly. 
After: Disable the progress bar display for file operations.
Fixes #
```
```
```release-note
display task progressbar in file.
```
```docs
```
=> fix: display task progressbar in file.

pkg/executor/task_executor.go
/kind feature
more fast execute task
Fixes #
```
```
```release-note
more fast execute task
```
```docs
```
=> feat: more fast execute task

pkg/project/project.go, pkg/variable/helper.go, pkg/variable/yaml.go
For variables defined in Playbook files, the following precedence should be followed: **vars** > **vars_files** (in order).
Later-defined variables **must not override** existing ones, as the configuration and inventory values represent the initial set of variables.
*(Note: This maintains clarity while emphasizing the priority and reasoning behind the rule.)*
Fixes #
```
```
```release-note
Modify the node parsing order.
```
```docs
```
=> fix: Modify the node parsing order.

builtin/capkk/roles/precheck/env_check/defaults/main.yaml, builtin/core/defaults/config/v1.23.yaml, builtin/core/defaults/config/v1.24.yaml, builtin/core/defaults/config/v1.25.yaml, builtin/core/defaults/config/v1.26.yaml, builtin/core/defaults/config/v1.27.yaml, builtin/core/defaults/config/v1.28.yaml, builtin/core/defaults/config/v1.29.yaml, builtin/core/defaults/config/v1.30.yaml, builtin/core/defaults/config/v1.31.yaml, builtin/core/defaults/config/v1.32.yaml, builtin/core/defaults/config/v1.33.yaml, builtin/core/roles/precheck/env_check/defaults/main.yaml, cmd/kk/app/options/builtin/builtin.go, cmd/kk/app/options/builtin/create.go
add default kubernetes version from v1.23.x to v1.33.x
Fixes #
```
```
```release-note
add more default kubernetes version
```
```docs
```
=> feat: add more default kubernetes version

builtin/capkk/roles/uninstall/cri/tasks/uninstall_containerd.yaml, builtin/capkk/roles/uninstall/cri/tasks/uninstall_cridockerd.yaml, builtin/capkk/roles/uninstall/cri/tasks/uninstall_docker.yaml, builtin/capkk/roles/uninstall/kubernetes/tasks/kubernetes.yaml, builtin/core/roles/uninstall/cri/tasks/uninstall_containerd.yaml, builtin/core/roles/uninstall/cri/tasks/uninstall_cridockerd.yaml, builtin/core/roles/uninstall/cri/tasks/uninstall_docker.yaml, builtin/core/roles/uninstall/etcd/tasks/main.yaml, builtin/core/roles/uninstall/kubernetes/tasks/kubernetes.yaml
/kind cleanup
more deep clear
Fixes #
```
```
```release-note
none
```
```docs
```
=> fix: more deep clear

cmd/kk/pkg/bootstrap/os/tasks.go, go.mod, go.sum
fix: #2539
Fixes #
```
```
```release-note
```
```docs
```
=> fix: umount /run/calico/cgroup first before clear cluster

cmd/kk/app/options/builtin/add.go, cmd/kk/app/options/builtin/artifact.go, cmd/kk/app/options/builtin/builtin.go, cmd/kk/app/options/builtin/certs.go, cmd/kk/app/options/builtin/create.go, cmd/kk/app/options/builtin/delete.go, cmd/kk/app/options/builtin/init.go, cmd/kk/app/options/builtin/precheck.go, cmd/kk/app/options/option.go
/kind cleanup
Fixes #
clear default inventory and configuration logic.
```
```
```release-note
none
```
```docs
```
=> fix: clear default inventory and configuration logic.

builtin/capkk/playbooks/add_node.yaml, builtin/capkk/roles/precheck/env_check/defaults/main.yaml, builtin/capkk/roles/precheck/env_check/tasks/kubernetes.yaml, builtin/capkk/roles/precheck/env_check/tasks/os.yaml, builtin/capkk/roles/uninstall/cri/tasks/main.yaml, builtin/core/playbooks/add_nodes.yaml, builtin/core/playbooks/hook/pre_install.yaml, builtin/core/roles/install/cni/defaults/main.yaml, builtin/core/roles/install/image-registry/tasks/install_docker.yaml, builtin/core/roles/kubernetes/pre-kubernetes/tasks/high-availability/kube_vip.yaml, builtin/core/roles/kubernetes/pre-kubernetes/templates/haproxy/haproxy.cfg, builtin/core/roles/kubernetes/pre-kubernetes/templates/kubelet/kubelet.env, builtin/core/roles/precheck/env_check/defaults/main.yaml, builtin/core/roles/precheck/env_check/tasks/kubernetes.yaml, builtin/core/roles/precheck/env_check/tasks/network.yaml, builtin/core/roles/precheck/env_check/tasks/os.yaml, builtin/core/roles/uninstall/cri/tasks/main.yaml
/kind cleanup
move the binary_type fact setting to the pre_install hook
Fixes #
```
```
```release-note
none
```
```docs
```
=> cleanup: move the binary_type fact setting to the pre_install hook

cmd/kk/pkg/bootstrap/precheck/tasks.go
/kind bug
当前通过 which 来判断 baseSoftware 是否存在的方式在下面情况下会表现错误：
不应该通过是否包含 not found 来判断 software 是否存在，而应该使用系统调用。
Fixes #
```
```
```release-note
```
```docs
```
=> fix: replace 'which' with 'command -v'

.golangci.yaml, builtin/core/playbooks/host_check.yaml, pkg/const/env.go, pkg/executor/playbook_executor.go, pkg/modules/command.go, pkg/modules/result.go, pkg/variable/helper.go, pkg/variable/variable.go, pkg/variable/variable_get.go, pkg/variable/variable_merge.go, pkg/variable/variable_merge_test.go, pkg/web/api/result.go, pkg/web/corev1.go, pkg/web/resources.go
/feature
1. Modify the response for GET /kapis/kubekey.kubesphere.io/v1/namespaces/{namespace}/inventories/{inventory}/hosts
2. Add more types of result modules.
Fixes #
```
```
```release-note
none
```
```docs
```
=> fix: add index to groups

pkg/executor/playbook_executor.go
/kind bug
error update playbook
Fixes #
```
```
```release-note
none
```
```docs
```
=> fix: error update playbook

pkg/executor/block_executor.go
/kind bug
The next task should continue executing if the rescue task succeeds.
test results
rescue succeed:
rescue failed:
Fixes #
```
```
```release-note
rescue success continue execute playbook
```
```docs
```
=> feat: rescue success continue execute playbook

builtin/core/playbooks/vars/create_cluster_kubernetes.yaml, builtin/core/roles/kubernetes/init-kubernetes/templates/dns/nodelocaldns.yaml, builtin/core/roles/kubernetes/init-kubernetes/templates/kubeadm/kubeadm-init.v1beta2, builtin/core/roles/kubernetes/init-kubernetes/templates/kubeadm/kubeadm-init.v1beta3, pkg/executor/block_executor.go
/kind feature
make the nodelocaldns bind IP configurable
Fixes #
```
```
```release-note
none
```
```docs
```
=> feat: make the nodelocaldns bind IP configurable.

config/file.go, config/web/index.html, pkg/const/web.go, pkg/manager/web_manager.go, pkg/modules/gen_cert.go, pkg/web/corev1.go, pkg/web/openapi.go, pkg/web/resources.go
/kind feature
add webUI route
Fixes #
```
```
```release-note
add webUI route
```
```docs
```
=> feat: add webUI route

docs/zh/modules/image.md, pkg/modules/image.go
/kind feature
add platform input args when pull image
Fixes #
```
None
```
```release-note
None
```
```docs
```
=> feature: add pull image platform

api/project/v1/base.go, pkg/executor/task_executor.go, pkg/modules/set_fact.go, pkg/project/project.go, pkg/project/project_test.go, pkg/variable/helper.go, pkg/variable/variable_merge.go, pkg/variable/variable_merge_test.go
/kind feature
support same key in different file
Fixes #
```
None
```
```release-note
support same key in different file
```
```docs
```
=> feature: support same key in different file

builtin/core/roles/defaults/vars/v1.23.yaml, builtin/core/roles/defaults/vars/v1.24.yaml, builtin/core/roles/defaults/vars/v1.25.yaml, builtin/core/roles/defaults/vars/v1.26.yaml, builtin/core/roles/defaults/vars/v1.27.yaml, builtin/core/roles/defaults/vars/v1.28.yaml, builtin/core/roles/defaults/vars/v1.29.yaml, builtin/core/roles/defaults/vars/v1.30.yaml, builtin/core/roles/defaults/vars/v1.31.yaml, builtin/core/roles/defaults/vars/v1.32.yaml, builtin/core/roles/defaults/vars/v1.33.yaml
/kind bug
Fixes #
error format for kubernetes version file
refer: https://github.com/kubesphere/kubekey/pull/2718
```
```
```release-note
none
```
```docs
```
=> fix: error format for kubernetes version file

builtin/core/playbooks/add_nodes.yaml, builtin/core/playbooks/artifact_export.yaml, builtin/core/playbooks/artifact_images.yaml, builtin/core/playbooks/certs_renew.yaml, builtin/core/playbooks/create_cluster.yaml, builtin/core/playbooks/delete_cluster.yaml, builtin/core/playbooks/delete_nodes.yaml, builtin/core/playbooks/delete_registry.yaml, builtin/core/playbooks/init_os.yaml, builtin/core/playbooks/init_registry.yaml, builtin/core/playbooks/precheck.yaml, builtin/core/roles/native/root/tasks/main.yaml
/kind bug
fix issue 6795
update /etc/sudoers ,add /usr/local/bin to secure_path
Fixes #
https://github.com/kubesphere/project/issues/6795
```
None
```
```release-note
fix issue 6795
```
```docs
```
=> bugfix : fix issue 6795

builtin/core/defaults/config/v1.33.yaml, builtin/core/roles/defaults/vars/v1.33.yaml
/kind bug
Fixes #
```
None
```
```release-note
change openebs version from 4.3 to 4.2
```
```docs
```
=> bugfix : change openebs version from 4.3 to 4.2

builtin/core/roles/native/dns/tasks/main.yaml
/kind bug
Fixes #
https://github.com/kubesphere/project/issues/6764
```
None
```
```release-note
fix issue 6764
```
```docs
```
=> bugfix : fix issue 6764

builtin/capkk/roles/install/storageclass/templates/local-volume.yaml, builtin/core/roles/storage-class/local/templates/local-volume.yaml
bugfix : fix a bug, openebs can not use leases
/kind bug
fix a bug, openebs can not use leases
Fixes #
```
None
```
```release-note
fix a bug, openebs can not use leases
```
```docs
```
=> bugfix : fix a bug, openebs can not use leases

builtin/capkk/roles/init/init-os/tasks/init_repository.yaml, builtin/core/roles/image-registry/docker-registry/tasks/main.yaml, builtin/core/roles/native/nfs/tasks/main.yaml, builtin/core/roles/native/repository/tasks/install_package.yaml, builtin/core/roles/native/repository/tasks/main.yaml, pkg/converter/tmpl/functions.go
bugfix: fix some system id error
/kind bug
when user use kylin, release id will shown as "\"kylin\""
fix release id shown value ,add unquote function
Fixes #
```
None
```
```release-note
fix release id shown value ,add unquote function
```
```docs
```
=> bugfix: fix some system id error

pkg/const/common.go, pkg/web/api/result.go, pkg/web/handler/resources.go, pkg/web/service.go
feat : add issue 6787
/kind feature
add one clieck host check function and api
Fixes #
https://github.com/kubesphere/project/issues/6787
```
None
```
```release-note
add one clieck host check function and api
```
```docs
```
=> feat : add issue 6787

builtin/core/roles/etcd/templates/backup.sh
etcdctl backup is not supported in api v3.
test results:
Fixes #
```
```
```release-note
fix: etcdctl backup is not supported
```
```docs
```
=> fix: backup not support in apiV3

builtin/core/playbooks/artifact_images.yaml, builtin/core/roles/download/tasks/images.yaml, builtin/core/roles/image-registry/tasks/main.yaml
/kind bug
Fixes #
```
None
```
```release-note
change download data config in some playbooks
```
```docs
```
=> bugfix: change download data config in some playbooks

pkg/web/handler/inventory.go
/kind bug
This update introduces a function to ensure that internal IPv4 addresses and SSH connections are unique across all hosts in the inventory. It checks for duplicates and returns an error if any are found, enhancing the integrity of the inventory data.
Fixes #
https://github.com/kubesphere/project/issues/6912
```
```
```release-note
feat: add validation for unique host variables in inventory
```
```docs
```
=> feat: add validation for unique host variables in inventory

builtin/core/defaults/config/v1.29.yaml, builtin/core/roles/defaults/vars/v1.33.yaml
/kind feature
change some config image tags
Fixes #
```
None
```
```release-note
change some config image tags
```
```docs
```
=> feat: change some image tags

cmd/kk/pkg/bootstrap/os/tasks.go, cmd/kk/pkg/utils/cgroups_linux.go, cmd/kk/pkg/utils/cgroups_unsupported.go
fix #2715
Fixes #
```
```
```release-note
```
```docs
```
=> fix: cgroups not supported on darwin
